### ISSUE TITLE
Feature: `helm rollback RELEASE VERSION` can rollback to a previous version

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1004]
A command named `helm rollback RELEASE [VERSION]` should be added to allow a user to replace the current version of a release with a previous version of a release.

Ideally, this would work not as an "upgrade" to an old version, but as a hard reset to the old version. In other words, it would re-create the old resources as they were, destroying the newer version first.

In the backend, the versioning and storage should look like this:

Record   |  Description
------- | -----
foo, v1    | Initial release

User runs `helm update foo`

Record   |  Description
------- | -----
foo, v1    | Initial release
foo, v2   | Upgraded release

User runs `helm rollback foo v1`

Record   |  Description
------- | -----
foo, v1    | Initial release
foo, v2   | Upgraded release
foo, v3 | Copy of "Initial release"

This way, a pristine and linear history is maintained.

Open question: For a rollback, to we re-template the release or re-release exactly? Re-templating might trigger certain functions like `date` to generate new values. To me, this sounds like a good thing.

**Comment by migmartri** [comment]
Hi,

Overall the process looks good to me although there are some considerations that we might want to take into account:

### k8s deployments

- How does this overlaps with the `k8s deployments` rollback feature? If we treat a rollback as essentially a new release. Should we also call rollback in the deployment object or just ignore this functionality?

Something interesting about the deployment's rollback is that the revision that becomes the active one disappears from the list so you do not end up in a cycle with the same version. This might not be a problem for us if we enforce the user to always set a release version. 

Example:

```
$ kubectl rollout history deployments/stacksmith-backend

deployments "stacksmith-backend":
REVISION	CHANGE-CAUSE
1		<none>
2		<none>
3		<none>
4		<none>
5		<none>
6		<none>

$ kubectl rollout undo deployments/stacksmith-backend
deployment "stacksmith-backend" rolled back

DeploymentRollback	Rolled back deployment "stacksmith-backend" to revision 5

$ kubectl rollout history deployments/stacksmith-backend
deployments "stacksmith-backend":
REVISION	CHANGE-CAUSE
1		<none>
2		<none>
3		<none>
4		<none>
6		<none>
7		<none>

(5 does not exist anymore)
```
### re-template

This can be dangerous since it does not guarantee immutability. 

As well as certain functions returning different values, an upgrade in the Helm/Tiller tool itself could also cause differences in the re-rendered templates.

I am not sure about how useful triggering functions like `date` would be since the k8s timestamp metadata of these new objects might be enough.

### Client side dependency

In order to rollback, should the client have all the requirements (values in values.yaml, etc) to create this previous version or everything will happen server-side? I prefer the latter.

> it would re-create the old resources as they were, destroying the newer version first.

What if the old resources can not be created? Image not published anymore, not accessible, etc?
