### ISSUE TITLE
Can't reuse a release name

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/helm#1016]
Create a chart release

```bash
$ helm install chart --name jojoba
jojoba
```

Delete the release

```bash
$ helm delete jojoba
```

Re-use the old release name in the next `helm install`:

```bash
$ helm install chart --name jojoba
Error: a release named "jojoba" already exists
```

**Comment by technosophos** [comment]
See the `--replace` flag (actually, it's `--reuse-name` right now. But it's about to be changed to `--replace`)

**Comment by technosophos** [comment]
The reason, btw, is because a release has a history even after it has been deleted. The plan is to make it possible for operators to (a) retrieve information about deleted releases, and (b) rollback from a delete operation (e.g. recover from accidentally deleted releases).

The `--reuse-name` flag will basically append to the existing history for that release. So you'd be able (in theory) to rollback across re-uses of the name.

**Comment by technosophos** [comment]
Okay, the `--replace` flag change was committed. I'm going to mark this as closed. Feel free to re-open if it's not working for you.

**Comment by sameersbn** [comment]
thanks for the clarification @technosophos
