### ISSUE TITLE
helm package, multiple charts input support.

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1100]
Currently it seems that helm package only accepts one chart directory to package. 

For example, `helm package mariadb mariadb-cluster` only packages the mariadb chart ignoring the other chart.

Allowing multiple charts as input will help in case that the user wants to use bash expansion like `helm package .`

**Comment by migmartri** [comment]
I guess that this use-case is not common and might not make sense in a CI (unless we do batch releases). But it might not hurt to have this capability available in the same way than the linter has it.

I have noticed that repackaging a chart generates a new file, changing the timestamp and invalidating the index. We might want to change the behavior of package to by default skip the package if a tgz file for this release is found, but add a `--force` option that will override.

Having this option, doing something like `helm package .` should not be dangerous.

What do you think @michelleN?

**Comment by technosophos** [comment]
I think that if we do this, we should consistently implement it across the commands that should be able to take multiple charts.

At a glance, I'd say they are:

- package
- create
- fetch

Complicated by how to handle errors:

- lint (good for CI/CD case)
- install (`helm install foo bar baz`)
- delete (`helm delete angry-kitten silly-panda`)

Because of volume of information and predicted use cases, 'helm info' and 'helm get' probably don't need this feature.

For releases, we would have

**Comment by prydonius** [comment]
Agree that we should be consistent here. I think it's okay if `create` only handles a single input, I don't see a batch operation for that command to be helpful, since most of these cases are to do with bash expansion.

r.e. lint, support for multiple charts has already been implemented in https://github.com/kubernetes/helm/pull/922. I'm not sure if the error handling there is robust enough to work for `install` and `delete`?

**Comment by technosophos** [comment]
Okay, `package`, `fetch`, and `delete` are all trivial. I'll do a PR.

For `install`, it's not really a good idea. Too many values and stuff. So I take that one back. ;-)
