### ISSUE TITLE
helm search returns slightly odd results (or at least I can't grok/use them)

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1159]
this is related to #1158. If I install a helm repository and search it I get:
```sh
$ helm repo add fabric8 https://fabric8.io/helm
fabric8 has been added to your repositories
$ helm search chaos
fabric8/chaos-monkey-2.2.233.tgz
fabric8/chaos-monkey-2.2.245.tgz
fabric8/chaos-monkey-2.2.236.tgz
fabric8/chaos-monkey-2.2.238.tgz
fabric8/chaos-monkey-2.2.247.tgz
fabric8/chaos-monkey-2.2.237.tgz
fabric8/chaos-monkey-2.2.240.tgz
fabric8/chaos-monkey-2.2.242.tgz
fabric8/chaos-monkey-2.2.239.tgz
fabric8/chaos-monkey-2.2.243.tgz
fabric8/chaos-monkey-2.2.230.tgz
fabric8/chaos-monkey-2.2.231.tgz
fabric8/chaos-monkey-2.2.234.tgz
fabric8/chaos-monkey-2.2.225.tgz
fabric8/chaos-monkey-2.2.223.tgz
$ helm install fabric8/chaos-monkey-2.2.245.tgz
Error: file "fabric8/chaos-monkey-2.2.245.tgz" not found
```
Whats confusing is its using the chart name, version and adding .tgz to the end yet that file doesn't exist anywhere locally.

Was the intention for the url of the Chart to be used to download this file somewhere internally in ~/.helm/ so that this path could work? Or should we output the URL of the chart instead?

```
$ helm search chaos
fabric8 http://central.maven.org/maven2/io/fabric8/devops/apps/artifactory/2.2.223/artifactory-2.2.223-helm.tar.gz
...
```

Then at least folks could click on the output URLs of the tarballs to download them, then run them using a local folder?

**Comment by michelleN** [comment]
hey @jstrachan !
A chart repository contains an index file (with meta data and location of all charts). When you "add" a repo, we're downloading and caching the index file which should be located at `repo-url.com/index.yaml`. When we `search` for charts, we're doing a regex search on name/keywords in all of the cached index files. 

What `helm install fabric8/chaos-monkey-2.2.245.tgz` should be doing is fetching the chart at the chart url provided in the cached index file of the repo `fabric8`. You can find the cached index files  under `~/.helm/repository/cache/`. We set up the `~/.helm/` directory as part of the `helm init` step.

With that said, here are some questions to help us debug:
1. Does `https://fabric8.io/helm` contain an index.yaml file? I suspect it does because the `repo add` step is not failing. What does it look like?
2. Does that index file point to packaged charts? (with .tgz extension)


Also, automatically adding that .tgz extension is probably not great. We should just leave .tgz off entirely. Thanks for pointing that out. I'll create an issue for that if it doesn't already exist.

**Comment by michelleN** [comment]
Just took a look at `https://fabric8.io/helm` and it's awesome that you have so many charts!

**Comment by michelleN** [comment]
Did you package the charts in this repo with the `helm package [CHART]` command per chance? @jstrachan

**Comment by jstrachan** [comment]
@michelleN no we generated the `index.yaml` by querying all the individual helm charts we've released independently in a CI job. I'm wondering if there's something wrong with the YAML though ;)

Thanks for the explanation! It looks like its downloading the index file fine into ~/.helm - I"m gonna try diagnose why the install doesn't work. It could very well be I've created a bad `index.yaml` ;) though I'd hope if there's something wrong with the YAML we can output a more descriptive error. As right now I get:
```
$ helm install fabric8/chaos-monkey-2.2.238.tgz
Error: file "fabric8/chaos-monkey-2.2.238.tgz" not found
```

**Comment by jstrachan** [comment]
@michelleN aha I figured it out. It looks like the code to download a chart ignores the `url` in the `index.yaml` and instead assumes that the chart lives in the repository at whatever is listed after the 'fabric8/' prefix. 

I've added a minor bit of diagnostics to make it more clear:
```
$ helm install fabric8/chaos-monkey-2.2.238.tgz
Downloading chart from: https://fabric8.io/helm/chaos-monkey-2.2.238.tgz
Error: file "fabric8/chaos-monkey-2.2.238.tgz" not found
```
The thing is in the fabric8 index.yaml the URL to the chart is not `https://fabric8.io/helm/chaos-monkey-2.2.238.tgz` its at `http://central.maven.org/maven2/io/fabric8/devops/apps/chaos-monkey/2.2.238/chaos-monkey-2.2.238-helm.tar.gz`

I should have a PR shortly to fix this...

**Comment by jstrachan** [comment]
I'm gonna mark this one as closed and raised a more descriptive issue: https://github.com/kubernetes/helm/issues/1169 - a PR is on its way shortly
