### ISSUE TITLE
provenance: what is the root? consolidate the index/provenance format?

### ISSUE THREAD

**Issue by philips** [kubernetes/helm#1167]
Reading through the provenance guide I have questions about the design. My questions stem from experience building AppC, OCI, and digging into the evolution of the Docker Image Formats.
## Digest First, Signatures Second

In OCI and the other container image formats we define the object and how it is addressed by digest before discussing signatures. I think it would be helpful if the Helm Chart format did the same. The separation ensures the digest of the item could be used in other signing systems (e.g. TUF) or placed inside of other objects to form a merkle DAG (e.g. [dependencies on other packages](https://github.com/kubernetes/helm/issues/874#issuecomment-245768202)).

Lets run through an example: 
1. Create a chart `helm create mychart`
2. Package a chart `helm package mychart`
3. Take the digest of the chart `shasum -a 256 mychart-0.1.0.tgz` resulting in sha256:6d16658f790909bbeee77802b80b455ed6934a37a564d5ccfb3f69f648a3748c

At this point we have sufficient information to generate a signature file for provenance on this object, the digest. Contained inside of the object should be the digests of all dependent objects, forming a merkle DAG. 

Does it make sense to break the digest creation for a chart file into a separate concept from the provenance file? Having this be a separate concept would also enable things like fully immutable Charts with external dependencies (see https://github.com/kubernetes/helm/issues/874#issuecomment-245768202)
## Internalized Dependent Hashes

Why are the image hashes part of the provenance file instead of being embedded into the Chart? I see the Chart as a Merkle DAG with the following flow:

```
Index <- Chart <- Resource Templates <- Container Images
```

If we embed the container image digests into the templates in the Chart then the Chart is fully immutable and content-addressable even without a provenance signature.
## Provenance File vs Index Format

The next question I had reading about the provenance file is why it is separate or independent from the index file? On first glance I think the index file contains all of the relevant metadata required if we internalize the container image hashes into the package. The only issue is that the checksum field should be improved: https://github.com/kubernetes/helm/issues/1166 
## Move Signatures Into Index?

One useful pattern from the world of container and apt/yum repos I think we should follow is signing of the entire list of versions/packages instead of individual files. In general the index size will be small as it will be small amounts of metadata and digests. And by using the merkle DAG concept we can go from index to trusting everything addressed by digest in the index without additional signatures or metadata files. 

Further I think we should consider borrowing from the container image model of OCI and address all non-index information by digest. This would potentially simplify caching, and fetching and potentially make Charts fit nicely into the existing container image registry ecosystem.

**Comment by technosophos** [comment]
Here's a quick attempt to explain the model that led to the current provenance file format and generation sequence. Much of the history of this may be traced back to the way Debian/Ubuntu/etc. do their package signing. The big outlier, as you know, is that we are stuck relying upon container images as well.

1. Digest is first, signature is second already. The two could be independent... but you don't give a practical example of what that means. (They exist as separate functions, if that's what you mean). I suspect that issue #1166 relates here. The `index.yaml` does indeed have a digest of the file. That code antedates the provenance code and I think needs some updating to be brought into parity -- I see there is an issue for that.

2. Having the images listed in the prov file was requested because it makes it possible to audit the images without decompressing the chart and then rendering the template (remember: an `image:` field in a template may not be a fixed string). This auditability is a desirable feature for enterprises.

The container images actually aren't in the prov file right now, largely because of the difficulty involved in obtaining that information. I would far prefer that developers use the digest of the image instead of a tag in the templates and values files. We just haven't figured out how to enforce that yet.

3. Why a separate prov file? Because those who generate the index file may not be the same people who sign the archive. It's true that the prov data could be added into the index file. I would be fine with that. In that case, we'd simply alter the workflow to have the index generator also import the contents of a `.prov`.

4. Signing the index is an interesting idea, but is not sufficient for what we are trying to accomplish. A signed index indicates that the index was generated by an authority (which is a good assurance). However, a signed chart gives proof of identity for a specific chart. The two are not the same. The entity that generates the index may be distinct from the ones signing the charts in that index. This is more the way Debian (and most other package managers) do this sort of thing. The signature verifies that a person in a position of responsibility audited _a particular package_. A signature on an entire index might be a little overly ambitious, since it would require one signer audit the entire repository.

Also, see https://github.com/kubernetes/charts/issues/23 The Helm Charts team (which works off of that repo) is responsible for defining how their chain of authority will go. As we've discussed in the meetings that led to that document, individual maintainers would sign charts, and the work of signing would be split across multiple maintainers. Essentially, a signature is an LGTM that the file can go into a production repo. Maintainers would then commit their `.prov` files into GitHub, and CI would build packages and relocate the entire thing to the appropriate destination.

**Comment by technosophos** [comment]
This is now partially addressed in the new documentation. I know there are some people working on establishing authority. I'll update here when I see what they figure out.

**Comment by thomastaylor312** [comment]
@technosophos Any updates on this or is this closable?

**Comment by jascott1** [comment]
@philips Im going to close this due to lack of activity but please feel free to re-open if necessary.
