### ISSUE TITLE
helm: verbs install/delete are confusing compared to kubectl

### ISSUE THREAD

**Issue by philips** [kubernetes/helm#1174]
Coming from kubectl I expect `kubectl create` to create things on the cluster and `kubectl delete` to delete things on the cluster.

With helm today things are a bit confusing when I come from that experience. `helm create` creates an empty chart on disk. `helm delete` deletes a chart that we previously installed with `helm install`.

I think there are three ways to fix this:

1. `helm delete` could be renamed to `helm uninstall`
2. `helm create` could be renamed `helm new` or `helm new-chart` then `helm install` could be renamed
3. We move around the help text around to contain different categories

```
Repo Commands
  repo        add, list, or remove chart repositories
  search      search for a keyword in charts
  update      update information on available charts in the chart repositories

Local Commands:
  home        displays the location of HELM_HOME
  serve       start a local http web server
  version     print the client version information

Release Commands:
  delete      given a release name, delete the release from Kubernetes
  get         download a named release
  install     install a chart archive
  list        list releases
  upgrade     upgrade a release
  status      displays the status of the named release
  rollback    roll back a release to the previous version

Cluster Commands:
  init        initialize Helm on both client and server

Chart Commands:
  create      create a new chart with the given name
  inspect     inspect a chart
  fetch       download a chart from a repository and (optionally) unpack it in local directory
  lint        examines a chart for possible issues
  package     package a chart directory into a chart archive
  verify      verify that a chart at the given path has been signed and is valid
```

My personal preference would be to match kubectl habits with 2. But, would love feedback.

**Comment by viglesiasce** [comment]
I tried to map these in the `verb noun` way so that I could get a visual of that. I also created a dev subcommand for some of the one offs but it does not map to `verb noun`. I may have missed some combos in the process but so that we can get an idea:

```console
helm create release CHART_NAME
helm create repo REPO_NAME REPO_URL
helm delete repo REPO_NAME
helm delete release RELEASE_NAME
helm list charts [--repo REPO_NAME] [SUBSTRING]
helm list releases
helm describe release RELEASE_NAME
helm describe repo REPO_NAME
helm dev create-chart PATH_TO_CHART
helm dev serve PATH
helm dev package PATH_TO_CHART
helm dev lint PATH_TO_CHART
helm verify chart URL_FOR_CHART
helm rollback release RELEASE_NAME
helm update release RELEASE_NAME URL_FOR_CHART
helm update repo [REPO_NAME]
```

**Comment by technosophos** [comment]
I have not really seen a tool that uses the `VERB NOUN` combo instead of `NOUN VERB`. Can you point me to an example @viglesiasce ?

For background, here are the cold commands: https://github.com/kubernetes/helm/tree/1.999.0/cmd/helm

You'll notice that we _used_ to do things the way this ticket suggested. But based on feedback, we changed it (viz. `uninstall` is now `delete`, and we bubbled up common commands to follow `helm VERB` instead of `helm NOUN VERB`).

**Comment by philips** [comment]
@technosophos kubectl is verb noun. `kubectl describe service -n kube-system kube-dns`

**Comment by viglesiasce** [comment]
Yeah I think keeping things similar to kubectl makes sense. 

We had really wanted to keep things as close as possible to package managers ({yum,apt} install) but I think that most helm users will have had some experience with kubectl already. Additionally, package managers only really have one noun (packages) which makes them simpler from a ux perspective. The repos are handled by the filesystem (/etc/yum/repos.d/ or /etc/apt/sources/list.d/). We are also baking in the package maintainer tools with helm which is split out [in RPM land](https://apps.fedoraproject.org/packages/fedora-packager), for example.

**Comment by technosophos** [comment]
I think you guys are maybe misunderstanding `kubectl`. There is a distinction between `CMD NOUN VERB` and `CMD VERB ARGV...`.

For the most part, `kubectl` follows two conventions:

```
kubectl VERB ARGS
kubectl NOUN
```

Take @philips's example: `kubectl describe service -n kube-system kube-dn`. In that case `service` is _not_ playing the role of NOUN. It's just an argument in argv.

Same with `kubectl get pods`. `pods` isn't a subcommand, it's an argument. This is like `helm list foo`. `foo` is an argument.

Then there are a few of the `NOUN VERB ARGS` formats, mostly in `kubectl config`:

- kubectl config set
- kubectl config use-context
- ...

And then a few `NOUN` ones:

- kubectl cluster-info
- kubectl api-version
- kubectl logs

I can't actually find any that are of the form `kubectl VERB NOUN`, where NOUN is a fixed word. It's always just an arg.

Again, I'm going to appeal to well-known UNIX programs, which tend to follow the `CMD VERB` or `CMD NOUN VERB` convention. I'd honestly feel much more comfortable going to things like `helm repo-add` than doing `helm add repo`.

Now, to take things another step, what would your help text look like for the `VERB NOUN` format for which you are advocating? How do I find out, for example, what things I can do with Helm repos? To see the relevant commands, I'd have to do `helm add -h && helm index -h && helm list -h && helm remove -h` -- and that's only because I _know_ what the verbs are. This is why things are typically grouped into NOUN subgroups. Think of it from the user's perspective. What does the user want to know? What sorts of things they can delete, or what actions they can do on a release?

**Comment by jayunit100** [comment]
For folks looking for the simplest answer to this , just run `helm list`, find the *name* of your installed chart, and delete it -  `helm delete xyz `
