### ISSUE TITLE
helm repo index reading the directories recursively

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1328]
when we specify a folder to the `helm repo index` command the all the tar files in the subfolders are also read there by corrupting the index.yaml.

**Comment by technosophos** [comment]
It looks like the issue is that we walk the directory recursively, but the URL generator calls `filepath.Split()`, which gives only the basename.

Should we (a) not walk recursively, or (b) generate the correct URL relative to the base, or (c) introduce a `--recursive` flag that defaults to a, but correctly handles b?

**Comment by kmala** [comment]
i like option c as it provides an option for both sets of users who wants use sub-directory to store charts in separate folders(may be one directory for different versions of a specific chart) and those who just wants everything in the current directory and don't want to touch the other directory .

**Comment by kmala** [comment]
I think this is bigger issue that what i initially thought, when using dependencies the charts folder has dependent chart tar files and repo index will add all those dependent charts to the index.yaml

**Comment by technosophos** [comment]
Yeah, it appears that the `helm repo index` command is using the wrong call. I'll have to dig into this more than I thought.

**Comment by technosophos** [comment]
I think I'll fix for (a) and add a new feature request for adding a `--recursive` flag.
