### ISSUE TITLE
bug: `helm delete --purge` is only deleting the last version of a release.

### ISSUE THREAD

**Issue by royjs** [kubernetes/helm#1395]
I noticed a strange behaviour when deleting a release that has been upgraded.

When deleting a release that has prior versions, only the latest version will be marked as deleted. The prior versions will still be in the "SUPERSEDED" state. The problem is that the leftover versions can't be deleted nor replaced. I was only able to fix it by manually deleting the remaining configmaps for the release.

Similarly, a 'helm delete --purge' will only delete the last version, resulting in the same problem.

I'm not sure what would be the best way to handle this but I would expect to be able to re-use a deleted release name even if it was upgraded.

**Comment by technosophos** [comment]
So that issue with `--purge` is _definitely_ a bug. That flag should destroy all of the releases for that given release name.

With the others, `SUPERSEDED` means that the record is no longer authoritative for that release. We don't change those to `DELETED` because that particular record was not the record that was deleted.

I'm going to change the name of the issue so that we remember to fix this.

**Comment by royjs** [comment]
Thank you for the `--purge bug`.

About the `SUPERSEDED`,  I understand that the record is no longer authoritative but I still feel that we should be able to delete or replace it using helm only. Right now in that situation the `delete` command says that the release is not found (since the latest version is DELETED) and a `install --replace` will complain that a release with that name already exists (since not all version are DELETED). It seems weird to me.

I think that a `SUPERSEDED` version should not prevent a `install --replace` to replace a deleted release.
