### ISSUE TITLE
Tiller access control

### ISSUE THREAD

**Issue by aecolley** [kubernetes/helm#1442]
Tiller's gRPC interface needs to be secured against users who are not authorized to launch jobs in its namespace.

I don't see a document setting out the vision for the security model of Tiller. Intuitively, it seems to me that Tiller shouldn't do anything unless the user who runs `helm` has permission to do it. On the other hand, a single authorisation check for users is easier to understand and debug. A more radical option is for tiller to use the helm-user's credentials (perhaps by delegating all apiserver access to helm in the form of kubectl commands).

But let's get rid of those `grpc.WithInsecure` options.

**Comment by technosophos** [comment]
Our plan is to implement security via RBAC, and rely upon Kubernetes' security model.

**Comment by aecolley** [comment]
Using Kubernetes security to secure Tiller will mean a major architectural change. Perhaps Tiller can be made into a backend for the kube-apiserver. Or grpc can develop some native Kubernetes authentication with delegation. Or the user's credentials can be delegated directly to Tiller (I don't like this idea). Or Tiller's use of the Kubernetes API can be indirected through Helm. Whichever option is taken, it will be a serious change. How will it be done? Is it so far in the future that users should seek workarounds before then?

**Comment by technosophos** [comment]
Thanks for expressing your interest. I'll give an answer that's a little more thorough and we can get to some specifics. I'd love some more feedback on this, since basically this is stuff we've tossed around in meetings, but have never written down.

The initial goal was to run all queries from Helm clients through the K8s API server, which handles the authn/authz for us. The RBAC model worked relatively well in that scenario, since it can refuse a tunnel to Tiller for anyone who's unauthorized (and all authn happens automatically).

We've talked for a long time about having the Helm client forward credentials to the Tiller server so that the actual k8s API operations were executed with the client's credentials. But we've not implemented that, having opted to push that work back until after the 2.0.0 release.

Tiller credentials itself through KubeAPI by whatever auth it is currently configured with (in-cluster, that's typically the token). So as it stands, Tiller can be the subject of RBAC rules.

A few people have been using Helm in-cluster (or opened NodePorts to Tiller). This is a case we need to figure out. A NodePort will essentially render Tiller unprotected, and was definitely not our design.

One of our design goals was to not introduce yet another credentialing system. So whatever we decide to do to harden, it will leverage existing Kubernetes auth.

So off the top of my head, we have a few options:

- Hook into gRPC with...
  - SSL/TLS client certs (pain to manage, though)
  - Add an auth overlay to proxy kube credentials in (http://www.grpc.io/docs/guides/auth.html)
- Change the way Tiller interacts with Kube API so that all contact to Tiller _must_ be proxied through the KubeAPI

My preference is to hook into the gRPC auth mechanism, and supply a backend mechanism that would validate the client's kube credentials against k8s API. That gives us an additional advantage: We can get authz based on RBAC, since all of Tiller's calls to create/modify/delete,etc new resources would be credentialed directly against the client's credentials instead of against the Tiller pod's credentials.

Thoughts on that? This is work we could definitely begin for the 2.1.0 cycle.

**Comment by technosophos** [comment]
The main part of this issue is now slated to be addressed in Helm 2.3 or 2.4 (depending on the state of Kubernetes at that time).

**Comment by technosophos** [comment]
Closing this in favor of #1918, which contains a full proposal for this.

**Comment by technosophos** [comment]
Re-opening this to track @fibonacci1729 's progress on enabling TLS for gRPC, which was a separate issue that 1918 did not capture.
