### ISSUE TITLE
Helm choking with third party resources.

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/helm#1468]
Hello! Super excited by this work, and am experimenting with it both in a personal and a professional capacity. However, Helm doesn't seem to be able to deploy third party resources, though `$ kubectl` can. Steps to reproduce are below:

```
$ # This is the only thing in the templates directory
$ cat templates/40-howden-io.certificate.yml 

---
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "howden-io"
  namespace: "howden-io"
spec:
  domain: "howden.io"
  email: "[REMOVED]"
  provider: "route53"
  secretName: "tls-howden-io"

# See
$ ls templates/
40-howden-io.certificate.yml  NOTES.txt

# Helm doesn't seem to like this third party resource
$ helm install . --name=howden-io
Error: release howden-io failed: unable to decode "": no kind "Certificate" is registered for version "stable.k8s.psg.io/v1"

# kubectl handles the certificate OK
$ kubectl apply -f templates/40-howden-io.certificate.yml 
certificate "howden-io" created

# Helm also doesn't like the deletion of the certificate
$ helm delete --purge howden-io
Error: deletion error count 2: no objects visited; unable to decode "": no kind "Certificate" is registered for version "stable.k8s.psg.io/v1"

```

Note: Mildly edited for content, clarity. Versions and things:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
```

The third party resource in question

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  description: A specification of a Let's Encrypt Certificate to manage.
  kind: ThirdPartyResource
  metadata:
    creationTimestamp: [REMOVED]
    name: certificate.stable.k8s.psg.io
    resourceVersion: " [REMOVED]"
    selfLink: /apis/extensions/v1beta1/thirdpartyresources/certificate.stable.k8s.psg.io
    uid: [REMOVED]
  versions:
  - name: v1
kind: List
metadata: {}
```

**Comment by technosophos** [comment]
Related to #1295

**Comment by technosophos** [comment]
@andrewhowdencom is it possible for you to test the fix in #1473? It would require building Tiller from source, and then doing something like this:

Terminal one:

```console
$ bin/tiller
```

Terminal two:

```console
$ export HELM_HOST=localhost:44134
$ helm ls
#... 
$ helm install ...
```

**Comment by andrewhowdencom** [comment]
For sure -- I will hopefully look at this in the next 24 hours or so.

**Comment by technosophos** [comment]
This passed internal testing, so it was merged onto `master`. That means you can test it from the `canary` binary builds @andrewhowdencom

**Comment by andrewhowdencom** [comment]
I was having some trouble trying to build it (: I should more about golang.

**Comment by paultiplady** [comment]
@andrewhowdencom I'm hitting the issue that you saw above, "no kind Certificate is registered..."

How did you get past that one?

**Comment by paultiplady** [comment]
@technosophos this looks like it made it into 2.1.3, should I need to do anything on my end to enable it?

**Comment by andrewhowdencom** [comment]
@paultiplady I haven't had an issue since this was committed. What version of helm / k8s are you using?

**Comment by paultiplady** [comment]
@andrewhowdencom I'm on 2.1.3, which as far as I can tell contains the commit for the fix (https://github.com/kubernetes/helm/pull/1473/commits/f27791c35b465b6e7a31c68fb13c0d31da7d45dd).

I've added Certificates manually for some time now, so the resources are definitely valid.

**Comment by andrewhowdencom** [comment]
What version of k8s?

**Comment by andrewhowdencom** [comment]
Update: I am also now seeing this. 

```
$ helm version
Client: &version.Version{SemVer:"v2.1.2", GitCommit:"58e545f47002e36ca71ac5d1f7a987b56e1937b3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.2", GitCommit:"58e545f47002e36ca71ac5d1f7a987b56e1937b3", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Not sure when it appeared.

**Comment by paultiplady** [comment]
I'm running:

```
$ helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

The commit does appear to be on the `release-2.1` branch though; if you check out the tag 2.1.3 it's in there. (It's also in before the 2.1.2 and 2.1.1 tags as well).

**Comment by paultiplady** [comment]
@technosophos ping on this just in case the notification got lost over the new year break; third party resources seem to be broken still in v2.1.3

**Comment by technosophos** [comment]
Reopening this issue.

**Comment by technosophos** [comment]
Added this to 2.1.4. I'll see if I can track down the issue.

**Comment by technosophos** [comment]
Okay, we _think_ that kubectl 1.5.1 cannot do `kubectl apply` on TPRs. And since Helm 2.1.x internally uses kubectl's `apply` logic, we think Helm upgrades are not functioning for TPRs.

On the missing code -- we actually took that out intentionally on Master, since the kubectl 1.5 library now enables that behavior automatically.

So...

- Helm 2.1 can _install_ TPRs (e.g. the `com.etcd.operator/v1` kind from #1531).
- Helm 2.1 can _install resources_ that use TPRs (e.g. the `Certificate` kind here, or the `EtcdCluster` kind in #1531)
- Helm 2.1 _cannot_ currently upgrade a resource that uses a TPR.
- Kubernetes 1.5's `kubectl apply` also _cannot_ currently upgrade a resource that uses a TPR (though kubectl 1.4 might work).

Does this sound like what you are seeing @paultiplady and @andrewhowdencom ?

**Comment by lachie83** [comment]
This is a kubernetes issue. You cannot use `kubectl apply` on a TPR https://github.com/kubernetes/kubernetes/issues/29542

**Comment by paultiplady** [comment]
@lachie83 given that the linked issue currently appears to have been punted to k8s 1.6, is it worth considering a special-case workaround in Helm until this is fixed? E.g. CoreOS use this cURL method: https://github.com/coreos/etcd-operator/blob/master/README.md#resize-an-etcd-cluster

**Comment by AmandaCameron** [comment]
Just an additional data point, I'm seeing a failure of even **installing** a TPR using helm at the moment, contrary to the above comment by @technosophos -- It's spitting out the same error that a `kubectl apply` would, and I'm getting it from `helm install .`

I'd very much like to see at least installation working, as it's blocking some charts I'd like to write / use for some projects I'm making.

**Comment by technosophos** [comment]
@AmandaCameron can you give any more info about this failure?

I do know of the case where you cannot install a TPR and use one of the TPRs resources in the same chart (without using a hook). For example, if you declare a TPR "example.com/foo" and then try to use a resource with "apiVersion: example.com/foo" in the same chart, you will see an error. The reason for this is that the TPR is not fully installed when the second resource is pushed. The work-around is to send the TPR in a pre-install hook, which causes Helm to wait until the TPR is marked READY before continuing with the installation.

**Comment by AmandaCameron** [comment]
I mean in "consumer" charts. For example, I have a chart that can provision postgres database users/passwords in a legacy system, and I'd like to be able to insert instances of the "PostgresDatabase" TPR that it uses for the creation of this provisioning. This fails because it chokes on the idea of a resource it does not understand. The actual creation of this TPR is handled by the go program that gets run from the first chart. Another example would be provisioning of ACME TLS certs using an already-installed TPR-based controller, such as the kube-cert-manager.'

Appologies for the abiguity in my previous post, I have a hard time turning thoughts into words occasionally.

**Comment by krancour** [comment]
> Just an additional data point, I'm seeing a failure of even installing a TPR using helm at the moment

@technosophos: @arschles, @lachie83, and myself have run into this as well.

To be clear, when we say we're "installing a TPR," we're talking about creating a resource of an existing TPR type.

We've tried with a variety of cluster versions and helm versions. Consistently, I am finding that the problem occurs only with helm 2.1.0+. 2.0.0 - 2.0.2 all worked fine for this purpose.

**Comment by krancour** [comment]
Spent some time troubleshooting with @technosophos. Here are some pieces to the puzzle.

cluster: 1.5.2
kubectl: 1.5.2 
helm: 2.1.3
tiller: 2.1.3

Given the following TPR definition:

```
$ kubectl get thirdpartyresource service-broker.steward.deis.io -n steward -o yaml
apiVersion: extensions/v1beta1
description: A service broker which Steward may use to provision and bind to services
kind: ThirdPartyResource
metadata:
  creationTimestamp: 2017-02-03T20:07:29Z
  labels:
    heritage: steward
  name: service-broker.steward.deis.io
  resourceVersion: "241"
  selfLink: /apis/extensions/v1beta1/thirdpartyresourcesservice-broker.steward.deis.io
  uid: 641c2268-ea4c-11e6-bfcc-08002711dab6
versions:
- name: v1
```

I can try to create a resource of that type. Like this one, for example:

```
kind: ServiceBroker
apiVersion: steward.deis.io/v1
metadata:
  name: s3
  namespace: steward
  labels:
    type: broker
    release: "manageable-butterfly"
    chart: servicebroker-0.1.0
    component: manageable-butterfly-s3-uploader-broker
  annotations:
    "helm.sh/created": "1486154327"
spec:
  url: "http://wrinkled-fish-s3-broker.steward.svc.cluster.local:3000"
  username: username
  password: password
```

If the above is included in a chart, helm will fail to install that chart with an error like the following:

```
Error: release idolized-hydra failed: [unable to decode "": no kind "ServiceBroker" is registered for version "steward.deis.io/v1", unable to decode "": no kind "ServiceBroker" is registered for version "steward.deis.io/v1"]
```

If, however, you take that same manifest and use `kubectl create -f`, it works fine.

Here is one additional datapoint. @technosophos suspects that the problem lies within some validation code, which was altered between Tiller 2.1.3 and master.

With Tiller 2.1.3, a dry-run / debug of a chart including the manifest above succeeds and the manifest is echoed back to me.

After that validation logic moved (e.g. if I try this using the Tiller canary image), dry-run  / debug _fails_ and yields the same error that 2.1.3 could only produce when actually trying to install.

I _think_ this points to @technosophos guess about the error being somewhere in the validation logic being correct.

**Comment by sstarcher** [comment]
This causes a similar issue with helm 2.1.x and Kubernetes 1.4.x.  You can no longer use PetSets if you upgrade helm to 2.1.x

**Comment by technosophos** [comment]
Since there will be no 2.1.4, moving this to 2.2.0

**Comment by technosophos** [comment]
To test this on master:

- Download the canary Helm client: https://github.com/kubernetes/helm/blob/master/docs/install.md#from-canary-builds
- Install the canary version of tiller: `helm init --canary-image`

We've been testing by installing the TPR with `kubectl`, then using a Kind from that TPR in a chart. If you want to store the TPR in the chart, make sure you flag it as a `pre-install` hook so that the API server has time to register it before any associated kinds are used.

**Comment by sstarcher** [comment]
Tested Helm canary against Kubernetes 1.4.8 and I was able to deploy a PetSet.
