### ISSUE TITLE
Helm install should add the LastAppliedConfig annotation during create

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1530]
When helm does an install/upgrade it should add the LastAppliedConfig annotation so that upgrade doesn't fail when something is deleted from the manifest. For more information https://github.com/kubernetes/kubernetes/issues/35134.

**Comment by bgrant0607** [comment]
Specifically:
https://github.com/kubernetes/kubernetes/issues/35134#issuecomment-259878680

**Comment by technosophos** [comment]
@adamreese Is this solved among the Kube 1.5 updates, or are we still using the patch logic?

(Background: Originally Helm used patch instead of apply logic. There's a long historic explanation, but the short version is that we are trying to move to apply. However, that effort got delayed by the internal transition from Kubernetes 1.4 libraries to 1.5)

**Comment by adamreese** [comment]
@kmala I think was fixed, can you check if you are still having the issue on 2.1.0?

**Comment by kmala** [comment]
Tested with hem v2.1.0 and the issue is fixed.
