### ISSUE TITLE
feat: Upgrade command needs --reset-values

### ISSUE THREAD

**Issue by royjs** [kubernetes/helm#1569]
When doing an upgrade command with the --set flag, the provided values are saved in the release.

E.g.
```
REVISION: 5
RELEASED: Fri Nov 18 20:14:51 2016
CHART: test-0.1.0
USER-SUPPLIED VALUES:
replicas: 2
```

The problem is that when you run your next upgrade command, even if the --set flag is not used, the user supplied values will be loaded from the server and be re-used. In the case where no override values are supplied I would expect the default value in the values.yaml file to be used, not the override values from the last upgrade command.

Even more confusing, if you supply a `--set` command with a different override key, then the last value from the server is not used, it replaces it.

Here's step by step example: 

1. in values.yaml we have "replicas=1"
1. we do a `helm upgrade --install` without a `--set`
   * the replicas value used is the default value of 1
1. we do a `helm upgrade` with `--set replicas=2`
   * the replicas value used is 2
1. we do a `helm upgrade` without any --set parameter
   * **the replicas value used is still 2 (notice that we are not using the default value as we would expect)**
1. we do a `helm upgrade` with a different `--set` value like `--set a=b`
   * the replicas value used is 1 (the default value)

**Comment by technosophos** [comment]
We actually went from your expected case to this behavior because of community demand. The rationale behind the move was: If user A does a release, and then leaves and the app breaks, user B needs to be able to re-deploy with the same set of configs (and the minimal amount of work). Going to the defaults would be a confusing experience for user B.

Now, `--set` might be a little confusing, as `--set` is essentially resetting to the defaults, and then overriding (IIRC). Think of it this way: `--set` and `-f` are both considered "the user specified value" and are applied against the chart default values.yaml. There was some debate about what the expected behavior there was. Basically, all solutions confused at least someone.

I'd be happy to see a `--reset-values` or `--default-values` flag on `helm upgrade` that could basically tell Tiller to reset to the default values. That would certainly be easier than the existing workarounds (like supplying a `--set` flag specifically to reset things).

**Comment by royjs** [comment]
Thank you for the detailed answer. I agree that there is pros and cons to both solutions. 
I think that adding a --reset-values flag would make the behavior a little more explicit and less confusing. Maybe the debug output could also make it more obvious what values we are reusing from last deploy.

**Comment by technosophos** [comment]
I updated the title and added this to the triaging queue.
