### ISSUE TITLE
Feature Request: Required properties in Values.yaml

### ISSUE THREAD

**Issue by sputnick** [kubernetes/helm#1580]
In even the simplest Charts you will have a fairly long "values.yaml" file so that users can tune their runtime properties to the fullest. However to correctly deploy an app from a chart you sometimes have to set certain properties. We need a way to define a "Required" key/property in values.yaml. 

This will make it easier to build charts because helm can validate that these properties are set and stop the deployment or warn the user about the missing changes. Today we have to implement the required checks manually with template helpers. 

This feature will also make it easier to deploy Helm charts through UIs because those UIs can prioritise the properties the end user needs to set above a long list of optional ones.

A simple example of a current chart that could benefit from this change is stable/minecraft. There is one property that has to be set so that application works and that's the "EULA" property. If you do not set that to "true" (I agree with the EULA!) then the app will deploy but won't work. The chart maintainer for that had to write template functions to do those checks and write comments for the user using a templated Notes.txt

Perhaps we could get away with something simple like below. The "@required" in the comment above the key would make the following key required to be changed and the string after ":" would be the message that the user gets if he fails to do so? Just an idea - there is probably a YAML friendly way of doing this...

```# Minecraft values.yaml...
minecraftServer:
  # @required: This must be overridden, since we can't accept this for the user.
  eula: "FALSE"
```

Then we could add a helm cli flag i.e. :
```helm inspect values --required chartname```
That filters the required keys and shows that to us. Or without the flag the output would mark the required specifically with a "*" plus show the required comment.

**Comment by technosophos** [comment]
There _may_ be a way to do this with YAML tagging. That would be cool.

**Comment by technosophos** [comment]
## The Idea

Okay, so this was the plan I set out with.

Use YAML tags to mark `values.yaml` fields as optional. In the simplest form, that would look like this:

```yaml
server:
  host: !required.string "localhost"
  port: !required.int 31337 
```

See http://yaml.org/spec/1.2/spec.html#id2782090

With this very basic info, we could unobtrusively "schematize" the file. When other values are overlaid onto the default values.yaml, we would be able to both ensure the presence of required fields and validate their type. Additionally, an agent could read the values.yaml file an prompt users for overrides.

## The Bummer

While I found a few YAML parsers that claim to support tags, they don't actually support _accessing_ the tags (or, really, using anything other than the built-in tags).

- I could not find any YAML stream parsers (e.g. ones that did not try to unmarshal into a data structure for you) that support tags.
- CandiedYAML provides an Unmarshaler interface that looked promising, but it turns out to not correctly overlay tags: https://github.com/cloudfoundry-incubator/candiedyaml/issues/27 Even with that fix, it may not be sufficient for our needs.
- gopkg.in/yaml.2 doesn't expose tags in any meaningful way, though there is a PR to add tag support: https://github.com/go-yaml/yaml/pull/204 I think this could be workable.

I'm going back to the drawing board on this. I was hoping not to have to write a custom parser, and not to have to introduce a new file format. But those are options I may have to revisit.

For now, I'm pulling this out of the 2.2 milestone and putting it back into Triage.

**Comment by errordeveloper** [comment]
I'd suppose we could just define an array of required values in `Chart.yaml`.

Also, may be there is a way to hack around this in `_helpers.tpl`? Basically, I really need this.

**Comment by technosophos** [comment]
What if we added a `require` function in the template so that you could do things like:

```
{{ require "A valid foo is required" .Values.foo }}
```

If `.foo` evaluates to an empty value, bail out of template rendering with the error message.

**Comment by sputnick** [comment]
In the template or Values.yaml?

**Comment by wilkers-steve** [comment]
@sputnick Sounds like it'd be for the templates.  I don't think that's a terrible approach until we can find a better approach aligning with @technosophos's initial vision with parsing yaml files.  This would be a good start, and shouldn't be difficult for 2.3.  I can look into this if you think this is the approach we'd like to take.

**Comment by technosophos** [comment]
@wilkers-steve I'm "assigning" to you.

Option 1: Add it in `engine.go` where functions like `include` get defined

Option 2: If it seems really general purpose, you can contribute it to the upstream Sprig library. I sorta feel like this is special-purpose enough to keep local to Helm.

**Comment by technosophos** [comment]
@sputnick As far as creating a _real_ schema, I'm looking at maybe generating an external schema off of the `values.yaml` file. I'd like to pick a relatively common schema type. Maybe JSONSchema?

This is assuming that the YAML parsers don't get fixed soon.

**Comment by wilkers-steve** [comment]
@technosophos Sounds good.  I started with Option 1 already and agree that it makes sense to keep this local to Helm for now.

**Comment by redbaron** [comment]
just curious, why you suggested for "required" to be late bound as "include" ?

**Comment by DrewEaster** [comment]
Hey @technosophos - was just wondering if you'd had a chance to give some more thought to your initially preferred plan, or something along the lines of schematized values.yaml files. I think this would be a great feature.

The required template function is a great start, but it does have some shortcomings, e.g. where I'm referencing a Value in multiple places. Doesn't feel very DRY to repeat the required function when my expectation would be for the Value to be required wherever it's referenced.

To be fair, one could argue the other way around that it might not always be preferable for a Value to be required by default, as it might be the case that the need for it to be required/optional depends on usage context (i.e. it might be required when used in one template, but not another). So, I guess there's always a place for being able to have some kind of template function for required/optional, even if that's to override some default behaviour in a future schematized values.yaml.

**Comment by ptagr** [comment]
@DrewEaster and for anybody stumbling upon this issue, you could use the `required` function in `_helpers.tpl` to achieve DRY function.

**Comment by anandsinghkunwar** [comment]
@ptagr I was trying to use `required` function in _helper.tpl, do you have an example?

**Comment by rubensayshi** [comment]
@ptagr @anandsinghkunwar it seems `required` always fails in `_helper.tpl` ?
