### ISSUE TITLE
deduplication of chart resources

### ISSUE THREAD

**Issue by khrisrichardson** [kubernetes/helm#1625]
Consider the following hypothetical collection of micro-services...

B and C, which can operate standalone, both have a dependency on E.

```
  B
 / \
D   E
```

```
  C
 / \
E   F
```

When grouped into a larger collection A, the installation fails when E's resources are detected a second time. That's a good way to perform cycle detection, but less than ideal when the presence of said resource by multiple dependents was intentional.

```
    A
   / \
  B   C
 / \ / \
D   E   F
```

One way around this conundrum is to create a directed acyclic graph, where each unique node is only represented once, with the added benefit of topological sorting to install and delete resources in a less than arbitrary manner. What we appear to have instead is a nested list of lists. Thoughts?

**Comment by technosophos** [comment]
Good question. I'm assuming you are asking in relation to charts. One of our earliest design decisions was to disallow diamond dependencies where two charts could have hard dependencies on a third common chart (in short, Helm only allows DAGs). So in the example above, what you would (hypothetically) end up with is

```
     A
   /    \
  B      C
 / \       / \
D  E  E'   F
```

Or, you'd get two `E` chart instances, which often gets expressed as two in-cluster instances of the E chart. E is addressed as A/B/E (or A.B.E), and E' is addressed as A/C/E' (or A.C.E'). Sometimes you want this behavior. Example:

My top-level app (A) depends on a wordpress site (B) which uses MariaDB (E) and a Drupal site (C) which uses MariaDB (E'), but I want each to have its own DB instance. In other words, I don't want a shared DB.

In this case, structuring the chart as above is just fine, since essentially what I want is two instances of the same type of DB.

Sometimes you don't want that. So the solution there is configuration injection.

Unlike programming language package managers (like Glide) where the Diamond Dependency Problem is very deep, for us it boils down to a fairly simple problem: We need a way to tell our services which other services they depend upon. That relationship needn't be expressed by the arbitrary nesting of charts and subcharts. It can be expressed at the configuration layer (e.g. `values.yaml`) or even in service selectors (https://github.com/kubernetes/helm/blob/8660f012a2d673396768cbe2c3df15341306134a/docs/glossary.md#chart-dependency-subcharts).

So what we recommend is organizing the services in a less hierarchical way:

```
    A
   /  |  \
  B   C E
```

And then injecting information about relationships into the B and C charts. The `.Values.global` set of variables is one way of injecting configuration information. "Soft dependencies" (described in the link above) is another. And using Kubernetes' SkyDNS and downward API for autodiscovery is the third. Each of those covers a slightly different use case. But so far we haven't found a problem that breaks down irredeemably into a diamond dependency problem.

Hope that at least starts to answer your question. I've tried to give a simple explanation, but lurking beneath the surface is the fact that there are three relevant abstractions: the templates/values, the generated resource definitions, and the runtime instances. In theory, each of these could suffer from a variety of diamond dependency problem. If there are particulars in regard to any of those, I'd be happy to answer questions and entertain ideas.

**Comment by khrisrichardson** [comment]
@technosophos, thank you for your thoughtful and thorough response. I am indeed speaking in terms of charts, and this does appear to be the dreaded diamond dependency problem.

The workloads I am dealing with use orchestration and service discovery much more extensively than configuration management, so configuration isn't the problem at hand, but rather the objective was to install a complex system in one shot, with Helm serving the role of dependency manager.

I would prefer to represent the workloads hierarchically so that smaller subsystems can be created more rapidly than full blown systems for targeted integration testing, while seamlessly handling the composition of smaller subsystems into larger collections.

I had been dabbling with Project Atomic's atomicapp, in which I had introduced more graph-centric modelling of dependencies, to overcome a similar limitation, but I was wishing to tap into Helm's burgeoning chart repository.

RE: the "soft" dependency suggestion, I think I can coerce build tools with their own deep dependency managers to perform this function, since I was already using such a tool to assemble the charts/ directory in the first place.

Thanks and keep up the great work.

**Comment by khrisrichardson** [comment]
@technosophos thanks again for the suggestion. Flattening the charts and letting the build tool handle the dependency management seems to be working pretty well.
