### ISSUE TITLE
Change `trunc 24` in all base charts

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1637]
Since Kube 1.4, the upper limit for a chart name is now 54 characters instead of 14 or 24.

There are several example charts in the code that use 24 or 14 (e.g. `trunc 14` in the code). Those need to be updated.

**Comment by databus23** [comment]
Wouldn't this potentially break existing deployments that used `trunc 24` for generating all the resource names At least for PVC's this could be catastrophic, no?

**Comment by technosophos** [comment]
This would just be a change to the docs/examples/* charts, which are pretty safe to alter, since they are not production charts, but examples.

**Comment by wilkers-steve** [comment]
Hey everyone :)  Working on a PR for this issue.

The only example chart I see that uses the `trunc 24` is here: docs/examples/nginx/templates/_helpers.tpl 

The other instances of `trunc 24` appear in the following:
pkg/chartutil/create.go 
pkg/lint/rules/testdata/albatross/templates/_helpers.tpl

With the comment made by @databus23 in mind, is it okay to change these instances?  My feeling would be yes, because one instance is in the Go module for packaging the chart, and the other is testdata.  These shouldn't affect the charts that already exist, but wanted to clarify before I submit a PR. :smile: 

Thanks!

**Comment by prydonius** [comment]
@technosophos @wilkers-steve from what I understand the limit is 63 chars (see https://github.com/kubernetes/kubernetes/pull/29523 and https://github.com/kubernetes/helm/issues/1528), or is that info outdated?
