### ISSUE TITLE
Better namespace support

### ISSUE THREAD

**Issue by dzavalkinolx** [kubernetes/helm#1768]
Current namespace support in helm is not a way to go. I should see only charts from current namespace (like I do with `kubectl get xxx` commands) and/or namespace name when I run `helm list`. Currently I see all helm charts installed in this cluster.

**Comment by SuperNami** [comment]
Current way to switch to a different namespace in kubectl is `kubectl config set-context dev --namespace=development --cluster=cluster --user=cluster`

Maybe

`helm config set-context dev`

To switch? Would be nice.

**Comment by mgoodness** [comment]
Duplicate/variation of #1563?

**Comment by technosophos** [comment]
There's a little bit of terminological confusion that might be happening here.

When a Helm chart is installed, it creates a _release_. A release is not bound to a namespace. (That's why a release itself can contain a namespace definition). In fact, it should be possible (though I can't say I've personally tried) to deploy a single chart that creates multiple objects in multiple namespaces.

For that reason, it doesn't necessarily make sense to say that releases should be constrained to "their namespaces", as they are not namespaced objects.

That's also part of the reason why nothing's really been done on #1563. However, that issue does at least give us one way forward: We could apply filters that would only return releases that had objects in a particular namespace.

**Comment by technosophos** [comment]
I am going to close this in favor of #1563, which is on the docket for Helm 2.2.0. After re-reading this and that issue, I think we may try to support a general filter syntax based on metadata like label selectors, name, and namespace.

**Comment by dminkovsky** [comment]
> A release is not bound to a namespace. (That's why a release itself can contain a namespace definition). In fact, it should be possible (though I can't say I've personally tried) to deploy a single chart that creates multiple objects in multiple namespaces.

I am struggling to understand exactly this. I've looked at the documentation and I've looked at several issues here on GH and I am still confused: 

* On one hand, I can use `helm install --namespace` to specify the namespace I'd like to target
* On the other hand, my chart can specify whatever namespaces it wants inside its metadata objects for every resource it creates.

So, my questions: 

* If the namespace specified by `helm install --namespace` does not exist, does Helm create it?
* If a resource template specifies a namespace in its metadata, does helm overwrite it?
