### ISSUE TITLE
Feature request: Add ability to specify kubernetes label in the command line

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/helm#1800]
When Operator launches multiple objects, which belongs to the same service,  it would be great to be able to assign them a common kubernetes label from helm cli. 
Example  helm install --label label_name:label_value. 
When specified, it should add to the rendered template, 
metadata:
  labels:
    label_name: label_value
This is the most common way for operators to get info for its objects without going through extensive search.

**Comment by kfox1111** [comment]
Also it would be nice to be able to query releases based on labels attached at release time.

**Comment by intlabs** [comment]
@sbezverk, @kfox1111: to help explain this concept could you describe how it would be different to implementing something like this: https://github.com/technosophos/common-chart/blob/master/common/templates/_common.tpl#L25-L30 in a chart.

**Comment by sbezverk** [comment]
The major difference with already implemented labels is that they are unique per release. You install chart for PV, PVC, SVC each will have unique release label. My goal is to have COMMON label assigned to ALL type of objects created by a specific operator (operator being a piece of code, not confuse with human ;-) ). This way the operator can easily group then with a single search for a specific uniqu to this group of objects label. Let me know if it is more clear the goal I try to achive.

**Comment by technosophos** [comment]
For a long time we resisted doing anything like this simply because we felt like it would add an additional processing step (post-template, but pre-install). That's the same reason Helm doesn't ever set any of its own labels. WE've basically held the line telling people that if they wanted to do labels like that, they could do this in the chart, and use --set.

But... I can actually see the use case for something like this (especially since it would not be the chart developer's job to expose the functionality). I think this could be useful.

@kfox1111 on querying by label, I think we'd like to be able to support that. @adamreese and I talked about it this morning in relation to #1563, which would be better implemented with a generic query mechanism.

**Comment by technosophos** [comment]
Okay, I'm closing this in favor of #1950 simply because that one is closer to the top of the queue and is thus more likely to get done. ;-)

There are a few open questions on that one that we need to figure out in order to implement this feature, but I think it is possible.
