### ISSUE TITLE
Feature Request: Create #openstack-helm Slack Channel on kubernetes.slack.com

### ISSUE THREAD

**Issue by alanmeadows** [kubernetes/helm#1877]
What

The kubernetes organization on slack should have an #openstack-helm channel.

Why

There is a growing community of those trying to orchestrate OpenStack using helm.  It would help community exchange and collaboration to have a place for that group as a wider community to speak about issues specifically facing OpenStack orchestration using helm.

Issues then requiring helm specific improvements can be brought to #helm, but many issues can be worked through with by discussing Kubernetes primitives and best practice approaches in combination with OpenStack development, deployment, and operations experience that may best operate in its own channel.

User Experience

Helm chart owners of OpenStack need to interact with end users who are using the charts and requiring complex real world configurations not yet cared for.  The dialog will help build a Kubernetes native way using best practices for both Kubernetes and Helm.  The end result is a benefit to the Kubernetes community in general--clear examples that can be pointed to of how to successfully orchestrate and manage the life-cycle of a very large and interconnected application inside Kubernetes.

@sarahnovotny any wisdom appreciated.

**Comment by v1k0d3n** [comment]
@lachie83 maybe you could weigh in on this? your thoughts?

**Comment by technosophos** [comment]
I'd be strongly in favor of this. The OpenStack + Kubernetes + Helm discussions have really taken on a life of their own. Often, the conversations are very domain specific ("here's a very advanced case, how can we take the collective toolset and solve it").

Does anyone know who the gatekeeper is on the Kubernetes Slack? I don't have permissions to create new channels.

**Comment by sarahnovotny** [comment]
the helm to deploy openstack use seems to fit in two sigs already... sig-apps and sig-openstack.  we're trying to right size our conversation sharding as much as possible.    why do you want another #channel ?

**Comment by v1k0d3n** [comment]
i think this is a great/fair question. i think sig-openstack today was intended for kubernetes workloads on openstack, because at the time...that was the real challenge for openstack users. i'm thinking about the early days of ingress, lbaas issues with kubernetes, magnum CaaS, etc. if that group is willing to evolve into _anything_openstack...i'm all for it. i will continue to work with the openstack community (interop - @hogepodge) to see if this really makes the most sense.

sig-apps is also another good suggestion, and this is definitely where i think openstack needs to eventually go. meaning, that openstack is a very complex set of applications and there are some openstack specific oddities. imagine if gce or aws were community projects (complicated). it was always intended to _be_ the infrastructure, and even though it too is a collection of applications, they are tightly bound and not easy to containerize, let alone orchestrate in this new container reality. because of this, i think that openstack users tend to gravitate towards _openstack_ SIG's and channels dedicated to general openstack discussions. this is something that i think we need to break down over time though, and i see kubernetes helping with this naturally. they are forced to join other communities, and this is a great thing!

trust me, i don't like being in limbo (or seeming like an odd duck in a new world). we want to break down this "openstack" echo chamber, and take things one step at a time. this project is only using kuberrnetes and helm natives, and dedicated to applying resources to kubernetes and helm to solve issues (rather than solving issues _just_ within openstack, as users are typically used to). the hope  is that this strengthens both communities, and open source IaaS. because...(at least for openstack users) they're a whole lot better together.

**Comment by sarahnovotny** [comment]
thanks for the info.  I've created #openstack-helm.

**Comment by xsgordon** [comment]
Just for future time travelers the scope of sig-openstack is "a special interest group co-ordinating contributions of OpenStack-related changes to Kubernetes." [1]. Whether those are workload or deployment focused depends on what issues folks have and who shows up to work on them. The right place to propose expansion of scope is the mailing list [2].

[1] https://github.com/kubernetes/community/tree/master/sig-openstack
[2] https://groups.google.com/forum/#!forum/kubernetes-sig-openstack
