### ISSUE TITLE
Proposal: support local path in requirements.yaml

### ISSUE THREAD

**Issue by qwangrepos** [kubernetes/helm#1884]
## Problem Statement
Currently Helm only support fetching dependency charts in requirements.yaml from a helm repository, which can be run locally or remotely. This limitation requires chart developers serving a helm repository and pushing the dependency charts to the repository and fetching the dependency charts into the charts/ folder. This is a pain point for chart developers in the CI process.

## Use Cases
For a chart developer, the dependency charts can be pointed to a local file system in requirements.yaml. A dependency chart can be operated directly in the file system without serving a local or remote helm repository.

## Specifications
requirements.yaml:
```
dependencies:
- name: mariadb
  version: 0.5.x
  repository: file://a/local/path
```

Behaviors for the following commands will be changed.
`helm dependency update`
If a dependency chart is specified to be accessed through files in a local path in requirements.yaml, the chart in the local path will be copied into ./charts folder, and requirements.lock file will not be generated. 

`helm dependency build`
If a dependency chart is specified to be accessed through files a local path in requirements.yaml,  requirements.lock must be absent. Otherwise, it will throw an error for requirements.yaml and requirements.lock are not synchronized. 
Otherwise, the behavior will mirror helm dependency update.

`helm dependency list`
This command will behave the same except that the repository will start with "file://" indicating the chart is located in the local file system.

This proposal is trying to resolve #1733 and a part of #1834.
Please comment for any thoughts and ideas.

**Comment by kfox1111** [comment]
Looks really good, but needs a bit of clarification.

file:// vs file:/// meaning. file:// is the root dir of the local fs where Charts.yaml is stored?, while file:/// would search from the root of the fs? Would disallowing file:/// be good? (I think?)

'../' in the file:// needs to be explicitly allowed. so, file://../../foo should look two directories up from this chart for a chart dir named foo.

I also propose version should be optional in this proposal when type is "file://". As the only options are, they will match and it will work, or they will not match and it will be broken. Its just more work for the operators then to maintain.

**Comment by jascott1** [comment]
On the optional version idea, i'm not so sure. We could match the requirements entry's version to the one in the local dir. Sure its a pain but at least it forces consistency, otherwise it would be easy to drift far away from reality thinking you have version 1.12 (as listed in requirements) but are in fact dealing with 1.13 with all the breaking changes. Not a huge deal to me but with many many charts it could be a needle/haystack affair. We could at least detect and warn?

**Comment by kfox1111** [comment]
If its optional, if you want the consistency check, you just add the version. if you don't want to version them separately, you skip adding the version to the parents deps. It handles both use cases I think?

I just don't think that if you have a single git repo, with two packages, A and B, you will hit a case very often where you update A to an incompatible version from what B expects. They are in the same repo and developed/tested together.

**Comment by technosophos** [comment]
We would pretty much have to follow the spec for how `file:` URIs are treated. See https://en.wikipedia.org/wiki/File_URI_scheme (which links to the RFCs)

**Comment by technosophos** [comment]
I would not be in favor of dropping the `version:` requirement. But this is a case where using version matching (instead of exact versions) would be preferable.

In fact, I would be in favor of version constraint checking for any charts included by `file:///`. This is actually a good feature to have for those who are using multiple VCS repos, as it will provide a way of flagging when a user's local environment differs from the expected.

**Comment by technosophos** [comment]
I believe that @qwangrepos is currently working on a PR to add this feature. I've added it to the 2.2.0 roadmap.

**Comment by kfox1111** [comment]
@technosophos yeah, I'd be ok with version matching instead of exact, so you could at least say, version >= 1.x, version <= 2.x. Wouldn't be a huge burden then.
