### ISSUE TITLE
Helm fails when podsecuritypolicy is on

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/helm#1951]
I was doing some testing of Helm under OpenShift and Kube with pod security policy to flush out any assumptions that don't make sense in a multi-tenant environment.  One of the first ones I hit was that it looks like the helm assumes that it can run containers as root on the cluster:

```
$ helm install stable/redis
Error: release eager-jackal failed: error validating "": error validating data: mkdir /.kube: permission denied
```

A restrictive pod security policy (that doesn't allow running as root) will catch this - since I assume tiller doesn't actually need root in the pods it sets up, it might be good to craft the tiller image so that it doesn't assume it is running as UID 0 in the image.  Since tiller will have access to high level credentials, it's also somewhat dangerous that the tiller image expands the code inside its own container (any escape from the template environment will root the cluster).

**Comment by technosophos** [comment]
Bumped this to the next patch release.

**Comment by bacongobbler** [comment]
@smarterclayton can you elaborate more on his pod security policy? How is tiller running as non-root in your cluster? I'm curious to see how one could reproduce this issue so we can test against it.

My assumption is that the `mkdir /.kube` error stems from the kubernetes codebase, where if $HOME is not set then the schema is written to the root filesystem. I'd try setting $HOME to `/tmp` and see if that fixes things.

**Comment by smarterclayton** [comment]
PodSecurityPolicy is a Kube beta API that prevents users from running operations that allow container escape unless they have a certain level of privileges.  By default, OpenShift runs with this on (no user is allowed to run as root, access the host filesystem, access the host network, etc).  I'll send you a yaml dump later, but effectively the PodSecurityContext field is set with a high non-root user (the most restrictive and safest mode) which at some point might be come the (or a) default setup for Kube.  

/tmp should be writable as any user, but / would not be.  I will try your change out tonight.

**Comment by smarterclayton** [comment]
Yes, setting HOME fixed that particular issue.

**Comment by bacongobbler** [comment]
For the reason why this is failing, I'm fairly certain it's because tiller uses k8s `pkg/client/api/validation` to validate the schema. Because the schema does not exist initially, pkg/client writes it to `$HOME/.kube/schema` so that a user of pkg/client (in this case, tiller. Usually kubectl) can validate data client-side before uploading it to the server. When it writes it to disk, $HOME is not set when running as a non-root user according to the pod security policy, so it writes to `/` instead, causing the failure. Hardcoding an ENV entry for HOME makes it apply globally to the container, no matter what user spawns the container which is why changing it to /tmp works here.

Related upstream issue: https://github.com/kubernetes/kubernetes/issues/23973
