### ISSUE TITLE
RFC: add an option to export values from a chart

### ISSUE THREAD

**Issue by redbaron** [kubernetes/helm#1965]
# Summary
I propose to add `exports.yaml` which is templated, available to the rest of templates and accessible from parent charts.

# Motivation
Currently when chart `A` depends on `B` it includes it as a subchart and then uses resources provided by `B`. Current way for `A` to address resources created by `B` is for both of them follow same convention in naming. This limits the way how services from multiple authors can be composed. It is also very fragile and easy to make errors, given that multiple instances of a service can be created in a Release.

Example of such an error is Sensu from `kubernetes/charts/stable`:

It references redis service using a convention `{{Release.Name}}-redis` [1]:
```
{{- define "redis.fullname" -}}
{{- printf "%s-%s" .Release.Name "redis" | trunc 24 -}}
{{- end -}}
```

But redis subchart defines it as overridable way[2]:
```
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}
{{- end -}}
```

so if some chart pulls in both `sensu`  (and implicitly `redis`) and explicitly `redis`, then it might decide to change `overrideName` of  `.sensu.redis` which will make `sensu` to use wrong redis for it's data. This error wont manifest itself until somebody checks actual dataflows or decides to put down "wrong" redis for maintenance.

# Detailed design
Helm can add new concept of "exported vars".  Possible implementation might be:
 1. every chart can have a special file `exports.yaml`
 2. `exports.yaml` is templated in the same way as files in `templates`, but *before* them
 3. once templated, `exports.yaml` is then loaded as YAML file similarly to how `values.yaml` is loaded
 4. values loaded form `export.yaml` are accessible for rest of templates in a chart as a `{{.Exports.XXX}}`
 5. parent charts accesses subchart  exports as `{{.Exports.<chart name>.XXX}}` in both parent's `exports.yaml` and `templates`
 6. `exports.yaml` cannot have keys which match any subchart name.

## Example
This way, in case of sensu and redis, with sensu and redis might look like:
 1. `redis` chart defines `exports.yaml` as:
 ```
ServiceName: {{Release.Name}}-{{.Values.nameOverride | default .Chart.Name }}
 ```
 2. `redis/svc.yaml` uses `{{.Exports.ServiceName}}`  as a service name chart creates
 3. when `sensu` chart configures connection to redis it uses `{{.Exports.redis.ServiceName}}`

# Alternatives
Introducing additional special file is fully backward compatible and path of a least surprises overall. 

## Pumped .Values
There is an alternative to introducing `exports.yaml`, which is to upgrade  `.Values` in a following way:
 1. (if it is not done already) make `.Values` accessible across charts, so that parent chart can access values of a ` redis` subchart using `.Values.redis.VarName`
 2. Enable "calculated" fields in `values.yaml`. It  seems that  YAML spec [3] allows custom processing of tagged fields, so `values.yaml` of  a redis chart from example above might look like:
 ```yaml
 ---
 Port: 9999
 Memory: "512M"
 ServiceName: !!eval "{{ .Release.Name }}-{{ .Values.overrideName | default "redis"}}"
 ```
 
`values.yaml` is loaded then as following:
 1.  load file skipping any calculate fields
 2. populate context with standard builtin vars such as `.Release` or `.Chart`
 3. load file again, but evaluate calculated fields as a template using context from `2`.  Interpret templating result as YAML and assign value to computed var

I don't see any major disadvantage  of "pumped" `values.yaml` in favor of `exports.yaml` , but it seems inferior due to "unnatural" look of it from user point of view and possible unnecessary complicated implementation.

# Unresolved questions

Due to possible conflict in names, values in `exports.yaml` can not have keys which match subchart names,because same `{{.Export}}` object is proposed to be used for both chart's own exports and access to subcharts' exports.  

Due to it's nature values in `exports.yaml` form a contract which other charts expect from it and therefore key names shouldn't be changing. List of subcharts  is not stable over time though, therefore should a new subchart be introduced which happen to match existing key, that key would need to be renamed therefore making it a breaking change for a chart.

So it is possible that chart's own exports and subchart's export should be separated.

[1] https://github.com/kubernetes/charts/blob/0c62b3e5adccccfb2dd378a4ae718a99564b4056/stable/sensu/templates/_helpers.tpl#L14-Lundefined
[2] https://github.com/kubernetes/charts/blob/0c62b3e5adccccfb2dd378a4ae718a99564b4056/stable/redis/templates/_helpers.tpl#L13-L16
[3] http://yaml.org/spec/1.2/spec.html#! tag indicator/! local tag/

**Comment by jascott1** [comment]
Why not just use existing child values.yaml and allow parent to access that? This is being discussed here https://github.com/kubernetes/helm/issues/1883

**Comment by redbaron** [comment]
Correct me if I a wrong, but child `values.yaml` is not templated, therefore they can not have things like `{{ Release.Name}}` in  there

**Comment by jascott1** [comment]
No values file is templated and that idea has been shot down repeatedly. Imo the exports file seems like heavy lifting for this but perhaps I am missing something.

**Comment by redbaron** [comment]
I can't see that `values.yaml` is templated:

my `values.yaml`
```
MyVar: "{{.Release.Name}}"
```

my `templates/cm.yaml`
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
data:
  myvar: {{ .Values.MyVar }}
```

Running helm 2.2.0:  `helm install --dry-run .`

expected result:
```
# Source: mychart/templates/cm.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
data:
  myvar: random-release
```

Actual result:
```
---
# Source: mychart/templates/cm.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
data:
  myvar: {{.Release.Name}}
```

**Comment by jascott1** [comment]
So sorry, bad grammar on my part. Should have written "none of the values.yaml files are templated"

**Comment by technosophos** [comment]
Phew... lots to digest here.

Generic stuff:

- We might have figured out a way to support rendering templates in values files: https://github.com/kubernetes/helm/issues/1978 @jascott1 
- Unfortunately, none of the YAML parser

**Comment by technosophos** [comment]
@kfox1111 Have you looked at this issue? I'd be curious to hear your opinion.

**Comment by kfox1111** [comment]
yeah, seems similar to the other issue. allowing values to be templated and imported into the parent is interesting. Though I think that may be a more general case of allowing values to itself be templated. Which I do think would be useful but might be a separate thing? Should we consider those two use cases separately in two different issues?

**Comment by redbaron** [comment]
What I don't like about pumped values, as it turns one-directional channel into bi-directional, we use same method to pass config downstream AND to lift final values from them, which is not very easy to model and will have confusing ordering issues

**Comment by redbaron** [comment]
@technosophos ,

>  The export idea makes it a little safer, but it could still be the case that if I updated a subchart, it could alter a value in my parent chart without that being my intent, and this could occur on accident.

 1. it is already the case,but worse: both charts need to follow convention to be able to coexist. 
 2. changing values is not a prolem with `exports.yaml`, in fact it is exactly the reason I am proposing them: even if value changes, parent chart always use the right value,not just silently breaks

**Comment by kfox1111** [comment]
So, one of the use cases seems to be passing templated values from the child to the parent?

That can be solved today by calling a macro defined in the child and called from the parent. We use this pattern in kolla-kubernetes.

Is that functionality enough to skip implementing it here? Are there other use case for it?

How does this interact with child macro's? Can you call a child's macro's (or a child's child's macros) in the child's exports? I could see that being useful, if macro's are useful in exports.

**Comment by technosophos** [comment]
I'm looking at whether we can add a template function that would pass a string through the current instance of the template engine.  #1978 Does that get close to addressing some of the desires here to embed a template in a value?

It would allow you to do this:

```yaml
myval: '{{ .Release.Name }}-foo'
```

And then render the template inside of another template like this:

```
{{ $calculatedValue := tpl .Value.myval . }} 
```

Which would set `$calculatedValue` to something like `happy-lemur-foo`.

**Comment by redbaron** [comment]
> That can be solved today by calling a macro defined in the child and called from the parent. We use this pattern in kolla-kubernetes.

Calling macro which both parties agree on is just another form of sharing by convention, same as "lets name all our services `{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}` so that we can 'see' them from each other", but "lets use this macro name to name our services". If everybody follows pattern, it the time for a tool to embed it and provide facilities so that it just works.

Having `exports.yaml` draws a boundary what chart "offers" to a world and makes it in unambiguous and explicit way. There multiple examples of it elsewhere, for example in programming world that is public methods, in infrastructure management tools such as CloudFormation or Terraform that is "outputs" (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html and https://www.terraform.io/intro/getting-started/outputs.html)

If you have a code reuse there is always a need for a way to share information.

**Comment by redbaron** [comment]
@technosophos embeddable templates help to solve certain problems, but it has nothing to do with passing state information from one chart to another.

I think best way forward is to implement a PR for your consideration so that it will be something more tangible that just ideas, I'll try to do it this week

**Comment by technosophos** [comment]
There are two features suggested here:

1. Make it possible to export a variable from a subchart to a parent chart
2. Make it possible to template values

Let's treat them as separate problems for a moment.

Regarding (1): I don't have a problem with a _parent chart_ asking to access the values of a _subchart_. But I do not want a system that automatically injects subchart variables to the top level. It creates an environment that is very difficult to debug and it makes the scoping rules really hard to understand. (Imagine a programming language where all of the variables inside of one function were automatically hoisted into the body of the parent function. That would be very confusing.)

Regarding (2): It seems to me that we have four options:

- A. Allow template rendering inside of a template (#1978)
- B. Provide a file of values that are pre-processed and then coalesced into the values (this suggestion)
- C. Run the coalesced values through a template engine before making them available inside of the regular templates.
- D. Use an environment variable substitution system instead of a full template engine

Regarding (A), you have told me it doesn't meet your desired use case. To its credit, the scoping rules are relatively straightforward: It executes with access to all of the normal templates, variables, and macros that are in-scope for the template that calls it. It breaks backward compatibility in that charts that use it can't be installed with older versions of Helm. And it leaves it up to the original template author as to when a value may or may not contain a template.

Regarding (B), it will break backward compatibility in a moderate way. It will introduce some pretty substantial new scoping rules, and will switch us to a two-cycle template rendering process. We would need to change the coalescing rules (how values.yaml, `-f`, and `--set` are merged), and we will run into the difficult case where values that the user specifies can get silently overwritten to something else (and they will have no way to fix that).

Regarding (C), it will break backward compatibility in a big way, will require a unique set of template rules (e.g. one-line templates only), will require that templates be parsable as YAML (a huge problem), will make it very difficult to coalesce values, and will require _at least_ a two step rendering (possibly a three-step rendering).

Both (B) and (C) also suffer from a cognitive overhead problem: We have to come up with a way to educate users about why only certain variables, certain templates, and certain macros are available to them in one template file, while a different set of things are available in another context.

Regarding (D), we could support simple variable expansion:

```yaml
myReleaseName: ${RELEASE_NAME}-${CHART_NAME}-foo
```

The (D) solution is the easiest. This particular implementation will break backward compatibility in a very small way (charts that use this can't be installed with old versions of Helm), but is otherwise relatively safe. It does not introduce any of the scoping problems that B and C have, and it occurs as a pre-pass before templating. Its capabilities are nowhere near as sophisticated, but that is a good thing IMO. I still think it is confusing, but it's far less confusing than any of the other relevant options.

Okay, and the last thing is whether (1) and (2) MUST be solved together. I don't understand why they must. It seems to me they are two very different problems, and can be solved in isolation.

**Comment by jascott1** [comment]
We went with the non-templated 'import child values via requirements.yaml' approach. Should we close or alter this proposal to reflect that and concentrate on the templating values aspect?

**Comment by bluecamel** [comment]
How is this supposed to work when including charts directly instead of requirements.yaml?
