### ISSUE TITLE
could the `helm` binary be made available as a standalone download?

### ISSUE THREAD

**Issue by iameli** [kubernetes/helm#1981]
I find myself downloading tools in the kubernetes universe a *lot*. I help people set up kube stuff, and I also put them in a lot of Docker containers for build processes.

kubectl is the best:
```
curl -O https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/linux/amd64/kubectl
```

minikube is not so bad, there's a redirect in there so you need `-L`...
```
curl -L -o minikube https://github.com/kubernetes/minikube/releases/download/v0.16.0/minikube-linux-amd64
```

helm... not so fun.
```
curl https://kubernetes-helm.storage.googleapis.com/helm-v2.2.0-linux-amd64.tar.gz | tar xvz --strip-components=1 linux-amd64/helm
```

Always takes me twice as long to put together that command in my head. Any chance we could follow the `kubectl` trend and just put the binary online? I'd do the legwork, but it seems like mostly adding stuff to the Google bucket that I don't have access to.

**Comment by technosophos** [comment]
Adding to the meta issue about reworking our build/package system. #1968 

We were under the impression that it was required to distribute the Apache license with the binary. If anyone knows the "official" stance on that for CNCF, can you comment here?

The relevant portion of the Makefile is this target: https://github.com/kubernetes/helm/blob/master/Makefile#L35

**Comment by bacongobbler** [comment]
I'd say that including the README and the license agreement in the packaged release packages are intentional. From my point of view, it's [part of the legal requirements](https://github.com/kubernetes/helm/blob/master/LICENSE#L90-L96) for distributing software under the Apache v2 license, so we should not be distributing the software without the license.

Does that make sense?
