### ISSUE TITLE
How to upgrade from a helm-less system to a helm controlled system

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/helm#1999]
Hi Helm experts,
We're running a system which is using Ansible to do Kubernetes resource deployment, and we want to run an upgrade to change the Kubernetes resources deployment to be under helm's control .
Is there some introduction for how to upgrade a helm-less system to a helm controlled system?

I found I can add the manifest of the existing resource to the chart, and run "helm upgrade" twice to add the existing Kubernetes resource to be managed by helm:
1. The first time to run "helm upgrade", helm reports "Error: UPGRADE FAILED: no resource with the name nginx-added found".
Although “helm upgrade” is failed, the new release data is saved into helm storage:
tiller log:
2017/02/13 13:58:16 release_server.go:303: warning: Release Upgrade "tonyaw-rl" failed: no resource with the name nginx-added found
2017/02/13 13:58:16 storage.go:53: Updating "tonyaw-rl" (v3) in storage
2017/02/13 13:58:16 storage.go:45: Create release "tonyaw-rl" (v4) in storage

2. After that, "helm get" fails:
[root@host01 helm]# helm get tonyaw-rl
Error: release: not found

3. When I run "helm upgrade" again, the upgrade is successful. The manifest of existing k8s resource is added to release, and "REVISION" is increased.
[root@host01 helm]# helm list
NAME            REVISION        UPDATED                         STATUS          CHART
tonyaw-rl       5               Mon Feb 13 21:58:38 2017        DEPLOYED        upgrade-test-0.1.0

Is this behavior expected? Can I use it as an official solution to upgrade from a helm-less system to a helm controlled system?

Thanks in advance,
Tony

**Comment by technosophos** [comment]
I believe AppsCode released a tool that helps with exporting existing manifests to Helm charts: https://github.com/appscode/chartify /cc @TamalSaha 

What you are seeing is basically the expected outcome. The first run, the upgrade has no record of the objects, so it fails to install them. The second time, it has a record that you tried to install those objects, so it attempts to upgrade the existing ones.

Doing things this way will _work_, but is a little dangerous. If you use PVCs, it _could_ result in losing data on those if they get deleted.

**Comment by tonyaw** [comment]
Matt,
Thanks for your response very much.
I will study your info, and will consult you again with further questions. :-)

Thanks,
Tony

**Comment by bacongobbler** [comment]
closing this as inactive/resolved via chartify. If that doesn't fix the issue there's an ongoing proposal at https://github.com/kubernetes/helm/issues/2730 which I would suggest taking a look at if you're interested :)

Thanks!

**Comment by dbendelman** [comment]
@technosophos @bacongobbler is there any discussion about creating an official way for Helm to import existing Kubernetes resources?

Terraform, for example, has the [`terraform import`](https://www.terraform.io/docs/import/usage.html) feature, which I use heavily any time I'm terraforming existing infrastructure. I sorely miss this functionality in Helm, and it's often a barrier to Helm adoption in some of the vanilla Kubernetes environments I work with.

The ideal workflow I'm thinking of would go like this:

1. Create a new Helm chart containing my desired resources, some or all of which already exist in my cluster.
2. Run `helm install ./mychart --import --name my-release -f values.yaml --set my.var=abc`. Notice the `--import` in there. This could also be a new `helm import` command instead, which communicates intent a bit better.
3. Helm behaves exactly as if I ran a normal `helm install`, but instead of assuming it needs to create every resource, it first checks if each resource exists and if it does, takes ownership of it.

It may choose to also update existing resources with new labels, but for safety this command will fail if it sees that an imported resource is different than what the chart+variables define.

Thoughts?

**Comment by bacongobbler** [comment]
You're probably looking for #2730 as the discussion topic on creating a Helm plugin to adopt existing resources into a chart. You can also look into the [Kubernetes VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) which allows you to convert an existing resource or manifest into a Helm template using the `Helm: Convert to Template` option in the palette window.

Screenshot of that in action:

![k8s vscode extension](https://user-images.githubusercontent.com/1360539/52764919-cff5a580-2fd6-11e9-9b91-d017e7002da7.png)

**Comment by dbendelman** [comment]
#2730 is spot on, thanks @bacongobbler!

RE the VSCode extension, it sounds like it helps with auto-generating a chart from existing resources. This is less interesting to me, as what I need in my use case is to generate a Helm _release_ from existing resources.

**Comment by ocofaigh** [comment]
@dbendelman Did you ever find a solutuon that worked to generate a Helm release from existing resources? 
I tried the approach in the description of this issue, but it didnt work for me. Here is what I got:
1. With resources already existing on kubernetes, I ran a helm upgrade. It failed with:
```
UPGRADE FAILED
Error: "APP" has no deployed releases
Error: UPGRADE FAILED: "APP" has no deployed releases
```
2. I ran the helm upgrade again. It failed with same error:
```
UPGRADE FAILED
Error: "APP" has no deployed releases
Error: UPGRADE FAILED: "APP" has no deployed releases
```

I then tried using `helm upgrade --install` instead of just `helm upgrade`, and I got this:
1. First attempt, helm tries to do an install, but fails:
```
Release "APP" does not exist. Installing it now.
Error: release APP failed: services "APP" already exists
```
2. Seconds attempt, helm tries to do an upgrade, but it fails :
```
UPGRADE FAILED
Error: "APP" has no deployed releases
Error: UPGRADE FAILED: "APP" has no deployed releases
```
