### ISSUE TITLE
A question about naming rule

### ISSUE THREAD

**Issue by kdada** [kubernetes/helm#2022]
In kubernetes, an object name should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and . .
refer to :
[kubernetes doc](https://kubernetes.io/docs/user-guide/identifiers/)
[kubernetes design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/identifiers.md)

In helm, there is a regexp of release name:
```
^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$
```
And I can't find any limitation about chart name ( or I missed something? ).

In common case, we'll use the template for name:
```
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
```

When we used any capital letter in release name or chart name, the chart will generate wrong kubernetes resources and kubernetes will reject these resources.

Will helm add some limitations about release and chart name?

**Comment by technosophos** [comment]
I don't think we will change the current requirements for chart name or for release name. Neither field is necessarily "guaranteed" to make a safe `name:` field. Convention has opted to use those values in those fields, and the template language is expressive enough to protect you from naming violations (for example, with `{{ lower .Release.Name }}`). Probably, that ought to be added to official Kubernetes Charts fullname templates, of it's not there already.

@prydonius may also want to weigh in, since I know he's been following the naming issue for quite some time.

Also, for the maximum name length... in 1.4.1 it was limited to 64, not 253, characters. Can anyone verify that the actual limit is now 253? My quick test allowed me to create a 73 char name, but some pod names seem to have been unpredictable truncated.

**Comment by iamzhout** [comment]
@kdada According to this PR(https://github.com/kubernetes/kubernetes/pull/29523), the length limit for service is 63 characters, and there do have different length limit for different kind of resources in k8s, so 63 chars limit is a safe bet for now I think.

**Comment by bacongobbler** [comment]
yep. Pods can have names up to 253 characters, but services created with the pod name via `kubectl expose` are truncated to 63 characters. The name length limitation differs from resource to resource.

**Comment by kdada** [comment]
@technosophos 
Should remind users of these limitation in doc?

**Comment by jascott1** [comment]
@kdada With the growing number of Kubernetes resource types and fast pace of development in general, it might be an unnecessary burden to track that in Helm. A definitive reference from Kubernetes would be great.

Im going to close this issue due to inactivity but feel free to re-open if you think its important for Helm to provide this and we can continue the discussion.
