### ISSUE TITLE
Helm Incorrectly Reporting Release "Deployed"

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/helm#2027]
During deployment of the stable/spinnaker chart, Helm reports it is deployed:

```
$ helm list
NAME            	REVISION	UPDATED                 	STATUS  	CHART                       	NAMESPACE
orange-marsupial	1       	Fri Feb 24 14:44:04 2017	DEPLOYED	spinnaker-0.1.1             	spinnaker
viable-quail    	1       	Thu Feb 23 13:23:45 2017	DEPLOYED	aws-cluster-autoscaler-0.2.0	default  
```

But part of the deployment failed. Observe in the following that the Redis replica set has zero running pods:

```
$ kubectl --namespace spinnaker describe replicaset orange-marsupial-redis-4063252840
Name:		orange-marsupial-redis-4063252840
Namespace:	spinnaker
Image(s):	bitnami/redis:3.2.5-r0
Selector:	app=orange-marsupial-redis,pod-template-hash=4063252840
Labels:		app=orange-marsupial-redis
		pod-template-hash=4063252840
Replicas:	1 current / 1 desired
Pods Status:	0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Volumes:
  redis-data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	orange-marsupial-redis
    ReadOnly:	false
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  9m		9m		1	{replicaset-controller }			Normal		SuccessfulCreate	Created pod: orange-marsupial-redis-4063252840-wbzcg
```

**Comment by technosophos** [comment]
The design of Helm is that it is responsible for deploying _to the Kubernetes API server_. Once the server has accepted the resources for running, Helm considers the resource to be `DEPLOYED`. (Really, we probably should have called it `INSTALLED`, because it's more analogous to installing an application versus actually running the application. But that was confusing in regard to upgrades).

To put it in terms of a traditional OS package manager, you can _install_ Apache on a server, and successfully complete the installation. And it is a successful install even if you go to start up the application and it won't work because it's configuration is wrong.

The `helm status` command is basically a convenience wrapper so that you can check about Kubernetes' state of a deployed release.

**Comment by pluttrell** [comment]
Thanks for the info and clarification. I also understand the naming dilemma.
