### ISSUE TITLE
Amending the Chart spec so that the an (optional) application version can be including, for display usage in things like monocular

### ISSUE THREAD

**Issue by solarce** [kubernetes/helm#2035]
I opened a [monocular GH issue](https://github.com/helm/monocular/issues/192) about having it / https://kubeapps.com show the application version (where helpful) along with the Chart version. @migmartri indicated that this would need some upstream change(s) in Helm itself and requested I file an issue to start a discussion.

My, admittedly naive, understanding is that the addition of a key like `application_version` to the [Chart specification](https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chartyaml-file) is where things would need to start?

**Comment by technosophos** [comment]
I'd be okay with adding this.

I was under the impression that a wide variety of charts allow this to be set by the user (by overriding the right tag or image value in the values file). But as a purely informational field, I think we could add it.

/cc @migmartri @prydonius

**Comment by migmartri** [comment]
> I was under the impression that a wide variety of charts allow this to be set by the user (by overriding the right tag or image value in the values file). 

Ideally, I'd prefer to add the field to the chart.yml spec so:

1 - From Monocular's side, It will require less effort to extract that info.
2 - Adding linting support for both field SemVer(If applicable) and existence should not be difficult
3 - Will make Chart maintainer's review easier since the value will be enforced and clearly marked.

@prydonius what do you think?

**Comment by prydonius** [comment]
In general, I think it's useful to separate these two versions. Over in the charts project, we are seeing a mix of maintainers keeping the chart version tied to the application, or just ignoring the application version entirely. This often leads to confusion about what a chart version should be bumped to, and also leads to incorrect use of semver (e.g. https://kubeapps.com/charts/stable/chaoskube).

I think an optional `app_version` field will definitely help to avoid confusion like this in the charts project.

This also becomes more important if we need to support different stable versions of an application (e.g. Drupal 7 and 8), though the proposed field doesn't necessarily solve this issue as these may need to be two different charts with different names.

**Comment by technosophos** [comment]
Okay, this is starting to get clearer. So for the sake of simplicity, let's say that this version is roughly "the version of the default image"

What do we do with charts that have multiple images?

Say we have a fictional chart that deploys Drupal with a local memcached cache (deployed as a second container in the same pod).

- Option 1: Force user to pick "the most relevant"

```yaml
name: Drupal
version: 1.2.3
appVersion: 8.1.2
```
- Option 2: Make the field list-like

```yaml
name: Drupal
version: 1.2.3
apps:
  - name: Drupal
    version: 8.1.2
  - name: memcached
    version: 1.3.4
```

**Comment by prydonius** [comment]
I think Option 1 is the simplest. Given that things like memcached should in most cases be dependent charts, that chart would have its own appVersion.

**Comment by migmartri** [comment]
I vote for the option 1 as well.

**Comment by mgoodness** [comment]
I concur with @prydonius & @migmartri; `appVersion` should refer to the chart's "primary" application.

**Comment by chancez** [comment]
As @technosophos alluded to:

I think you really must consider multiple apps. If a single chart has many containers, then it's extremely likely those containers each have separate, potentially unrelated versions. In this case, if you want this information to be useful, then each container (app) should have it's own version.

In my eyes, the version is most useful to do conditional templating for feature flagging, and maintaining backwards compatibility (see: https://github.com/kubernetes/helm/issues/2087). If you can't make this distinction on a per container basis, it becomes much less useful, since it cannot be used for the use-case mentioned.
