### ISSUE TITLE
Proposal: Lifecycle management of `--wait` flag

### ISSUE THREAD

**Issue by thomastaylor312** [kubernetes/helm#2095]
## Current Problem
So one unintended side effect of the `--wait` flag is that it prevents any `post-*` hooks from running until everything is in a ready state. A real world example of this is that if we have an umbrella chart with InfluxDB and Kapacitor (which needs to connect to Influx with a specific user), I need to have a hook that creates this user on Influx. If I use `--wait`, things will never get to a ready state because the `post-*` jobs won’t run. There are some workarounds for this (like creating a `Job` as part of the chart or using `postStart` in the Kubernetes manifest), but they are all a little clunky.

## Solution
I propose we add a new hook type called `during-*` for `install`, `upgrade`, `delete`, and `rollback` that will be run parallel to the manifests being sent to Kubernetes. This will allow for bootstrapping jobs to work with the `--wait` flag. 

## Potential Issues
If someone is not using the `--wait` flag, `during` and `post` hooks will essentially be the same thing. With `--wait`, the `post` hooks become more like `post-ready` hooks because they will be running against a Chart that is in a ready state. This could lead to confusion.

**Comment by technosophos** [comment]
So if we were to add a `post-ready` instead of a `during-`, to handle a non-wait case we'd basically have to:

- Check if there are any post-ready hooks. If so...
- Start a new goroutine that basically fires the wait logic
- When the wait finished, install the hook resources

That _might_ be a better solution, since it will essentially give users a new and useful hook. I've been asked for this in the past, and have generally said no, though, because I didn't want us to end up in the "release monitoring" business.

**Comment by thomastaylor312** [comment]
I am closing this in favor of the discussion and proposal going on in #2243
