### ISSUE TITLE
Auto generated release names too long / truncating service names

### ISSUE THREAD

**Issue by dstengle** [kubernetes/helm#2116]
I had a failing helm install of stable/spinnaker due to the orca pod.

It was trying to reach a service named "interested-bumblebee-redis", but the service that got created was "interested-bumblebee-red", so it kept failing.

helm version
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
This should probably live in https://github.com/kubernetes/charts.

**Comment by dstengle** [comment]
This issue is a little strange. The name is only 25 characters, so it should have been well under the service name limit of 63 and not get truncated. I can't figure out where the conditional truncation is happening. The redis chart has a 63 character truncate in the templates, but that is it.

**Comment by prydonius** [comment]
Agree with @bacongobbler that this should be in kubernetes/charts.

Looks like the issue is that Spinnaker is locked to an older version of Redis that used to truncate to 24 chars.
Spinnaker requirements: https://github.com/kubernetes/charts/blob/master/stable/spinnaker/requirements.yaml

Redis is locked to 0.4.2, and in the following commit 0.4.3 updates Redis to truncate to 63:
https://github.com/kubernetes/charts/commit/48740ddcfbbc76cfde90c4f9aa670957a215b6a0

**Comment by dstengle** [comment]
Thanks. I looked at the master redis, not the required version.

Closing this.

**Comment by prydonius** [comment]
@dstengle I created a PR (https://github.com/kubernetes/charts/pull/799) to update Spinnaker to point to the latest Redis. This should fix the issue.

**Comment by dstengle** [comment]
@prydonius Thank you!
