### ISSUE TITLE
Ports field is required for services of type ExternalName

### ISSUE THREAD

**Issue by sburtontx** [kubernetes/helm#2122]
In the [kubernetes documentation](https://kubernetes.io/docs/user-guide/services/) it states:

> An ExternalName service is a special case of service that does not have selectors. It does not define any ports or endpoints. Rather, it serves as a way to return an alias to an external service residing outside the cluster.

However, helm requires all services have a ports field or else the chart will not install.

**Comment by technosophos** [comment]
Helm should not require _anything_ about a service other than that it is in a valid format. Can you drop in the error message you are seeing?

**Comment by sburtontx** [comment]
The error is `Error: error validating "": error validating data: field ports: is required`.  If I remove the service file or add some dummy ports then the error goes away.

**Comment by technosophos** [comment]
That error is bubbling up from the Kubernetes validator. You can try running `helm install --dry-run --debug` and then using `kubectl` to send the manifest to Kubernetes. That might shed light on what is going on.

**Comment by sburtontx** [comment]
I tried running `helm install --dry-run --debug $CHART_DIR` and I got the same error.

> Error: error validating "": error validating data: field ports: is required

Is there a way to bypass the validation step?

**Comment by bacongobbler** [comment]
try `--verify=false`?

**Comment by bacongobbler** [comment]
You can also try `helm lint $CHART_DIR`.

**Comment by technosophos** [comment]
Or use the `helm template` plugin.

The bottom line is that your manifest is failing the Kubernetes validation, so very likely the manifest you are generating is being rejected because it is malformed. Helm doesn't do its own validation. It just validates against Kubernetes. So if that step is failing here, there is a high, high probability that it will fail anytime it is submitted to the Kubernetes server.

Without seeing the manifest or template, there's not much we can do to help out.

**Comment by bacongobbler** [comment]
closing this as inactive. Please re-open if you have more info to share. Thanks!
