### ISSUE TITLE
helm init should include tiller limits options

### ISSUE THREAD

**Issue by mattymo** [kubernetes/helm#2135]
helm init should include support for --tiller-cpu-limits, --tiller-cpu-requests, --tiller-memory-limits, --tiller-memory-requests so that Kubernetes can allocate appropriate resources for tiller

**Comment by at1012** [comment]
I would like to work on this feature.

**Comment by mvernimmen** [comment]
I'm running into the same problem when trying to deploy tiller to a multi-tenant cluster using namespaces, RBAC and quotas. Output from the replicaset:
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  33m		11m		19	replicaset-controller			Warning		FailedCreate	Error creating: pods "tiller-deploy-121279995-" is forbidden: failed quota: test-quota: must specify limits.cpu,limits.memory
```
 Since the work done on this is from a while ago, could someone please be so kind to provide some insight into the current status of implementing this feature request?
I have a workaround for those running into the same problem:
```
helm init --service-account tiller-test --tiller-namespace test --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' --override 'spec.template.spec.containers[0].resources.limits.cpu'="2" --override 'spec.template.spec.containers[0].resources.limits.memory'="1Gi"
```

**Comment by prageethw** [comment]
I found it is much easier as below

kubectl set resources deployment tiller-deploy  --limits=cpu=10m,memory=20Mi -n kube-system
