### ISSUE TITLE
PROPOSAL: pluggable storage backend for chart repo server

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/helm#2141]
# Proposal: pluggable storage backend for chart repo server
## User case
The idea here wants to solve the same issue described in #2093. 
There is needs to put the charts on a storage besides Linux file system, such as Swift. The proposal here is to keep helm chart_repo client unchanged, and divide helm chart_repo server logic to two parts:
1. chart repository logic(main part should be "index.yaml" generation and chart reading logic) ;
2. chart storage logic.
The idea here is to keep chart repo client/server HTTP interface unchanged, but make the storage backend part of chart repo server be pluggable:
It can read charts from Linux file system, Swift, and etc.

**Comment by technosophos** [comment]
Thanks for creating this new proposal.

As I understand it, this would make it possible to run `helm serve` and use a back-end like Swift or S3 instead of the local filesystem. Is that right?

**Comment by tonyaw** [comment]
Yes. 
That is correct. :-)

**Comment by libesz** [comment]
Coming back to this topic now, after the downloaders are pluggable.
Would you accept a PR which only solves the first bullet of @tonyaw use-case?
My thinking is that if I want to compose an alternative tiller client (not necessarily in helm plugin, but with helm code pkg import...), let's say, which want to use non-http backend, than from chart mgmt PoV I have to be able to:
* Download and dep-build charts from my custom backend - that is solved by the pluggable downloaders
* Upload charts to my custom backend - this does not mandate any helm code I think, since downloader core is already own code and not part of helm
* (Re)generate `index.yaml` and push to custom backend

Since the first two is fine already, now I want to solve the last thing. Index generation is currently accept local directory with charts to parse. I would like to introduce a generic layer under `IndexDirectory()` in `pkg/repo/index.go`. Than `IndexDirectory()` would call this generic layer, just like custom user code. Generic interface maybe only need to transfer the list of chart URLs to parse. 

How does it sound?

**Comment by bacongobbler** [comment]
[chartmuseum](https://github.com/kubernetes-helm/chartmuseum) allows for pluggable storage backends and regenerates index.yaml based on the contents from that backend. I think we can consider this closed and users who are interested in doing this should use chartmuseum as their repository server instead of `helm serve`. `helm serve` was never meant to be anything more than a basic web server for development purposes anyways. :)
