### ISSUE TITLE
<chart>.tgz downloaded to directory from which helm is run

### ISSUE THREAD

**Issue by jwandrews** [kubernetes/helm#2142]
Running helm `install` or `upgrade --install` downloads .tgz file to current directory when you use a helm repo for charts. This is somewhat annoying (and tedious to clean up) as we don't want to accidentally commit these files to our source control or have them dirtying up our filesystem out in the open. 

Maybe they could be downloaded to a central location like `~/.helm/repository/cache/archives` or something similar so they aren't spread out in whatever directory `helm` happened to be ran.

**Comment by technosophos** [comment]
I'd be okay with storing these somewhere in `$HELM_HOME`. It's necessary to store them in a non-temp space because of the plugin toolchain. But storing them in CWD is truly annoying.

There's an existing PR that defines a new `$HELM_HOME/cache` directory. It will hold `$HELM_HOME/cache/plugins`. That would be a good place to put a `$HELM_HOME/cache/archive` or something like that.

**Comment by michaelajr** [comment]
big +1
