### ISSUE TITLE
Base auth: helm repo index --url

### ISSUE THREAD

**Issue by hekike** [kubernetes/helm#2154]
Hi, can you help me?

I add my Base auth protected repository like this:
```
helm repo add myrepo https://x:y@helm.mydomain.com
```

Should I index it without base auth params?

```
helm repo index ./ --url https://helm.mydomain.com
```

or with:

```
helm repo index ./ --url https://x:y@helm.mydomain.com
```

Without the Base auth params in the indexing, it doesn't work.
But is it okay? I think it should use access params from `repo add` and we shouldn't bake access params to index.yaml

Do I miss something?

**Comment by ursuad** [comment]
No that's correct. I have the exact same issue. And because in the docs ( [here](https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#ordinary-web-servers) ) it's specified that for a regular webserver:
```
Make sure the index.yaml file can be accessed with no authentication requirement
```
and then you encode all your authentication details ( user/pass) in the unprotected `index.yaml` with `helm repo index ./ --url`. 

@technosophos I think this is a bug, because if you don't encode the user/pass with the `helm repo index --url`, `helm install `will fail with `HTTP/1.1 401 Unauthorized` when trying to install a chart. 
Or, maybe mention in the docs that basic auth is not supported yet if that's the case?
