### ISSUE TITLE
Proposal: dump/restore features

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#2470]
Helm releases dump/restore functionality would be very helpful for cluster migration/disaster restore:
`helm dump -f state.json` 
`helm restore -f state.json

**Comment by flah00** [comment]
With kube-aws-0.9.7, you can dump [etcd databases and kubernetes objects to s3](https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-backup-and-restore-for-etcd.md). The dumps, mercifully, can also be restored. But, my restore would only be worth so much, because I assume my tiller's data would no longer exist.

I would love to include tiller in my kube-aws dumps. Is this possible now? Is it feasible at all?

**Comment by bacongobbler** [comment]
If someone wants to write a plugin to dump and restore the configmaps helm creates, go nuts! This would be an awesome plugin to see.
