### ISSUE TITLE
helm pkg proto hapi can not talk to tiller, incompatible versions

### ISSUE THREAD

**Issue by ZhenyangZhao** [kubernetes/helm#2505]
Dear all:

###Problem
I use helm & tiller with 2.4.2, on the server i can `helm list` release.But when i use hapi golang code(tag v2.4.2) seem to be error.
```
rpc error: code = Unknown desc = incompatible versions client[] server[v2.4.2]
```
###Environment
```
golang: 1.7
kubernetes: 1.6.3
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```
Thanks a lot.

**Comment by fibonacci1729** [comment]
Can you provide more details? It's not immediately clear to me what you mean when you say "hapi code"; by this are you referring to the helm client APIs? From what I understand, the helm client works for you.

**Comment by ZhenyangZhao** [comment]
@fibonacci1729  Thanks a lot .my mistake. I solved this problem by `metadata.Pairs("x-helm-api-client", version.Version)`
:)

**Comment by migueleliasweb** [comment]
I'm not sure if this was just your mistake. I'm having similar problem when trying to call Tiler from a custom client. Basically if we don't set the version within the context, Tiller yields an error on the logs..

Example:

Gopkg.toml
```toml
[[constraint]]
  name = "k8s.io/helm"
  version = "2.6.2"
```

```bash

```

main.go
```go
package main

import (
	"context"
	"log"

	"google.golang.org/grpc"
	"k8s.io/helm/pkg/proto/hapi/services"
)

const (
	//kubectl --namespace=kube-system port-forward {tiller's pod} 8080:44134
	address = "localhost:8080"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	} else {
		log.Println("Connected!")
	}
	defer conn.Close()

	c := services.NewReleaseServiceClient(conn)
	request := services.ListReleasesRequest{}
	result, err := c.ListReleases(context.Background(), &request)

	if err == nil {
		response, err2 := result.Recv()
		log.Println("Got ", len(response.GetReleases()), "releases !")

		if err2 == nil {
			for _, r := range response.GetReleases() {
				log.Println(r.GetInfo())
			}
		}
	} else {
		log.Println("Got error: ", err)
	}
}
```

Tiller errors from logs (kubectl --namespace=kube-system logs -f {tiller-pod-name})
```
2017/10/27 03:05:02 incompatible versions client[] server[v2.6.2]
```
Btw, the installed grpc version installed with dep (v1.7.1) differs quite a bit from the one in [Glide.yaml (v1.2.1)](https://github.com/kubernetes/helm/blob/master/glide.yaml#L28)

**Comment by bacongobbler** [comment]
You need to import pkg `k8s.io/pkg/helm/client` and switch your context from `context.Background()` to `helm.NewContext()` as seen [here](https://github.com/kubernetes/helm/blob/6643a21271b193db067700b8fe49b2825d0fcc9e/pkg/helm/option.go#L425-L429). Essentially tiller cannot authorize your request because no api compatibility flag was sent from the client so it has no idea if it can handle the incoming request.

Example can be found here [in pkg/helm/client](https://github.com/kubernetes/helm/blob/24238bbe207949b155707aba792dabe4893f21e5/pkg/helm/client.go#L51-L65) (which I would suggest using, it's a lot easier to use as a client instead of pkg/proto).

**Comment by bacongobbler** [comment]
@ZhenyangZhao is right though. Sending a context using that metadata pairs to specify `x-helm-api-client` will get it working.. Or just use the existing package that already sets that up for you. :)

**Comment by migueleliasweb** [comment]
Thanks @bacongobbler ! 

I was digging into the code and found this client ( `k8s.io/helm/pkg/helm.Client` ) that would simplify things a lot. You could see from my previous comment I tried to install helm using `dep` but seems like I have an inconsistent build right now.

Right now, after finding about this client, what I'm trying to do is this:

```go

package main

import (
	"log"

	"k8s.io/helm/pkg/helm"
)

const (
	//kubectl --namespace=kube-system port-forward {tiller's pod} 8080:44134
	address = "localhost:8080"
)

func main() {
	c := helm.NewClient(helm.Host(address))
	response := c.ListReleases()

	for r := range response.GetReleases() {
		log.Println(r)
	}
}

```

But I got this error: `vendor/k8s.io/helm/pkg/helm/option.go:428:9: undefined: metadata.NewContext`. This is due to the fact grpc version fetched by dep is v.1.7.1 but according to [Glide.yaml](https://github.com/kubernetes/helm/blob/v2.6.2/glide.yaml#L28), Helm uses version v1.2.1.

Do you know how to get around this ? I really didn't want to change the Gopkg.lock manually (that would be too much of a hack) or setup a specific version for it at my Gopkg.toml...

**Comment by bacongobbler** [comment]
AFAIK we need to stick to an older version of GRPC due to [kubernetes' reliance on grpc v1.3](https://github.com/kubernetes/kubernetes/blob/94e77bd4cab597b4cf978ed4c1726c93b01de295/Godeps/Godeps.json#L2917-L2919), but I forget the reasoning now.

You'll have to specify the deps defined in helm's glide.yaml into your Gopkg.toml. You can use https://github.com/Azure/draft/pull/385 as a reference.

**Comment by migueleliasweb** [comment]
FYI, I kept digging and turns out the whole issue was due Golang's Dep is not ready yet for merging dependencies-of-dependencies atm. The problem with the version was due to the fact Dep does not check recursively dependencies-of-dependencies for extra version contraints. I raised an issue about this on Dep's repo and the guys are working on solving it in a near future.

Dep issue: https://github.com/golang/dep/issues/1321
Original Dep issue: https://github.com/golang/dep/issues/821

**Comment by sdboyer** [comment]
> Golang's Dep is not ready yet for merging dependencies-of-dependencies atm. The problem with the version was due to the fact Dep does not check recursively dependencies-of-dependencies for extra version contraints.

to clarify rq - dep _does_ read `Gopkg.toml` constraints for **all** projects - the root/current project, direct dependencies, and transitive dependencies. while we do automatically convert metadata files from other tools (e.g. `glide.yaml`, `Godeps.json`, `vendor.json`, `vendor.conf`) during `dep init` as a one-time hint, that's only done for the root project's old metadata file. we do not, during normal operations, read and convert those files in dependencies, direct or transitive - that's the thing those we're working on enabling soon.

**Comment by focusaurus** [comment]
I'm seeing this same issue trying to use generated grpc javascript in node.js. `Error: 2 UNKNOWN: incompatible versions client[] server[v2.8.0]`. Can anyone point me at where I might specify the client version? I have tried `metadata.setTillerversion("2.8.0")` and `metadata.setVersion("2.8.0")` in my chart's metadata but that doesn't fix it.

**Comment by ZhenyangZhao** [comment]
@bacongobbler
Sorry for reply this later.
```
md := metadata.Pairs("x-helm-api-client", version.Version)
```

**Comment by migueleliasweb** [comment]
_Just because this might be handy for somebody in the future._

The way I have (kind of) fixed the problem with `undefined: metadata.NewContext` was pin-pointing the version of gRPC inside Gopkg.toml:

```toml
[[constraint]]
  name = "k8s.io/helm"
  version = "=2.7.2"

[[override]]
  # https://github.com/golang/dep/issues/821
  # https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
  name = "google.golang.org/grpc"
  version = "=1.2.1"
```

With this I was able to run the commands from `k8s.io/helm/pkg/helm.Client`. Eg.

```go
package main

import (
	"log"

	"k8s.io/helm/pkg/helm"
)

const (
	//kubectl --namespace=kube-system port-forward {tiller's pod} 8080:44134
	address = "localhost:8080"
)

func main() {
	c := helm.NewClient(helm.Host(address))

	// Listing all releases
	response, _ := c.ListReleases()

	for _, r := range response.GetReleases() {
		log.Println(r)
	}
}
```

**Comment by munai-das** [comment]
Thanks @migueleliasweb. This came handy :)
