### ISSUE TITLE
Proposal: Jsonnet template integration

### ISSUE THREAD

**Issue by eicnix** [kubernetes/helm#2577]
In order to provide jsonnet rendering for helm charts a new ReleaseModule similar to the Rudder ReleaseModule should be developed. 
This module would take charts and render them as Jsonnet templates. Afterwards it will apply the resulting Kubernetes Objects similar to the default LocalReleaseModule. 
 
### Registering the ReleaseModule
Since the current ReleaseModule implementation does not provide the capability to choose between multiple custom ReleaseModules this implementation would need to add this. 

If the `experimental-release` flag is set, all ReleaseModules will be registered into a map. 
When a Chart interacts with Tiller, Tiller will check the `releaseModule.name` of the Chart and choose a ReleaseModule with the matching name from the list.
 
**Should the LocalReleaseModule be used as a fallback if no matching ReleaseModule was found?**

### Providing jsonnet libraries

Jsonnet libraries like the ksonnet lib can be put under the `library` folder next to the `template` folder. Jsonnet files in this folder will not be directly rendered. 
 
**Size can be issue since the current ksonnet lib file is 1.7 mb and ConfigMaps can only store 1mb.**

### Assumptions for the template format

In order to use jsonnet templates a few assumptions need to be applied to the templates:  
- Every file in the template directory that does not start with `_` and ends with `.jsonnet` will be rendered
- Every rendered file must produce a valid kubernetes objects. Otherwise the whole action fails and no object will be applied. 
- If a jsonnet template wants to use values, chart or release information the file needs to start with `function(values, chart, release)`. This data will then be passed as a top level argument to the jsonnet template.

**Comment by bacongobbler** [comment]
You might be interested in [`helm-ksonnet`](https://github.com/technosophos/helm-ksonnet). Does that help you? Essentially it translates jsonnet templates into helm packages which can then be shipped to tiller.

**Comment by bacongobbler** [comment]
Arguably I think the client integration is the way to go. That way there's no fragmentation between the default `text/template` template engine in tiller and the jsonnet template engine.

**Comment by eicnix** [comment]
@bacongobbler Client side integration has its drawbacks too: You can't integrate with the Helm value management unless you are doing a two stage rendering: first rendering jsonnet into yaml with `{{.Values.value}}` placeholders and then into json with the default go template engine. But I feel this can get very complicating when you are trying to escape values over multiple rending processes.

**Comment by seh** [comment]
I too imagined _jsonnet_ integration as creating a peer to the current `text/template` integration, with a higher-level dispatcher that could choose among them, such that each would take a set of files as input and produce (in-memory) Kubernetes objects as output.

**Comment by seh** [comment]
There was [some preceding discussion](https://kubernetes.slack.com/archives/C51E88VDG/p1497254572938276) in the "helm-dev" channel of the "Kubernetes" Slack team.

**Comment by anguslees** [comment]
Fwiw: Speaking for https://github.com/ksonnet/kubecfg (go-based cli tool for k8s config expressed in jsonnet), we're very happy to refactor anything that would help integrate the core jsonnet -> k8s objects library into another codebase.

**Comment by prydonius** [comment]
> Providing jsonnet libraries

I don't think the ksonnet library should be tied to Tiller, this will make jsonnet charts dependent on the version of Tiller. Rather, the ksonnet library should be implemented as a chart that is imported and versioned as a dependency in the parent chart (the same way we expect the [common-chart](https://github.com/prydonius/common-chart/tree/merge-approach) to work).

**Comment by nikolay** [comment]
`<?xml version="1.0" encoding="UTF-8"?><rant><![CDATA[`
[Jsonnet](http://jsonnet.org/) is not a new project - it's been around for years, and Google used it for a thing or two but decided not to use it in Kubernetes or other projects as far as I know. Although it is better than static JSON, it's not better than the simplest embedded interpreter out there - Lua (via [eLua](http://www.eluaproject.net/)), JavaScript (via [Duktape](http://duktape.org/)), Ruby (via [mruby](http://mruby.org/)), Python (via [Micropython](https://micropython.org/)), etc. I wondered why [Jsonnet](http://jsonnet.org/) decided to implement something like JavaScript, but not simply a subset of it with domain-specific extensions. For example, they chose `local` and not the familiar `var` or `let`. They also implemented a stdlib that you have to learn instead of borrowing from JavaScript. I don't see the purpose of this "let's be different at any price" effort! Like we don't have enough languages and formats to learn already! So, instead of adding yet another format to the core, the best would be to add mechanisms where an external process can generate the configuration. Because what's next? [HCL](https://github.com/hashicorp/hcl), [JSON5](http://json5.org/), [Hjson](http://hjson.org/), [ICL](https://github.com/archipaorg/icl), or XML for the diehards? A love the simplicity of shebang and wonder why nobody uses it for dynamic configuration!
`]]></rant>`

**Comment by nikolay** [comment]
See, I even forgot [TOML](https://github.com/toml-lang/toml) - the number of choices is getting overwhelming!

**Comment by nikolay** [comment]
So, now that Google released [Skylark](https://github.com/google/skylark), which it uses internally, there's yet another option! 😄

**Comment by anguslees** [comment]
I see the <rant> tags, but I will point out that (as you have noticed) jsonnet is not javascript.  jsonnet is side-effect-free (referentially transparent) and closer to lambda calculus.  This brings a bunch of nice (formalised) properties for config template expansion, but can be restrictive in a general-purpose programming language.

A number of the others you list (XML, TOML, JSON5, etc) are not capable of templating (no parameter substitution, etc) so I wouldn't consider them candidates for this task.

I agree with your general point however, that there exists multiple reasonable choices in this space - and so it makes sense to openly declare never to support alternatives, or plan to support many alternatives (perhaps via a plugin mechanism)

**Comment by eicnix** [comment]
I did some prototyping around this issue and implemented a simple jsonnet template engine. 
Currently I am not convinced that jsonnet is the right way to improve templating inside helm. 

Here is a list of issues I've encountered: 
* Template files would need to follow certain conventions like start with a top level function to pass values, chart metadata, etc. 
* Size limits of ConfigMaps preventing the usage of larger jsonnet libraries like ksonnet
* [go-jsonnet](https://github.com/google/go-jsonnet) doesn't support custom importers so loading jsonnet libraries from a chart isn't possible
* [jsonnet_cgo](https://github.com/strickyak/jsonnet_cgo) supports custom importers but has some issues with being a wrapper aroungdthe jsonnet C code

Since implementing a new template engine would break any compatibility with exciting charts and conventions I am not sure if the jsonnet engine would gain much adoption. 

Here is a test that executes a jsonnet chart: https://github.com/eicnix/helm/blob/feature/jsonnet-engine/pkg/engine/jsonnet_engine_test.go

**Comment by seh** [comment]
Why would implementing a new template engine break compatibility with existing charts?

The idea we've discussed in the past is to separate the interpolation of templates ("rendering" in Helm parlance) from the application of in-memory Kubernetes objects, where by "objects" here I mean instances of the Go structs that define those objects' GVKs. One could argue that JSON is actually the most faithful, canonical form of a Kubernetes object, given the existence of the OpenAPI schema, but Helm sits atop _client-go_, and even if _client-go_ in Tiller turns around and serializes these objects as JSON to talk to the API server, I'm sticking to my statement that Go struct instances are canonical.

If we could reach that state in Tiller, then adding a new template engine that expands Jsonnet files to Go struct instances—as the current YAML engine does—would be a matter of registration. There could be any number of supported languages, as [@anguslees notes above](https://github.com/kubernetes/helm/issues/2577#issuecomment-336352631). So far, no one has has made a sufficiently convincing argument to warrant tearing up Tiller like that.

The current Helm demands both Go's `text/template` for interpolation and YAML as the encoding. Jsonnet commits to the JSON encoding and doesn't need `text/template`, though, notably, [the _kapitan_ project](https://github.com/deepmind/kapitan) mingles Jsonnet with Jinja2 interpolation. #3044 asks for the JSON encoding and doesn't mention an interpolator, perhaps assuming `text/template` would remain. One can't write interpolation rules without knowing the encoding, so there's a dependency there from interpolation to encoding, but Tiller could accept multiple encodings, where each encoding could in turn be subjected to any number of interpolators.

Your experiment here is valuable, but I think the Helm project would benefit more from generalizing the interpolation of text and the subsequent deserialization of formats (today, YAML and JSON) into Go struct instances.

**Comment by hausdorff** [comment]
@eicnix I'm not sure what you mean when you say go-jsonnet doesn't allow custom importers. `jsonnet.Importer` is an interface, and you can implement your own, and pass that to the go-jsonnet runtime. I _believe_ this should accomplish your goals.

If that does not accomplish your goals, I (and, I'm sure, @sparkprime) happy to talk about what you do need, and whether it would be reasonable to add it to go-jsonnet.

**Comment by eicnix** [comment]
@hausdorff I tried to write an implementation for the `ImportData` function inside the helm project but the fields of the `ImportedData` are private and cannot be set from the helm package. 

Am I missing something here?

**Comment by sparkprime** [comment]
> Template files would need to follow certain conventions like start with a top level function to pass values, chart metadata, etc.

I actually added this support *for* helm back in early 2016 :)  Designing templates that way is a little bit more verbose at first but brings productivity benefits for people trying to read them, because the parameterization is more explicit.  This is important when multiple files are involved, because the threading of parameters is explicit and modules can be understood from the outside.

There are alternatives (import callbacks, native callbacks, std.extVar) but I think you lose benefits you actually want if you go that route.

> Size limits of ConfigMaps preventing the usage of larger jsonnet libraries like ksonnet

importgzip? :)  But 1MB is quite large for a handwritten config file, I suspect if we're broaching that limit then we're putting too much in one place and should split it into multiple parts.


> go-jsonnet doesn't support custom importers so loading jsonnet libraries from a chart isn't possible

go-jsonnet will replace jsonnet_cgo very soon.  It is intended to be a more-or-less drop in replacement for the C++ version (without the reformatter).  I am currently adding a commandline utility in Go that exactly matches the C++ commandline utility (except without garbage collection parameters and reformatter).  The issue you raise is an oversight (we never used it out-of-package yet) and trivial to fix.  Just an early adoption hurdle.  Thanks for being an early adopter ;)

I support @seh's comment above.  In the pre-tiller deployment manager days, I implemented a scheme whereby each chart could choose from a set of 3 langages (Jinja+YAML and Python for deployment manager, GoTemplates+YAML for Helm) which also interoperated cleanly, i.e. charts could instantiate other charts through a language-independent mechanism.  The intention was to add Jsonnet as a 4th alternative once we got feature parity with the existing approaches.  That worked exactly how @seh is proposing -- each "expander" took a datastructure that represented the unprocessed files (from disk) and returned a list of JSON objects (k8s resources and other charts).  If you don't want the nesting, it can just return k8s resources.  In addition to that if it runs server-side I would recommend sandboxing it in a separate process so that you can bound CPU and RAM consumption.  That goes for all templating approaches, since it is trivial to DOS a server even in a non-turing complete language if there are no resource limits.

**Comment by technosophos** [comment]
Just to clear up a misunderstanding here, Helm does still have support for alternative template engines. Nobody has written any, though.

The selectable engine interface is still there (grep for EngineYard). Selectable template engines are still supported in Chart.yaml. The Rudder gRPC scheme even makes it possible to implement a remote template renderer. So somebody just has to go through the work of actually _writing the rudder_ to do this. That's a proto file and some glue code. And as I've said many times before, provided that it doesn't break backward compatibility, we would definitely consider adding this to Helm 2.

To @seh's point about compatibility, the main concern is that it will no longer be the case that "one size fits all" for Tiller. Some charts will declare that they need an alternative template engine that does not exist on a Tiller installation. And it's possible that (given dependency nesting) this will lead to incompatibilities where a chart can be installed on one cluster, and not another.

**Comment by technosophos** [comment]
And I might also note that since nobody has used that facility, there may be a few bugs we have yet to unearth. It's been a feature since Alpha.1, but the template rendering system has had some minor tweaks and changes over the subsequent 20+ releases.

**Comment by sparkprime** [comment]
Thanks for the clarification, looks like this is the interface:
https://github.com/kubernetes/helm/blob/master/pkg/tiller/environment/environment.go#L92

It returns a string -> string map, what is the format exactly?

**Comment by bacongobbler** [comment]
Here is the actual rendering engine: https://github.com/kubernetes/helm/blob/dbb84a1b9e57d14b816ff9c70c82c5232a8d0d89/pkg/engine/engine.go#L57-L76

[The unit tests](https://github.com/kubernetes/helm/blob/dbb84a1b9e57d14b816ff9c70c82c5232a8d0d89/pkg/engine/engine_test.go) should give you an idea on the output of `Render()`.

**Comment by hausdorff** [comment]
> And as I've said many times before, provided that it doesn't break backward compatibility, we would definitely consider adding this to Helm 2.

What is the process for proceeding here?

**Comment by hausdorff** [comment]
And, separately: one thing that causes me to hesitate before putting in this work is that it's not clear where templating is going for Helm v3. I gather that they way to observe these discussions is on the issue tracker, but I have not yet seen this discussion happen. So, it would be awesome if someone could say in broad strokes whether this work is likely to be used in Helm 3.

**Comment by bgrant0607** [comment]
For Helm v3, I would like the template expansion/rendering mechanism to be moved to external plugins -- no built-in template formats.

**Comment by bgrant0607** [comment]
FWIW, Helm classic approach:
https://github.com/helm/helm-classic/blob/master/docs/generate-and-template.md#the-helmgenerate-header

**Comment by jordan-da** [comment]
If I opened a PR that added jsonnet as a template engine, is this something the community would consider? It's hard to tell if we are open to these sorts of fundamental changes? 

For example, simply supporting `.jsonnet` files the chart, next to templated `.yaml` files. No command need to change, no need for experimental flags or anything, just support jsonnet files.

**Comment by jordan-da** [comment]
I took a crack at this while trying not to change anything core and came up with a pretty elegant solution by simply adding another template function that can do jsonnet.. so this works, with imports and all

```yaml
---
apiVersion: fakeapi/v2
kind: Fake
metadata:
  name: foo
spec:
  {{ dict "tla" . | jsonnetFile .Files "jsonnet/index.jsonnet" | toYaml | indent 2 | trim}}
```

This will not break no existing charts, no one actually has to use it because its just a template filter, and it supports "dynamic files" if you wanna `lookup` jsonnet files from config maps or something. Of course you don't have to mix yaml with jsonnet, this is just an example of how you might use this filter, you can just use only the filter and render all your manifests with jsonnet if you like.

@eicnix would this address your needs?
