### ISSUE TITLE
Proposal: move chart download to Tiller

### ISSUE THREAD

**Issue by weiwei04** [kubernetes/helm#2638]
We'd like to integrate tiller into our CI/CD system, to call the tiller api to deploy/upgrade/delete charts. 

I looked into the code, it seems for the Install/Update process, it is the helm cmd line download the chart and send the chart & value to tiller. I am not sure why not make tiller more like docker daemon, the helm cmd line just send value and a chart url, the tiller will download the chart from chart repository?

**Comment by seh** [comment]
My interpretation of the current design is that Tiller's responsibility includes "rendering" the chart—meaning taking a set of templates, interpolating them, and unmarshaling them into Kubernetes objects to be installed or updated—but does not care where these chart artifacts come from. Moving the chart acquisition responsibility into Tiller means also bringing in network access to the chart repository, chart caching, and forces use of a chart repository separate from the chart developer's computer.

That's not to say that this proposal is infeasible to satisfy. One could imagine packaging up parts of the _helm_ program's chart management capability and making them available for use from Tiller as well. An alternate approach is to introduce a separate server to which the _helm_ client could talk, delegating most of what is its local responsibility today to this server that does the same work somewhere else, so that _helm_ is more like a remote control for a chart management agent running elsewhere. Since we are running short on boat and ship directional control terms, we can call this thing "[Azipod](https://en.wikipedia.org/wiki/Azipod)." (I am reserving "[cyclorotor](https://en.wikipedia.org/wiki/Cyclorotor)" for a future project.)

**Comment by weiwei04** [comment]
Thanks, the "Azipod" is our current design, we are writing a server to provide the helm client's function as http api.

**Comment by bacongobbler** [comment]
@weiwei04 did you ever come around to writing this API
? Would be neat to see what you came up with.

**Comment by weiwei04** [comment]
@bacongobbler at first I try to create a grpc-server implement all tiller api(see https://github.com/weiwei04/compass/blob/develop/pkg/compass/compass.go) stand in front of tiller proxy all the request to tiller and do the download stuff at the grpc-server, but the tiller api did not fit into our current http based infrastructure, so I write another poc, defined a new set of grpc api and use grpc-gateway to transform grpc-api to http-api(see https://github.com/weiwei04/compass/blob/master/pkg/api/services/compass/compass.proto & https://github.com/weiwei04/compass/blob/master/pkg/services/compass/compass_service.go)
