### ISSUE TITLE
first init 'Warning: Tiller is already installed in the cluster',then 'Error: cannot connect to Tiller'

### ISSUE THREAD

**Issue by inewlife** [kubernetes/helm#2640]
I use 'brew install kubernetes-helm' on mac

**Comment by seh** [comment]
To clarify, are you saying that the first time you ever ran _helm init_ in a cluster that had never had Tiller installed, _helm init_ complained that Tiller is already installed? _Is_ Tiller running in your cluster? By default, you'd probably find it running in the "kube-system" namespace.

**Comment by MostAwesomeDude** [comment]
I have run into this, somewhat.

Last night, I had a working Helm and Tiller. I was using Helm 2.5.1. (2.6.0 doesn't change anything.) Today, my cluster has the following strange behaviors.

First, Tiller isn't running. The `tiller-deploy` Deployment is stuck at 0 instances, and `kubectl scale --replicas 1 deploy/tiller-deploy --namespace kube-system` doesn't leave anything good in the logs. It does scale up, but then it's immediately scaled back down somehow, although there *is* a short window of time where Helm can reach Tiller.

Second, `helm init` gives me the "Warning: Tiller is already installed in the cluster." message, regardless of which pieces of Tiller are actually present in the cluster. I tried removing the Deployment, as mentioned in the documentation. That isn't sufficient. I also tried removing the Service. That wasn't sufficient either. The actual code which installs Tiller installs a Deployment, a Service, and a Secret; I couldn't find the Secret, though.

I actually looked at the code which gives this error message in `helm init`. There's a logic error, and while the error message says that Tiller is already installed, what actually happened is that an error occurred while trying to install Tiller. Or at least that's what it looks like to me.

I'm not willing to tear down my cluster, but I'm willing to do most things short of that to figure out what's going on. I rather like Helm.

Oh, and that's the third thing: Tiller is still running fine on my other cluster, which I also had not touched since last night, and Helm can install stuff.

**Comment by jascott1** [comment]
@MostAwesomeDude The last piece of Helm to delete is the configMap (typically in the kube-system namespace).

**Comment by jascott1** [comment]
@inewlife If you can re-produce it would be helpful to see what Tiller objects existed when that command failed. You can get this with `kubectl get all --all-namespaces`. 
To troubleshoot further it would be great if you could first remove Homebrew's Helm and then check that kubectl doesn't show any Tiller objects with `kubectl get all --all-namespaces`. Then re-install. 

When we see `Warning: Tiller is already installed..` that means that Kubernetes came back with StatusAlreadyExists for either the Deployment, Service or Secret (if TLS is enabled). Its not clear to me what conditions can trigger this response but two concurrent requests might.

For a quick sanity check I just tried on my 2.5.1 and it was successful. 
```
$ k delete svc/tiller-deploy
service "tiller-deploy" deleted
$ k delete deploy/tiller-deploy
deployment "tiller-deploy" deleted
$ helm init
$HELM_HOME has been configured at /home/ubuntu/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
```

**Comment by jascott1** [comment]
@MostAwesomeDude Sorry I gave bad advice in that configMaps aren't for Tiller but just how charts are stored as Releases and aren't relevant unless we are trying to completely remove all traces. 

If your Deployment is running and then exiting it seems like something else is going on. Typically I would check node taints and node labels but iirc those containers are usually in crashLoop. If you want to discuss further would you please create a new issue and then post the output of the `kubectl describe` command for the Deployment? We can let this issue pertain to Hombrew `helm init`.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by MostAwesomeDude** [comment]
Hi, this is just to say that, for whatever reason, with the latest k8s releases on GKE and IBM Cloud, I am no longer able to reproduce any of my Helm problems. Thank you so much for your hard work.

**Comment by devops4sachin** [comment]
I was able to recreate this issue on the Bare-metal cluster. @MostAwesomeDude 👍 , you commands worked on my environment.
