### ISSUE TITLE
Proposal: Tiller-less Helm

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/helm#2722]
I'd like to contribute to a proposal for Tiller-less Helm, so that users could use `helm` to generate plain Kubernetes YAML manifest files without having to `helm install` nor `helm upgrade`, so users can instead apply manifests manually as they wish with `kubectl`.

The Helm server and client components are already separated, so users could choose to not install Tiller to forgo using the deployment manager feature, and only use the Helm client and its features such as templating, dependency management, and package control.

Before fleshing out a proposal, is there an existing proposal for this? Is this already on the roadmap? Has it been decided that this will not be done for version backwards compatibility? Should this be a plugin or is there an existing plugin?

UPDATE:
Please see the Helm v3 design proposal from Helm Summit in Feb 2018.

>Tiller is gone, and there is only one functional component (helm)

https://github.com/kubernetes-helm/community/blob/master/helm-v3/000-helm-v3.md

**Comment by bacongobbler** [comment]
One plugin that has been spun out of Helm to solve this exact use case would be [helm-template](https://github.com/technosophos/helm-template). It generates the manifests by running the template engine client-side (with a few limitations). Does that partially help solve your use case? Perhaps you could run with that plugin and create a separate plugin to perform these operations client-side for your particular use case.

**Comment by bacongobbler** [comment]
IMO I don't think there's any active proposal to do these operations on the client side, however. Way back when (helm v1) it was client-side only and there were many limitations with that design decision, which eventually sparked the Helm v2 effort to move a lot of the reconciliation and templating logic over to the server.

**Comment by thomastaylor312** [comment]
Tagging as a question until decided if this should be fleshed out more

**Comment by BugRoger** [comment]
I'm interested in this as well. 

Looking at the Helm workflow from a user's perspective, I feel it is way too complicated for most use cases. Recently my experience went like this:

1. Want to install a Chart (e.g. Prometheus). Yay, there is an official stable chart! 😄
2. 🤔  Do I need to bother with versions? Stable sounds good enough.
3. Clone the charts repo
4. Ugh. Geez, the chart is doing lots of things. Needs a lot of values.
5. Better to store the values locally for next time. Copy defaults. 
6. Install cloned chart with local values. Great success 👍 
7. 🤔  Image versions in the chart are quite outdated. Do I fork the chart repo? Copy the chart?
8. Of course, new parameters required. But ok, install updated forked chart
9. Hm. Some error. What is Helm actually trying to upload. Installing diff plugin.
9. Bug Fix on the official chart. Trying to pull in changes. Ow, argh. Merge conflicts. 
10. 😕 

Granted this is mostly a versioning problem. Also, the increasing complexity of the charts makes their management not trivial. I feel that I need to take care of too many different sources of truth:

* [ Remote | Local | Forked | Tiller ] Charts
* [ Default | Local | Tiller ] Values

And I don't even use the rollback feature and try to keep my local state consistent. Usually we also never rollback. Always rolling forward it is.

I guess, this all boils down to that I would like to have my state in Git(hub) and not in Tiller. Where I can see with version history what changed and when. I would like to have template, values and expanded configuration in one place.

**Comment by shyiko** [comment]
@bacongobbler any chance you can share some details on what where the limitations that motivated the switch from client-side (helm classic) approach to helm v2 (maybe you have some records / links to the discussions / anything)? I'd really appreciate any information on the subject.

**Comment by jascott1** [comment]
I just created a proposal #2755 to integrate the helm-template functionality into core. Our motivations are for improving chart development experience and testing output without requiring Tiller/k8s.

**Comment by bacongobbler** [comment]
I shared my thoughts in the dev call about why there was a shift over to a client/server model from the client-only model:

1. The release ledger logic is now all handled server-side. In v1 there was no release ledger, making upgrades/maintenance on installed charts a nightmare to manage, especially with multiple clients from different machines
2. We can do a deeper introspection about the state of the kubernetes cluster before and after an install/upgrade by chatting with tiller
3. A lot of the communication with the Kubernetes cluster can all be handled server-side instead of client-side, making it easier on clients with slower internet speeds
4. Maintaining a semver-compatible client is incredibly difficult with a consistently moving target (in the form of Kubernetes's API). Standardizing on a client/server model under our control makes it easier to guarantee there won't be sweeping changes to the client packages.

Feel free to take a look at https://github.com/helm/helm-classic/issues to read up on some of the limitations of doing everything on the client side.

**Comment by JeanMertz** [comment]
We've also been looking for a server-less Helm solution for our packages. In the end, we wrote our own tool, available at:

https://github.com/blendle/kubecrt

It allows us to convert charts to regular resource files, and have our CI apply those files as we see fit (we run our CI as Jenkins, on top of Kubernetes, using the jenkins-kubernetes plugin).

Here's an example `charts.yml` file:

```yaml
apiVersion: v1
charts:
- blendle/web:
    version: ~> 0.9
    values:
      component: app
      contacts:
      - jean@blendle.com
      imageVersion: "{{ env "GIT_COMMIT" }}"
      public: false
      secrets:
        ADMIN_KEY: "{{ env "ADMIN_KEY" }}"
      resources:
        limits:
          memory: 200Mi
          cpu: 100m
        requests:
          memory: 128Mi
          cpu: 25m
```

It suits us really well, but of course, we have to maintain it, and update it whenever Helm/Kubernetes changes, including having the risk of it no longer working properly due to backward breaking changes in Helm.

This tool is not based on the plugin system (I believe we started it before plugins where available, but I'm not sure), but as I said, whatever solution is available to offer this functionality natively in Helm would help us a lot.

Until such time, we'll keep updating `kubecrt` to fulfil our needs of using charts, but in conjunction with our own deployment pipeline.

**Comment by bacongobbler** [comment]
Just curious, but does kubecrt handle a differing use case than [helm-template](https://github.com/technosophos/helm-template), which has now been rolled into core?

**Comment by JeanMertz** [comment]
@bacongobbler good question. I wasn't aware helm-template was merged into core already.

From reading the description, the first line states:

> This is a Helm plugin to help chart developers debug their charts

This might be outdated, but to us, `kubecrt` is more than a debug tool, it is the main tool with which all our ~700 pods are being deployed (or at least, the resource files being generated).

Also, the `charts.yml` file/format really suits our needs, as it allows us to quickly bring together a group of charts, define their values in a single file, and have all of the charts be converted to a single resource file.

I do believe Helm has such functionality now, but I haven't looked at it recently, and back when we wrote the initial version of kubecrt, the support wasn't there yet for us to simply adopt it.

**Comment by JeanMertz** [comment]
As a reference, a typical `script/deploy` file in one of our project looks something like this:

```
. ./config/deploy/environment.sh

kubecrt --namespace=article-to-speech-${ENV} \
        --name=article-to-speech \
        config/deploy/charts.yml | \
  kubectl apply --namespace=article-to-speech-${ENV} \
                --filename=- \
                --record \
                --validate
```

where all required environment variables are loaded from `environment.sh`, and then `kubecrt` parses the `charts.yml`, and fills in all the values/variables. The output is then piped to `kubectl`, which handles the actual deployment to our cluster.

**Comment by mattfarina** [comment]
@JeanMertz would `helm-template` plus `kubectl` provide a similar set of functionality to what you have in kubecrt?

@BugRoger Do you ever have the case where you need to switch computers or have multiple members of a team manage lifecycle of an app? Note, I really like that list. It would be great if the charts guide talked about more of this.

**Comment by JeanMertz** [comment]
@mattfarina I explained in https://github.com/kubernetes/helm/issues/2722#issuecomment-331733367 why I don't think it does. But, I have to investigate more to know for certain 👍

**Comment by bacongobbler** [comment]
> This might be outdated

Yes this is outdated. It was meant to be just a debugging tool but others have discovered its usefulness as a deployment tool as well (in combination with kubectl).

> Also, the charts.yml file/format really suits our needs, as it allows us to quickly bring together a group of charts, define their values in a single file, and have all of the charts be converted to a single resource file.

Helm has a concept called [umbrella charts](https://docs.helm.sh/developing_charts/#complex-charts-with-many-dependencies) which also solves this use case, however alternative tooling works too. It's just that these concepts already were in core. If they didn't solve your use case, we would love to hear more about it and how it can be solved!

**Comment by JeanMertz** [comment]
Thanks for the pointers @bacongobbler. I do believe that Helm templating + umbrella charts could replace `kubecrt` for us. I have to dig into this some more, but some questions that pop up into my head (no need to answer them, I'll find the answers once I dig into this at a later point in time, but just wanted to write them down nonetheless):

* Can I use Helm's (and Sprig's) templating functionality in `value.yml` files? kubecrt allows templating in the `charts.yml` file because we have a lot of environment variables + environment-based logic we want to inject during the deployment, without any manual intervention. We can of course use an external tool to handle that for us, but template functionality parity between charts themselves and the charts.yml file is something that we really like (and moved a step closer to in [kubecrt 0.6.0](https://github.com/blendle/kubecrt/releases/tag/v0.6.0)).

* Can I define semantic version constraints for sub-charts in an umbrella chart, instead of locking onto a specific chart version? We like to use the `~> X` constraint when pointing to our own internal charts, so we always get the latest bug fixes and feature enhancements in all of our projects when updating a centrally managed chart. We also set `~> X.Y` for charts not in our control, so we still get bug fixes, but guard against charts that don't quite follow the SemVer versioning rules, and introduce breaking changes in a new minor release.

* How light-weight can umbrella charts get? A chart has multiple components: resources, a chart.yml with versioning, and values.yml. The nice thing about a single `charts.yml` file is that that's all a project needs to be deployed to our infrastructure. The CI picks up on this file, and auto-deploys the service using `kubecrt`. The higher the barrier to entry for people to deploy new services, the more delays occur and/or resources are required to help people get started, so simplicity of the umbrella charts is a very important factor here.

Thanks for having this conversation with me 👍 I see a lot of overlap, and thus perhaps a path to moving from kubecrt to helm template, but I also still see some potential reasons why it might not suit our needs just yet.

**Comment by JeanMertz** [comment]
> @JeanMertz If you find a gap it may be worth asking for as a feature here. Since Helm 3 planning kicks off at the start of the year, now is a good time to ask about things.

Thanks, I'll do that 👍 



> Also, with the umbrella charts wouldn't you want a chart.yaml and values.yaml file? So that the values can set those of the sub-charts for the combination?

Yes indeed, but in our case, the `charts.yml` file contains both:

https://github.com/blendle/kubecrt#charts-configuration-file

**Comment by Ilyes-Hammadi** [comment]
It will be nice if the `helm template` could also work on remote charts that are hosted in a repository. Something like `helm template stable/redis` will be a useful addition to the `template` command. I'm really interested in this feature because it has happened to us that the Tiller was not responding and not restarting correctly, so all of our deployment pipelines where delayed 😕. To fix this issue we started using `helm tempalte CHART | kubectl apply -f -` to simulate the `helm install`, but of course we lost the nice rollback feature of `helm`. Then the second issue is that the helm chart started to accumulate in the project source code, and It will be much convenient to have them stored in a different repo and then just do `helm template REPO-CHART | kubectl apply -f -`.

**Comment by dhawal55** [comment]
+1
We are facing issues where `helm update` command succeeds but the changes are not applied. It would be great if we can use helm client for templating existing charts and use kubectl to deploy them.

**Comment by dhawal55** [comment]
@Ilyes-Hammadi I'm using `helm fetch` to fetch the remote chart first:
```
helm fetch stable/redis --untar --untardir build --version 0.10.2
helm template build/redis | kubectl apply -f -
```

**Comment by julianvmodesto** [comment]
Please see the Helm v3 design proposal:

> Tiller is gone, and there is only one functional component (helm)

https://github.com/kubernetes-helm/community/blob/master/helm-v3/000-helm-v3.md

**Comment by rogaha** [comment]
nice!

**Comment by jianzzz** [comment]
> I'd like to contribute to a proposal for Tiller-less Helm, so that users could use `helm` to generate plain Kubernetes YAML manifest files without having to `helm install` nor `helm upgrade`, so users can instead apply manifests manually as they wish with `kubectl`.
> 
> The Helm server and client components are already separated, so users could choose to not install Tiller to forgo using the deployment manager feature, and only use the Helm client and its features such as templating, dependency management, and package control.
> 
> Before fleshing out a proposal, is there an existing proposal for this? Is this already on the roadmap? Has it been decided that this will not be done for version backwards compatibility? Should this be a plugin or is there an existing plugin?
> 
> UPDATE:
> Please see the Helm v3 design proposal from Helm Summit in Feb 2018.
> 
> > Tiller is gone, and there is only one functional component (helm)
> 
> https://github.com/kubernetes-helm/community/blob/master/helm-v3/000-helm-v3.md

May I ask a question? If we use helm-v3, is there a standard way to use helm api, as we all know, for upper platform scheduling.

**Comment by gsemet** [comment]
Hi. I have move to tillerless helm v2 in Gitlab CI using Service Account token and it seems pretty safe and solid.
