### ISSUE TITLE
CLI flag to pass imagePullSecrets to deploy's?

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#2829]
Does Helm offer a command line flag for passing image pull secret references, e.g. `regsecret` from the [Kubernetes tutorial](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/), into `helm install` chart deployments?

I think a chart can be manually configured for image pull secrets, but it would be nice to be able to override this at runtime, for example when handed arbitrary, unauthenticated charts.

**Comment by jascott1** [comment]
@mcandre Helm does not have this feature but as you said you can accommodate by modifying your templates and passing the `regsecret` reference via `--set` or in your `values.yaml`.

**Comment by arno01** [comment]
It is supposed to be working in case when you set ``imagePullSecrets`` to a serviceaccount.

```
kubectl -n yournamespace patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regsecret"}]}'
```

I have tried kubectl v1.9.1 and it did create Pod, DaemonSet & Deployment with the ``imagePullSecrets`` available under the ``spec:``.


For some strange reason, it does take ``imagePullSecrets`` but only for the ``default-backend`` (with helm v2.7.2, when trying to install ``stable/nginx-ingress`` with ``controller.kind=DaemonSet`` or ``Deployment``):

```
nginx-ingress-controller-4fzbp                   0/1       ImagePullBackOff
nginx-ingress-controller-zcj67                   0/1       ImagePullBackOff
nginx-ingress-default-backend-548667657d-66m2m   1/1       Running         
```

When taking the YAML from ``helm install stable/nginx-ingress ... --dry-run --debug`` and manually ``kubectl apply`` it, then it is working (``imagePullSecrets`` gets propagated from the service account within the given namespace). It looks like the issue lies somewhere in Helm, but I am not certain.

**Comment by bacongobbler** [comment]
closing as answered
