### ISSUE TITLE
Proposal: use existing Helm releases as dependencies for a chart

### ISSUE THREAD

**Issue by nebril** [kubernetes/helm#2852]
This proposal aims to provide an option to `helm install` command which will replace chart dependencies with already existing helm release.

Use case:
- deploy stable/etcd-operator chart, release name: `pancake-master`
- other charts that normally have etcd-operator as a dependency are installed with `helm install chart-name --existing-dependency="etcd-operator=pancake-master`
All releases installed using this approach would use `pancake-master` as their etcd storage.

Implementation details:
- rendering chart templates would disregard etcd-operator specific k8s manifests and include current state of `pancake-master` release with annotation that it's external release and shouldn't be upgraded/rolled back/deleted when these operations are run on charts using `pancake-master` as dependency.

**Comment by technosophos** [comment]
This is a really interesting idea, and does seem like it would be backward compatible (non-breaking). I think this would be a great way to compose multiple releases.

You might need to accommodate the case where you want to replace a dependency like:

```
mychart/charts/subchart/charts/subsubchart
```

So you might have to do something like `--existing-dependency="mychart/charts/subchart/charts/subsubchart=..."` Or maybe even an abbereviation, like "subchart/subsubchart=..."`, since that is unambiguous.

This may push chart devs to focus more on using services and env vars to pass configuration information around (rather than relying on calling the same template functions all over the place). But I think that is actually a good practice.

**Comment by navin-rajan** [comment]
Hi  
is this option will be available in future release ?
helm install chart-name --existing-dependency....

We have a similar use case where we have application services using platform services in k8s. Therefore application services are dependent on platform services. When an application is deployed it should start using existing or already deployed dependency or if the dependency is not deployed it shall deploy.

Kindly provide your inputs or thoughts around this requirement.

**Comment by bacongobbler** [comment]
@navin-rajan this hasn't been slated for a milestone or discussed in the dev channel. If you feel like writing up a design document or a PR for this, go nuts! :)
