### ISSUE TITLE
Proposal: Add template action delimiters parameter

### ISSUE THREAD

**Issue by dhoeld** [kubernetes/helm#2931]
# Problem
We want to template some files e.x. Prometheus Alertmanager alert rules with helm. When trying to do do this, there is an issue:
The templating language used by the Prometheus Alertmanager is go-templating. Therefore there is a clash in the use of the standard template delimiters {{ }} when templating alert rules.

# Questions
From my knowledge level there are two possibilities:

- escaping the template delimiters within the alert rules with ``{{ `{{ ALERT_RULE_VARIABLE `}} }}`` which seems quite hacky
- extending the render package of helm to support using other delimiters than the default ones. E.x. `[[ ALERT_RULE_VARIABLE ]]` instead of `{{ ALERT_RULE_VARIABLE }}`

Is there any (maybe undocumented) way of using another set of delimiters?

If not and there are no arguments against extending the rendering package, I maybe would give it a try and add a PR.

**Comment by bacongobbler** [comment]
pkg text/template in Go does allow a way to [change the delimiters](https://golang.org/pkg/text/template/#Template.Delims). It's not baked into helm, but one could in theory come up with a PR to change the delimiters.

The concern would come down to chart compatibility, though. If one chart uses one set of delimiters and another uses a different delimiter, both charts are incompatible with each other once you start to add each together as dependencies or otherwise.

**Comment by bacongobbler** [comment]
related discussion: #856
