### ISSUE TITLE
"helm dependency update" does not delete dependencies already contained in charts folder

### ISSUE THREAD

**Issue by abinet** [kubernetes/helm#2936]
I cannot decide is it bug or feature but it still the case:

- add some dependency `subchart:1.0.0` to requirements.yaml
- do `helm dependency update .`
-  file subchart-1.0.0.tgz appears in chart folder
- remove depdendency from requirements.yaml
- do `helm dependency update .`
- file subchart-1.0.0.tgz is still in chart folder despite of message "Deleting outdated charts"

Helm v.2.6.1

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/issues/2830

**Comment by clhodapp** [comment]
This is very much not a feature. The problem here is that Helm does not differentiate between manually-managed chart dependencies and automatic ones. This is a problem because one would expect automatically-managed dependencies to go away on the next `helm dependency build` when they are removed from `Chart.yaml` but one would _not_ expect `helm dependency build` to remove subcharts that one put there by hand (else #2830 would be back). Ideally, helm would keep the two kinds of dependencies in separate directories so they could easily be told apart but... that seems deeply breaking. It seems to me like a simple heuristic that would mostly work would be to treat folders as subcharts (leave them alone) but tgz files as automatic dependencies (clean them up)

**Comment by duncangrist** [comment]
Could we add an option to delete `*.tgz` files if they're not present in `Chart.yaml`?

e.g.
```
helm dependency update --prune . 
```

or maybe a different action perhaps?
```
helm dependency sync .
```

**Comment by red8888** [comment]
Where is the official documentation for _removing_ a dependency? This behavior  is frustrating and poorly documented.

[The docs](https://helm.sh/docs/helm/helm_dependency_update/) only say `an update command will not remove charts unless they are (a) present in the Chart.yaml file, but (b) at the wrong version`

Before this is fixed the docs could at least be obvious about this: "To remove a dependency you must remove it from your Chart.yaml AND delete the chart from the "charts" folder"

**Comment by h0jeZvgoxFepBQ2C** [comment]
Stumbled over this as well... Strange workflow right now with this.
