### ISSUE TITLE
Helm Chart: auto string-ize integers

### ISSUE THREAD

**Issue by snavien** [kubernetes/helm#2969]
While trying to install my helm chart, I have received this error:
`[debug] Created tunnel using local port: '63163'
[debug] SERVER: "localhost:63163"
[debug] Original chart version: ""
[debug] CHART PATH: /hermes-1.1.4-dev19.tgz
Error: release hermes-deploy failed: DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: [pos 626]: json: expect char '"' but got char '9'`

Not only did that not tell me what the issue was, it didn't tell me where it was. Other issues stating to just put double quotes around those variables didn't work so I had to specifically put quotes around the template variable in the chart template and not the values:

"{{ .Values.group.name }}" 

instead of in the values section putting quotes on that value.

It'd be nice if helm automatically string-ized integers when rendering templates in a k8s deployment!

**Comment by bacongobbler** [comment]
This is something I know we definitely documented in Chart Best Practices. When developing charts, it is best to [make the type very explicit](https://docs.helm.sh/chart_best_practices/#make-types-clear), as YAML is not very clear on type as opposed to other markup languages like JSON or TOML.

I agree though that the debug information you received from Helm is less helpful than it should be. The problem is that this error comes directly from kubernetes, so it would need to be solved upstream in a sense. This error occurs after we have run the chart through the template engine and are now submitting the manifests as JSON, so at that point we have lost any information about which file or where the template came from.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
