### ISSUE TITLE
expose port 44135 in tiller deployment

### ISSUE THREAD

**Issue by ipedrazas** [kubernetes/helm#2985]
Right now the `tiller` deployment only exposes port `44134` (as you can see [here](https://github.com/kubernetes/helm/blob/master/cmd/helm/installer/install.go#L141)).

Tiller exposes probes and metrics in `44135`. Because tiller doesn't expose that port and does not contain any Prometheus annotations, making Prometheus scrape tiller is a bit more complex.

By adding port `44135` we can automatically make Prometheus scrape tiller and fetch those metrics.

**Comment by bacongobbler** [comment]
I'm certain this was due to security concerns over exposing metrics to the entire cluster and turning this on by default for all users, but I wasn't present at the time when this decision was made. There must have been a specific reason why this wasn't enabled by default.

#2171 has the original discussion/design around this feature. Specifically https://github.com/kubernetes/helm/pull/2171#issuecomment-293773120 mentions disabling this feature by default, so I assume that because it wasn't disabled by default, it was just never exposed and users would have to roll their own services that expose this port at their own risk.

**Comment by ipedrazas** [comment]
Metrics are exposed by default, but the port is not defined. I would understand metrics not being enabled by default and to have a flag to enable/disable this feature, as the comments in #2171 say. But that's not the case.

Right now, we expose the metrics but in order for Prometheus to scrape them, we have to manually modify the tiller manifest. I'm not very keen on this way of working since it breaks the `upgrade` path of Helm.

I understand the security concerns, but right now, the vector attack is there. We should either disable it or make it clear and public.

What I would do is to add the port definition into the yaml file. As you can see, [the fix is pretty straightforward](https://github.com/ipedrazas/helm/commit/4933af3546d93c854e7ac8201d3bd3c64a7e05b3). Less experienced users might not realise that tiller is using that port and there are metrics exposed. 

I'm happy to create a new issue to define and track the work related to adding a new flag to enable/disable metrics, but as it is right now, it's not very clear.

**Comment by ipedrazas** [comment]
any ideas/suggestions? /cc @lachie83 @prydonius

**Comment by adamreese** [comment]
@ipedrazas can you open a PR for your fix.  We can revisit a disabling flag later.

Thanks!
