### ISSUE TITLE
Use of `dict` leads to rendering errors

### ISSUE THREAD

**Issue by jaytaylor** [kubernetes/helm#3095]
Passing a dict into a named helm `include` or `template` fails.

Failure example:

```mustache
{{- define "exploder" }}
{{ include "takes_a_map" dict "A" "eh" "B" "bee" }}
{{- end }}

{{- define "takes_a_map" }}
A: {{ .A }}
B: {{ .B }}
{{- end }}
```
Produces the following render error:

```
wrong number of args for include: want 2 got 6
```

However, passing a dict via pipe works just fine.

Successful example:

```mustache
{{- define "works_fine" }}
{{ dict "A" "eh" "B" "bee" | include "takes_a_map" }}
{{- end }}

{{- define "takes_a_map" }}
A: {{ .A }}
B: {{ .B }}
{{- end }}
```

## Failing test case

If you paste this test into pkg/engine.go:
```go
func TestRenderInternalsDicts(t *testing.T) {
	// Test the internals of the rendering tool.
	e := New()

	vals := chartutil.Values{"Name": "one", "Value": "two"}
	tpls := map[string]renderable{
		"hello": {tpl: `hello .A={{.A}} .B={{.B}}`, vals: chartutil.Values{"A": "1", "B": "2"}},
		"four":  {tpl: `{{include "hello" dict "A" "1" "B" "2"}}`, vals: chartutil.Values{}},
		"five":  {tpl: `{{dict "A" "1" "B" "2" | include "hello"}}`, vals: chartutil.Values{}},
	}

	if _, err := e.render(tpls); err != nil {
		t.Fatalf("Failed template rendering: %s", err)
	}
}
```

Running the test yields the following output:

```bash
~/go/src/k8s.io/helm/pkg/engine$ go test -run TestRenderInternals -v ./... ; echo $?
=== RUN   TestRenderInternalsDicts
--- FAIL: TestRenderInternalsDicts (0.00s)
	engine_test.go:162: Failed template rendering: render error in "four": template: four:1:2: executing "four" at <include>: wrong number of args for include: want 2 got 6
FAIL
exit status 1
FAIL	k8s.io/helm/pkg/engine	0.009s
1
```

**Comment by bacongobbler** [comment]
This is actually how text/template works, though I understand it can be confusing at first. A template pipeline takes every argument as an argument to the function. In your case, `dict` was passed as an argument to `include` instead of the output of `dict` being the argument supplied, which is how the pipe works. If you want the output of `dict` to be the input of `include`, you'll want to wrap the arguments in parentheses. Think back to Order of Operations in high school :)

```
{{- define "exploder" }}
{{ include "takes_a_map" (dict "A" "eh" "B" "bee") }}
{{- end }}
```

pkg text/template is finicky at times with parsing function arguments. Wrapping arguments in parentheses helps in situations like this. :)

As far as to why the second example works as intended, it's because `dict` is in its own pipeline, so its arguments will be parsed in the proper order.

So, in terms of Order of Operations for text/template, it's

1. parentheses (`()`)
1. the pipe (`|`)
1. the template (`{{}}`)

Afterwards, everything is an argument to the function.

Does that help make sense?

**Comment by jaytaylor** [comment]
Ah!  I thought I had tried wrapping it in parenthesis yesterday, however I just tested now and it works!

Thank you for your help @bacongobbler!!!  And for helm, it's super cool and useful imho.
