### ISSUE TITLE
Daemonset and Pod removal ordering

### ISSUE THREAD

**Issue by hobti01** [kubernetes/helm#3136]
I think this is a small change but shouldn't Daemonsets be removed before Pods so that the Pods are not re-created?  The current code removes Pods first: 
https://github.com/kubernetes/helm/blob/29c3b5276f0290d21d43ef45ad0230e45b460b27/pkg/tiller/kind_sorter.go#L70-L71

**Comment by bacongobbler** [comment]
This is intentional as this is in relation to the helm chart's templates, not to all the pods deployed by cascading resources (deployments, daemonsets, statefulsets etc). Pods created by DaemonSets are uninstalled when the DaemonSet is uninstalled, but not when "Pods" are being uninstalled. We only uninstall Pods that were explicit Pod templates in the helm chart.

Does that help make sense, or are you seeing differing behaviour?

**Comment by hobti01** [comment]
That's a clear explanation, thank you.
