### ISSUE TITLE
Question: How to contribute ?

### ISSUE THREAD

**Issue by titilambert** [kubernetes/helm#314]
Hello !
I'm opening this issue because I'm really interested by this project and I have some questions:
 - Do you have any roadmap ? How can I add some inputs for the roadmap ?
 - How can I contribute ? development/doc ?
 - Which feature can I develop ?
 - Do you have an channel on IRC/slack ?

Thanks for your responses !

**Comment by michelleN** [comment]
Hey @titilambert. It's really nice to hear that you're interested in this project! 

1. We do not currently have an official roadmap yet but there is a workflow document in PR #298 that might be helpful. 
2. We're putting together guidelines for contributing. I've opened up issue #315 to track this. Until then, we have a rough [getting started guide] (https://github.com/kubernetes/deployment-manager/blob/master/docs/usage_docs/getting-started-guide.md). 
3. I would suggest checking out the doc in PR #298 and our open issue queue. Feel free to question, comment, provide feedback on any of the features/slices of work. That would be a great place to get started. 
4. You can find us in the Helm channel of the Kubernetes organization [here](https://kubernetes.slack.com/messages/helm/)

Thanks for your support.

**Comment by jackgr** [comment]
Welcome to the project, @titilambert!

There are contribution guidelines in the [README.md](https://github.com/kubernetes/deployment-manager#contributing). There's additional detail in [CONTRIBUTING.md](https://github.com/kubernetes/deployment-manager/blob/master/CONTRIBUTING.md). The CLA is the most important thing, since we can't accept contributions without it.

In the absence of an official roadmap, please see our open issues, in addition to the documents that @michelleN referenced above, and feel free to add issues for changes, new features and/or bugs. :0)

**Comment by titilambert** [comment]
@michelleN @jackgr Thanks for you replies !
Reading the getting started guide, I see that all links related to Helm see broken (or maybe not yet created)
Is Helm projects will be in kubernetes github namespace ?
Will Helm and Deployment-manager be merged ?

**Comment by pradeepto** [comment]
@titilambert dm and helm have merged. The new repository is now re-named to helm.

**Comment by jackgr** [comment]
Closing this issue, given the contributing guidelines cited above by @michelleN. Please reopen if it's still an issue.

**Comment by titilambert** [comment]
Thanks !
