### ISSUE TITLE
Error: UPGRADE FAILED: transport is closing Connection refused

### ISSUE THREAD

**Issue by wallrj** [kubernetes/helm#3140]
In https://github.com/jetstack/navigator/issues/133 our automated e2e tests failed because `helm upgrade` failed with the following error:

```
I1114 23:31:07.932] [debug] Created tunnel using local port: '40930'
I1114 23:31:07.932] 
I1114 23:31:07.932] [debug] SERVER: "localhost:40930"
I1114 23:31:07.932] 
W1114 23:31:08.246] E1114 23:31:08.245926    6980 portforward.go:331] an error occurred forwarding 40930 -> 44134: error forwarding port 44134 to pod f5bdd89f9da5116f3a6ccebb29e1c4448f06027bac37fb7029673d3f5bad1c77, uid : exit status 1: 2017/11/14 23:31:06 socat[10443.140469232314112] E connect(5, AF=2 127.0.0.1:44134, 16): Connection refused
W1114 23:31:08.247] Error: UPGRADE FAILED: transport is closing
```

The error message is not very clear to me. 
This is an intermittent error and maybe `helm` ought to retry before failing.

The full logs are here:
 * https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_navigator/130/navigator-e2e-v1-8/75/

Environment:
 * helm-v2.6.1-linux-amd64
 * minikube v0.23.0/minikube-linux-amd64
 * kubernetes v1.8.3

**Comment by bacongobbler** [comment]
Hmm, so a connection refused error from socat when forwarding ports would be an indicator that kube-proxy is starting to fail, possibly due to exhausted infrastructure. Because the error comes straight from kube-proxy in the form of `socat` failing, there's not much we can do to improve the error message, but a PR upstream to improve the error message would probably improve the situation!

I would check your kubernetes cluster and see why kube-proxy is starting to flap. :)

**Comment by wallrj** [comment]
@bacongobbler Thanks for your reply. We've scaled up our test infrastructure as you suggested.
