### ISSUE TITLE
tiller -authentication and authorization approach 

### ISSUE THREAD

**Issue by shikhasriva** [kubernetes/helm#3158]
As a user with roles, I should be able to install releases from the helm UI  page only if I have the proper authority to do so. By default as a view only user, I shouldn't be able to install/uninstall/upgrade/rollback any releases.
# Tiller Changes

Tiller needs to be modified to prevent users from installing/upgrading/rollback/uninstalling anything if the user isn't authorized.

    Adding authorization checks for all destructive methods

We are making updates to tiller in order to secure tiller by itself. Tiller is not secure by default and could be exploited to install things due to it using elevated privileges and not the user credentials. Tiller should accept the user's credentials and use them to authorize the user to perform destructive tasks.

We have incorporated this PR into the change since it was closed and never merged
https://github.com/kubernetes/helm/issues/1918

This is the proposal for securing tiller that was never completed:
https://github.com/kubernetes/helm/issues/1918

Using the PR mentioned above, the tiller will be secure by default from unauthenticated requests. However, this doesn't check for authorization of users to create/delete/update resources. I'm adding code to handle the authorization of users.
## Authentication

The PR addresses users authenticating before being able to interact with tiller.
When a new call comes to tiller an interceptor is added to the request which handles the authentication:

    Streaming and unary grpc server calls are intercepted and the authenticate function is added to these calls
        If the authenticate function returns as system:unauthenticated, the connection is dropped for the user
        If theauthenticate function returns as system:authenticated, calls to the services that tiller provides can proceed with additional information added to the context:
        users can authenticate with certificates, bearer tokens, and basic authentication
            Bearer tokens and basic auth are passed in the authorization header of the metadata object in the grpc call to the server.
            The certificate is sent over as part of the credentials of the grpc call.

## Authorization

Authorization happens after the user is authenticated, and is trying to make a destructive call. As with REST calls, we are assuming the user can view resources but cannot make changes to resources:

    When a destructive method is called create/update/rollback/uninstall we send a request to the k8s api and check if the user is authorized to perform that task
        We are using the SubjectAccessReview API to perform the access check.
            We are passing over the Username, Namespace, Resourcetype, and Verb to the k8s api for authorization checking
            The returned value will let us know if the user has access to perform the verb on the given resourcetype in the specified namespace.
            If the user is unauthorized, the action is stopped
            if the user is authorized, the action continues and the resource is modified/added/uninstalled

API information links:

    https://kubernetes.io/docs/admin/authorization/
    https://kubernetes.io/docs/api-reference/v1.8/#subjectaccessreview-v1-authorization

copy @ericabr @technosophos @tamalsaha @seh

**Comment by technosophos** [comment]
My personal recommendation would be to use the gRPC TLS authentication that is already built-in. You can supply client certificates to each Helm client, and Tiller with verify those with its CA.

Authorization, in that situation, is a separate issue. You might still have to inject some identity data into the gRPC metadata, or you could extract it from the client's SSL certificate. The later is,  f course, easier (since the data is already there), but would require more diligence in how you do the certificate generation.

The SAR should be a fine solution from there.

**Comment by bacongobbler** [comment]
For anyone that missed the dev call yesterday, here's the important bits on this proposal (including addressing gRPC TLS): https://www.youtube.com/watch?v=PBvhFbaR-bI&t=9m5s

**Comment by ericabr** [comment]
Following

**Comment by shikhasriva** [comment]
@ericabr , can you update with the modifications we talked about

**Comment by ericabr** [comment]
So, we will be moving to helm 2.7 because we are now using kubernetes 1.8.3
The changes we will be making will only be to pull the subject from the client certificate to obtain the username, store it in the context, and authorize the user from there.

We won't be making changes to the cli since the certificate can already be passed currently and can be verified when it is passed by tiller.

We will still need to pass that subject and organization to the k8s api for authorization and that can be done using the SAR:
- I've added a method to check for authorization that creates a SubjectAccessReview from the Username, Groups, Namespace, Verb, and Resource. That determines if the user has authority to perform the action. 
- **When should access fail** When one installs a helm chart, they are not simply trying to install a deployment. There could be many resources tied to the helm chart that need to be created. I propose I should test all of the resources in the helm chart to see if the user has access to do so, if any one of them fails, they don't have the authority to install/delete/update/rollback.

I assume if one resource is denied to install the chart should fail, since if you can't deploy part of the chart, the chart won't work properly.

We will need users to know when they create their helm client certificates, the subject needs to be added so we can authorize the user.

**Are there any reasons in which TLS is used to authenticate but we don't need to authorize the user?**
