### ISSUE TITLE
Ordering when using custom API definitions

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3289]
Hi, 
I'm creating a helm chart which has some dependency issues and i'm trying to work around using lots of `if` logic.

The issue is because some of the resources depend on some api extensions to exist first:
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
```

If tiller tries to run the resources which depend on this first (which it does), we get errors like this:
```
[tiller] 2017/12/21 16:55:49 failed install prepare step: [unable to recognize "": no matches for custom.api.definition/, Kind=attributemanifest, unable to recognize "": no matches for config.istio.io
```

This could be solved in one of two ways for me:

  - Chart dependencies being processed **before** the parent
  - Tiller doing custom api extensions first

I'm open to other suggestions, but this is a bit of a problem for me!

**Comment by Stono** [comment]
Moving up https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter.go#L39 to be done first would resolve this too.

**Comment by bacongobbler** [comment]
related: https://github.com/kubernetes/helm/issues/2994

**Comment by jascott1** [comment]
@Stono FYI moving CRD up in the order will not fix this issue as far as I can tell. You can test this by creating and chart with a CRD and CronJob as per [Kubernetes docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/) and attempting to install the chart. Although CronJob is after CRD in the install order, the release will still fail because the validation for all the manifests occurs before anything is installed and validation fails because the CRD has not been installed when CronJon is encountered. 

It will take some refactoring to accomplish a fix as currently its a 1. validate everything 2. install everything process.

**Comment by Stono** [comment]
Ah ok, thank you for confirming the issue.

:-(

**Comment by jascott1** [comment]
@Stono Im going to close this as we are converging the __many__ similar CRD issues on #2994 that @bacongobbler linked. Please come participate on that issue. Thanks!
