### ISSUE TITLE
installing helm in a designated namespace does not start the pod

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/helm#3304]
Hi,

On a kubernetes cluster create a service account name tiller-test and i have a namespace named test.
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: tiller-test
    namespace: test

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: tiller-services-test-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller-test
  namespace: test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

i then tried to do helm init as follows to install tiller in the namespace test
helm init --service-account tiller-test --tiller-namespace=test

$HELM_HOME has been configured at /Users/anitakumar/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!

if i do 
kubectl -n test get deployments

i get one deployment name tiller-deploy running but

kubectl -n test get pods
i dont see a pod created

Now if i just run
helm init

it works , i get a pod in a created in the kube-system namespace and a deployment as well

**Comment by bacongobbler** [comment]
Hey! Can you check the event logs in the namespace and see why pods cannot be scheduled?

**Comment by anitakumar** [comment]
Thanks . this helped to check the logs 
kubectl get events -w

my service account name was wrong and now its working

**Comment by a-barbieri** [comment]
I had the same issue but `kubectl get events -w` wasn't really helping me out.

To find out what the issue was I looked into the tiller _deployment_ found out that no _replica_ was created and debugged the _replicaset_.

The iter was the following: 

### 1. Find Tiller _deployment_

```
kubectl get deployment --all-namespaces
```

```
NAMESPACE          NAME                         DESIRED   CURRENT   READY     AGE
kube-system        cilium-operator-6d4dcbf8c7   1         1         1         14h
kube-system        coredns-5d668bd598           2         2         2         22d
my-namespace       tiller-deploy-7f4b6cf8f4     1         0         0         1h
```

There it is. I installed Tiller with `helm init --service-account tiller --tiller-namespace my-namespace` so the Tiller deployment has been correctly setup into `my-namespace`.

And there's an important thing as well! This shows that `my-namespace/tiller-deploy-7f4b6cf8f4` is `DESIRED` but there is 0 pods `READY`.

### 2. Find why _pod_ isn't ready

```
kubectl get deployment --namespace my-namespace tiller-deploy-7f4b6cf8f4
```

```
...

Conditions:
  Type             Status  Reason
  ----             ------  ------
  Available        True    MinimumReplicasAvailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     tiller-deploy-7f4b6cf8f4 (0/1 replicas created)
Events:            <none>
```

As you see no _event_ has been thrown but _deployment_ failed to create _replica_.

### 3. Find Tiller _replicaset_

```
kubectl get replicaset --namespace my-namespace 
```

```
NAMESPACE          NAME                         DESIRED   CURRENT   READY     AGE
my-namespace       tiller-deploy-7f4b6cf8f4     1         0         0         14h
```

Again we see no replicaset is ready.

### 4. Find why _replicaset_ isn't ready

```
kubectl describe replicaset --namespace my-namespace tiller-deploy-7f4b6cf8f4
```

```
...

Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  4m (x104 over 14h)  replicaset-controller  Error creating: pods "tiller-deploy-7f4b6cf8f4-" is forbidden: error looking up service account my-namespace/tiller: serviceaccount "tiller" not found
```

There it goes. Read the event message and you will find why your replica hasn't been created.

```
Error creating: pods "tiller-deploy-7f4b6cf8f4-" is forbidden: error looking up service account my-namespace/tiller: serviceaccount "tiller" not found
```

### 5. Update your config

My config had a mistake in `RoleBinding` settings:

```
...

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: some-namespace
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
```
