### ISSUE TITLE
Helm does not de-provisioning pvc generated through StatefulSets' dynamic storage provisioning

### ISSUE THREAD

**Issue by gmflau** [kubernetes/helm#3313]
I was able to use "helm install ..." to deploy my StatefulSets with dynamic volumne provisioning properly.  However, "helm delete ..." does not decommission (remove) the pvc generated through my StatefulSets' dynamic volume provisioning.

**Comment by technosophos** [comment]
This was by design. Helm will not manage things that were created by things other than Helm, because Helm is not "authoritative" about those. That is, Helm does not have information about the user's intent when it comes to things that were created by other things. @viglesiasce has some additional insight on why we are really careful when destroying PVCs/PVs in particular, but it boils down to the fact that a lot of users expect that PVCs will remain when the services that use them disappear.
