### ISSUE TITLE
search command returns no error on index search failure

### ISSUE THREAD

**Issue by adshmh** [kubernetes/helm#3687]
It seems the search command does not return an error

https://github.com/kubernetes/helm/blob/b335bfdabf03cc6aaea9bd3e46a5fc63c932c1dd/cmd/helm/search.go#L84-L87

The tests for the search command seem to miss this (they do not use `runReleaseCases` for testing) as the tests won't fail if there are no errors when an error is expected:

https://github.com/kubernetes/helm/blob/b335bfdabf03cc6aaea9bd3e46a5fc63c932c1dd/cmd/helm/search_test.go#L104-L108

**Comment by bacongobbler** [comment]
Hmm, I think this might actually be intentional. Searching for something and coming up with "no results" is a valid end state in my mind.

@michelleN I noticed your name under `git blame` for introducing this feature. Do you know if we intended this behaviour? Perhaps logging the error as a warning would be sufficient?

**Comment by bacongobbler** [comment]
nvm, after looking at how [search works](https://github.com/kubernetes/helm/blob/9bd03fd5713572a2b7f67a1e0f202d41800346a9/cmd/helm/search/search.go#L116-L121) I don't think it'll raise an error if no matches were found.
