### ISSUE TITLE
Valid `if pipeline` fails to render in template

### ISSUE THREAD

**Issue by rustycl0ck** [kubernetes/helm#3708]
Conditional check of `if`-
1. succeeds if parent exists and child-key exists
2. succeeds if parent exists but child-key does not exist
3. **[BUG]** fails to parse when parent does not exist

contents of `myChart/templates/test-configmap.yaml` :
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "myChart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "myChart.fullname" . }}
data:
  myDevice: phone


# ERROR producing code:
# Provide a default value for my variable if not defined in the expected location
{{- if not (and .Values.device .Values.device.type) }}
  myDeviceType: mobile
{{- end }}
```

contents of `values.yaml` (case 1 - does not throw any error) :
```
device:
  price: high
  type: telephone
```

contents of `values.yaml` (case 2 - does not throw any error) :
```
device:
  price: high
```

contents of `values.yaml` (case 3 - throws rendering error if parent not defined) :
```
# device:
#   price: high
```

**Comment by jascott1** [comment]
Hi @ravi-kumar 

This is a limitation of go-template. If there was a more elegant solution it would probably need to be added to the supporting [sprig templating library](https://github.com/Masterminds/sprig)

Here is a workaround:

```
myDeviceType:  {{- if .Values.device }}  {{- if .Values.device.type  }} {{ .Values.device.type }} {{- end}} {{else}} "mobile" {{- end }}
```

Im removing the `bug` label since this isn't going to be fixed in Helm although you might take the discussion to the Sprig issue queue.
