### ISSUE TITLE
helm search regexp shortcoming

### ISSUE THREAD

**Issue by das-super** [kubernetes/helm#3890]
Hi. Firstly, thanks for the awesome project - love it. I have a minor quibble with the current behaviour exhibited when using regular expressions with `helm search`. My aim is to precisely control the result set returned from a search; it seems that expressions with anchors do not currently return the result set I would expect. For example, when constrained by anchors, I expect the following regexp to return a single result: the redis chart from the stable repo:
```
$ helm search --regexp '^stable/redis$'
No results found
```
Loosen things up:
```
$ helm search --regexp '^.*stable/redis.*$'
NAME            CHART VERSION   APP VERSION     DESCRIPTION                                       
stable/redis    1.2.2           4.0.9           Open source, advanced key-value store. It is of...
stable/redis-ha 2.1.1           4.0.8-r0        Highly available Redis cluster with multiple se...
```
Current workaround:
```
$ helm search --regexp 'stable/redis[^-]'
NAME            CHART VERSION   APP VERSION     DESCRIPTION                                       
stable/redis    1.2.2           4.0.9           Open source, advanced key-value store. It is of...
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ kops version
Version 1.8.1 (git-94ef202)
```

**Comment by michelleN** [comment]
Thanks for bringing this up @das-super. It sparked an interesting conversation. The `--regexp` flag is working here as intended. What gets compared to the expression supplied is actually a concatenation of multiple fields from the `Chart.yaml` file ( the name of the chart, description, keywords, etc) each of which are separated with `\v` (vertical tab) not just the `NAME` field that we see in the output of `helm search`. 

`helm search` was implemented this way in order to search using keywords like `database`, `key-value store` or other keywords in the metadata that might be interesting other than the actual chart name itself. It looks like the work around you described is the right way to return the specific chart but if there were other charts with "stable/redis" in the description or keywords, they would also be returned via `helm search --regexp 'stable/redis[^-]'`.  To specifically look for charts that are named `stable/redis`, try searching using vertical tabs `\v` like this: `helm search --regexp '\vstable/redis\v'`

Now looking at your issue, @bacongobbler and I have been chatting about how to make this experience more intuitive. We cannot however change the current behavior at this time because it would present a backwards incompatibility issue. We can put this on the table for helm v3 as a discussion point.

**Comment by das-super** [comment]
Hi, thanks for following-up on this and for the improved workaround for my case.

Cheers!

**Comment by vadasambar** [comment]
Can we add a `--regexp-whole-word` field like @ian-howell suggests here (it's not present in helm 3)
https://github.com/helm/helm/issues/3927#issuecomment-445026515
> Suggestion: why not add a new flag --regexp-whole-word which simply adds the vertical tabs in the search? This would blackbox the implementation. Maybe an idea for Helm 3?

I think the help message in the command helps but having a field like `--regexp-whole-word` might be better because it would work the way you expect `--regex` to work, without breaking the backward compatibility of `--regex` and you wouldn't have to keep wrapping your regex with `\v \v` to make regex work the you would expect it to work. 

I can spend some time on this if required.

**Comment by scubbo** [comment]
I encountered this issue while looking for a way to simply list all charts from a given repo. I naively tried `helm search repo  -r '^<name-of-repo>./*'` which, of course, didn't work. This was a helpful pointer - but please consider this a request for a flag that allows you to specifically constrain the search to a particular repo!
