### ISSUE TITLE
Support new 1.2 types

### ISSUE THREAD

**Issue by therc** [kubernetes/helm#413]
I'm just looking at the documentation, i.e. I haven't run anything yet, but I see that so far Helm only refers to 1.0/1.1 stable objects (RCs and so on). We're already using —were guinea pigs for— the new shiny stuff in 1.2: Jobs, ReplicaSets, DaemonSets and Deployments. Are they going to be supported? Then there's the question of the relationship between Deployments and Helm's deployment manager. Naming is tough. :-)

For that matter, it's not clear if Helm dabbles with any of the types directly or if it's just an abstraction above kubectl or the API; in that case, there's no technical obstacle and it'd be a matter of revamping the documentation.

**Comment by jackgr** [comment]
Currently, we don't make explicit use of any type specific knowledge, except in the case of Secret, since need to read them. All other k8s objects pass through untyped.

That said, we're thinking about a change where we'd recognize k8s kinds, which currently share the type namespace with chart names, as part of a move to explicit typing. Currently, we simply assume that if the chart name is not a URI, then it must be a k8s kind. 

With explicit typing, we'd make the chart name `kubernetes:<kind>` instead of just `kind`. This change would also have the benefit of allowing us to support other kinds of primitives, including Configurable Resource Types (CRTs), as they're called in GCP Deployment Manager. A CRT is a type that identifies an endpoint and provides a Swagger document for it. When we encounter one of those, we do CRUD on the endpoint.

Supporting CRTs would let us interact with any service that offers a RESTful collection of resources, not just the k8s api server, which we currently call through kubectl in a container. The k8s api server would then become just another service that we can talk to for CRUD operations on resources in the cluster.

**Comment by therc** [comment]
That's very helpful, thanks. Are there any plans to support ConfigMaps, e.g. consuming them in templates? It would be nice to have a standard place for things such as the cluster name or, say, public TLS settings, the default redundancy, etc. They're  the non-secret Secrets, after all.

**Comment by jackgr** [comment]
That's a really interesting question. Came up in the SIG config meeting yesterday. No plans at the moment, but would be a killer feature. Please feel free to file an issue specifically for it.

**Comment by technosophos** [comment]
We're planning on storing release configuration inside of ConfigMaps, but not consuming arbitrary config maps as sources for template variables.
