### ISSUE TITLE
Linking external files to the values.yaml

### ISSUE THREAD

**Issue by KavinduZoysa** [kubernetes/helm#4131]
Hi,

Currently, I am working on deploying MySQL using helm package. In that scenario, I want to add some custom configuration files and initialization SQL file. According to the details which are provided on GitHub, we have to paste the content of all the configuration files and all the initialization SQL files into the values.yaml file. But in my case, I have a very big initialization SQL file and it is hard to paste it on the values.yaml file. 

Therefore, is there a way to link an external file or file path to the values.yaml or is there some other solution for this issue? 
Kindly appreciated your inputs on this issue.

Thank you,
Kavindu

**Comment by bacongobbler** [comment]
https://docs.helm.sh/chart_template_guide/#accessing-files-inside-templates? :)

**Comment by KavinduZoysa** [comment]
Closing this issue since we are discussing the issue [here](https://lists.cncf.io/g/cncf-kubernetes-helm/topic/linking_external_files_to_the/20396688?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,20396688).

**Comment by aksakalli** [comment]
The issue mentioned in the previous comment has moved from `cncf-kubernetes` to `cncf-helm`: here is [the new issue link](https://lists.cncf.io/g/cncf-helm/topic/linking_external_files_to_the/20396688).

You can't use Helm templating in `values.yaml`, but there is [a new option](https://github.com/helm/helm/issues/3276) named [--set-file](https://helm.sh/docs/helm/helm_install/#options) to pass an external file.

**Comment by atejano** [comment]
`--set-file` flag does not work for binary files. My issue is I need to to pass a truststore file that is in binary format. The truststore file I cannot embed in docker image since the truststore file can only provided during deployment since the files can vary per target environment

**Comment by ebuildy** [comment]
BTW with the adoption of gitops (aka declarative instead of imperative) CLI ``--set-file`` cannot be used.

Will be a killer feature to be able to do that inside a ``values.yaml`` file. I know this is not supported by YAML standard, but this is possible to declare custom tags such as ``!include`` (see https://stackoverflow.com/questions/63567945/how-to-extend-go-yaml-to-support-custom-tags ).

Or what about a way to use the Helm template engine for ``values.yaml`` as well? In our company, we use ``ansible`` to generate the ``values.yaml`` file from jinja template.
