### ISSUE TITLE
Crash Loop Back-Off with stable/wordpress, stable/mongo .. 

### ISSUE THREAD

**Issue by manojRy** [kubernetes/helm#4209]
Hello, 
I am using minishift and trying to deploy images using helm charts. So far i have tested with 3 helm charts on minishift 
1) helm install stable/mysql
2) helm install stable/mongodb
3) helm install stable/wordpress

Neither of them ran successfully, they ended up being in a Crash Loop Back-Off stage. 
my helm version is 
`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`

output logs from worpress container is 
`ERROR Cannot find any module matching the provided specification 'apache'`
output logs from mysql container is
`
INFO  ==> Starting mongodb...
sed: can't read /opt/bitnami/mongodb/conf/mongodb.conf: No such file or directory
error: failed switching to "mongo": unable to find user mongo: no matching entries in passwd file
`

**Comment by bacongobbler** [comment]
Hey @manojRy, since this looks like an actual issue with the charts themselves, we ask users to report these issues directly to the community charts repo instead of Helm. That way the maintainers of those charts only have to triage one issue queue rather than two. Please re-open this ticket over at https://github.com/kubernetes/charts. Thanks!
