### ISSUE TITLE
Remove `helm deploy` command, make `deploy` and alias of `deployment`, add `helm deploy install`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#555]
Because it is confusing to have `helm deploy` and `helm deployment *`, we should just change the former to a subcommand under the later.

- `helm deploy` should become `helm deployment install`
- Alias `helm deploy` to `helm deployment`

**Comment by michelleN** [comment]
I'm cool with this but an alternative might be `helm chart install [chart.tgz] [values] --name fishy-livestock` which then creates a deployment named fishy-livestock

?

**Comment by technosophos** [comment]
I'd be fine with that, too.

**Comment by michelleN** [comment]
yeah that's how I feel about it too.

On the note of deployment name. I passed in a name in that command but you should also be able to generate a random name (like in the original developer-workflows doc) if a name is not passed in. A deployment name doesn't seem like something the user HAS to think about, so let's lessen the burden on the end user as much as we can?

so, this would work:
```
helm install [chart-name] [values.yaml]
```
and output
```
Congratulations, you successfully created a deployment called fishy-livestock using the 
chart-name chart and values.yaml.
Get more information on your deployment by using the helm deployment commands using the deployment name: fishy-livestock.
For example:
$ helm deployment show fishy-livestock
```

**Comment by runseb** [comment]
seems to me we are loosing the sentence based cli feel. kubectl is awesome that way.
so whatever we do we should aim for things like:

```
helm install chart foobar
helm describe chart foobar
helm delete chart footer
```
and if we make a distinction between charts and deployment, then we just have a different primitive;

```
helm install deployment foobar
helm describe deployment foobar
helm delete deployment foobar
```

**Comment by michelleN** [comment]
I think there is definitely value in that sort of cli feel. 
kubectl can do that because resources have the same set of defined actions.. I don't think helm has that kind of consistency. 
Installing a chart in turn creates a deployment and you can then do different things with that deployment. You could install a chart but not install a deployment.. don't know what that would mean.

The top level nouns or resources or "things" in the helm world are chart, deployment, repo, and server, and you interact with nouns things in different ways. Even if we made the verbs the same, they would mean very different things for each noun. So even though the verb would be consistent for the nouns, the behavior would be very inconsistent unlike kubectl.

Given that background, do you still feel the same about about cli feel or disagree with these points? @runseb

**Comment by sparkprime** [comment]
FWIW gcloud is the opposite:

```
gcloud compute instances list
```

Of course, if you speak latin, having the verb at the end is fine, and Deis is a latin word right? :)

I am curious why we don't use a single "apply" for both initial deployment and updates.  This is what Terraform does.  I believe the backing idea is that apply will always bring the world to the requested state, so in that case there is no difference between the initial apply, and some subsequent apply where the world has been interfered with out of band (to delete everything).

**Comment by michelleN** [comment]
@sparkprime so are you suggesting `helm deployment apply [chart] [values.yaml]` ?

**Comment by michelleN** [comment]
cc/ @adamreese

**Comment by jackgr** [comment]
This is a fit and finish issue that should be addressed for MVP.
