### ISSUE TITLE
helm lint: This needs a lot of love

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#689]
`helm lint` needs the following:

- The Chart yaml file should be checked for conformance to the spec
    - The version field should be parsed with `github.com/Masterminds/semver` to verify correctness
- The values.toml file should (if present) be tested for parseability
- The template testing should go through the actual template library

**Comment by prydonius** [comment]
@migmartri and I have been looking into the existing linters in Helm Classic and the chart format docs to get a list of lint rules we can add to Kube Helm.

- Chartfile
  - Chart Name and directory name are the same (E) (#782)
  - Engine is a supported template engine (E) - this currently isn't part of the Chartfile struct, so we can skip this rule for now
  - Email is a valid email address (W)
  - Source and Home are valid URLs (W)

- Templates
  - File names are of the form foo-{kind shortname}.yaml (e.g. cassandra-rc.yaml) (E)
  - Templates are valid yaml after generating (E)
  - Required metadata is present and valid
    - Name, Kind, etc. (E)
    - Labels: provider, app, heritage (W)
  - Replication controllers are using a tagged image version (W)
  - ENV vars are quoted in the compiled templates (W)

- Values
  - Defined values are referenced in the template (W)
  - Any namespaces have a corresponding dependency fetched under /charts (W)

@technosophos @michelleN: would be great to get your feedback on these.

We may also want to add linter rules for some of the requirements we've defined in our [manifest authoring guide](https://github.com/bitnami/charts/blob/master/_docs/authoring-kubernetes-manifests.md), if you're open to that.

**Comment by migmartri** [comment]
After our our discussions we agreed on the implementation of some of the rules pasted above.

In this issue we will tackle only the rules that will prevent the chart to work as expected, in other words, any rule that must raise an error.

There will be another issue to discuss the rules for warning error and suggestions.

### General

- [ ] Add rules directory
- [ ] Rename info into suggestion

### Rules

##### Chart linting (chartfile.go)

- [ ] Check that the name of the chart and the directory name are the same.
- [ ] Validate that the version is bigger than 0.0.0 using semver comparison instead of string comparison.
- [ ] Version is quoted. Semver Build component error might break it 

For every element in the charts.yml:

- [ ] Validate that it contains a valid object type, for example
- [ ] Engine is one of the valid values.
- [ ] Each maintainer contains a name
- [ ] Email has email format
- [ ] Source and home are URL’s (if provided)


##### Template linting (template.go)

- [ ] Validate that the file is a proper yaml file. Currently it just checks that it is go-template parseable. (keep using for client side rendering for now, text/template)
- [ ] Environment variable values should be quoted in the compiled templates. @sameersbn, could you elaborate regarding the issue you run into and if it is still a problem?

#####  Yml values linter (values.yaml)

- [ ] It is a valid YAML file

**Comment by sameersbn** [comment]
> Environment variable values should be quoted in the compiled templates. @sameersbn, could you elaborate regarding the issue you run into and if it is still a problem?

kubectl (linter i believe) expects values of environment variables to be specified as strings. If the value of an environment variable begins with a number or has a truth value (yes/no or true/false), YAML will will interpret these as numbers or boolean values respectively which will cause the kubectl linter to throw errors and fail.

For example, any of the following snippets in a manifest file would cause a deployment to fail.

```yaml
        env:
        - name: MYSQL_PASSWORD
          value: 4ZxK4XBGDVxQHsFw
```

```yaml  
       env:
        - name: PICK_A_NUMBER
          value: 3306
```

```yaml
        env:
        - name: DOES_IT_BLEND
          value: yes
```

In my experience I found that its just a better practice to always use quotes around values for environment variables.

**Comment by sameersbn** [comment]
> Will verify it again

Tested, kubectl create fails with errors such as `unable to decode "mariadb-rc.yaml": [pos 505]: json: expect char '"' but got char '3'`

**Comment by technosophos** [comment]
I actually just ran into a similar, possibly related, issue when I used `foo: yes` (wanting the string "yes") and got the value `foo = true` after parsing. That sort of thing would also happen with env vars. So I can see what @sameersbn is talking about here.

**Comment by technosophos** [comment]
Removing this from Alpha.2 because #833 covered the basics of lint for Alpha.2

**Comment by technosophos** [comment]
I am closing this because all of the tasks are complete for Alpha.3. Any additions to `helm lint` should be filed as separate issues. 🎉
