### ISSUE TITLE
Complex charts and environments

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#765]
Looking through helm classic and new helm I don't see anything that would handle or generalize more complex setups.  A few things that I would have need for and am looking for a general solution.

* Pods that require volumes - Charts have been created for things that in a production setup would need like persistent storage and these charts are created with an Empty directory.  What would be the recommended way for a user to add say and AWS persistent EBS volume or a GCE volume?  Download the chart and directly modify those lines?
* Environmental config - Similar to the above do any recommendations exist for having the helm charts configured per environment for a user?

**Comment by technosophos** [comment]
Volume storage (and things like that): We are anticipating that chart authors will write charts that expose these features fairly richly. (Deis, for example, has a chart that makes it possible to configure object storage from five different sources, including S3, Minio, Azure, and GCS.) There's nothing in Helm Classic or Kubernetes Helm that prevents chart builders from doing this. I am pondering doing some "abstract" charts (le.g. "persistent-storage") that would generate the appropriate persistent storage config for people, and chart developers could simply drop this in as a dependency. This is possible in Kubernetes Helm because we allow templates to import other templates. So the short answer is: if chart developers are careful, we can do this today.

For environmental config, our current recommendation is to change the value of HELM_HOME for your particular environment. However, we're talking about a tool on top of Helm that would provide something closer to, say, Rails' environment concept. We're also talking about adding a Helm config file in $HELM_HOME that could contain environment-specific info. Those features are post-2.0.0-final, though. Maybe 2.1.

**Comment by sstarcher** [comment]
@technosophos thanks for the info

Volume setup can certainly be done it's just a good bit of boilerplate.  For now that will be the approach I'll take.

**Comment by philips** [comment]
@technosophos Do you have a link to the Deis meta-storage chart?

**Comment by technosophos** [comment]
There is some work being done on storage charts in https://github.com/kubernetes/charts. IIRC, the MariaDB chart does some PVC configuration.

The Deis chart is not done yet, but I expect it will show up here: https://github.com/deis/charts

At this point, there are no real action items on this ticket, so I'm closing it. Feel free to re-open if there are still TODOs related to CLI or Tiller. Also, if we want a generic storage chart, someone might file an issue in the Kubernetes Charts repo.
