### ISSUE TITLE
local-cluster.sh command does not work with new Docker for Mac beta

### ISSUE THREAD

**Issue by deinspanjer** [kubernetes/helm#773]
It specifically tries to get the IP address of the docker0 interface, but this inferface won't exist in the new OSX version of Docker once it is released.  The bridge still works fine, but it is hidden inside the xhyve machine, and is not visible.

https://beta.docker.com/docs/mac/networking/ under "Known Limitations"

**Comment by adamreese** [comment]
@deinspanjer Thanks for posting an issue.  

The script assumes docker-machine or linux host.  When on docker-machine it uses `docker-machine ip` rather than looking up the docker0 interface.  I have not worked with the new Mac beta but it might work by passing in the VM ip.  

`KUBE_MASTER_IP=192.168.x.x ./scripts/local-cluster.sh up`

**Comment by adamreese** [comment]
I have tested on kubernetes-anywhere and have helm installed.
https://github.com/kubernetes/kubernetes-anywhere/blob/master/DOCKER_FOR_MAC.md

**Comment by technosophos** [comment]
I think I'm going to close out this issue. Our plan at this point is to not rely upon `local-cluster`, and gradually phase it out as we move to kubernetes-anyway and other similar solutions. It just doesn't seem like a good idea for us to maintain yet another way of starting up a Kubernetes cluster. There's definitely nothing special about Helm that would warrant this.
