### ISSUE TITLE
proto: create TemplateEngine type.

### ISSUE THREAD

**Issue by fibonacci1729** [kubernetes/helm#856]
As TemplateEngine specific configuration grows and to avoid bloat of the chart Metadata type, we will introduce a new type with initial structure:

In "helm/_proto/hapi/chart/template.proto"

```
message TemplateEngine {
    enum Kind {
        UNKNOWN = 0;
        GO_TPL  = 1;
    }

    Kind   kind = 1;
    string name = 2;
}
```

The chart.Metadata type will be updated as follows:

```
message Metadata {
        ...
        TemplateEngine engine = 8;
}
```

**Comment by fibonacci1729** [comment]
@migmartri

**Comment by technosophos** [comment]
Some of the use cases for the `engine` field:

- We want to be able to support some other template engines. Requested so far (from Google):
  - Jsonnet
  - Jinja
- We might want to be able to add auxiliary information about an engine, such as:
  - list of required plugins
  - feature flags (e.g. `enable-foo`)
- Conceivably, we may have versions of an engine, so we _could_ at some point require a _version_ flag.
- It is possible that someone may want to write a custom non-public engine for their stuff. We need to decide whether we want to support this use case out of the box (or, perhaps, whether we want to actively discourage this).

**Comment by technosophos** [comment]
I'm pondering pushing this to 2.1.0-Alpha.1 because we haven't actually had any requests for an alternate template language. I did a test branch to see how this would look, and it's a little invasive to implement.

**Comment by philips** [comment]
@technosophos Who from Google requested the Jinga and Jsonnet features?

**Comment by technosophos** [comment]
It was the original DM team. These days, nobody (even them) have asked for us to go back and implement those.

**Comment by zoidbergwill** [comment]
I'd appreciate Jinja2 being supported a lot, since it has a lot of useful features `gotpl` doesn't, but I understand if it is unnecessary complexity that you don't wanna put into core helm.

**Comment by jgmize** [comment]
I believe alternate template languages like jinja2 and jsonnet could be implemented as [plugins](https://github.com/kubernetes/helm/blob/master/docs/plugins.md) now, but I'm not sure of the limitations. @technosophos do you have any thoughts on this approach?

**Comment by philips** [comment]
Given the interest around jsonnet I think it would be nice to have an update on how plugins could be used here. Right now I don't know if plugins are flexible enough to say swap the template rendering, right @technosophos

**Comment by philips** [comment]
cc @jzelinskie @ant31 @hausdorff

**Comment by hausdorff** [comment]
I talked to @technosophos about this last week, and the tentative plan is to work together on a Jsonnet plugin in mid-May, after the Deis acquisition, and after the changes that make the plugin model flexible enough to support this sort of thing are starting to land. I don't think I'm tipping anyone's hand to say that we're generally very happy to involve anyone who is interested -- feel free to contact me to get looped in.

Let me also fill in a bit of context here so that everyone has enough information to make good decisions -- hopefully Matt will jump in if I've misunderstood something.

To hear Matt tell the tale, Helm initially exposed a plugin specifically so that when a better templating solution came along, there would be a way to gracefully transition customers to the new solution. As this relates to Jsonnet specifically: the sense I get talking to different people is that folks on the core team are very keen to see whether Jsonnet could feasibly be that templating language. And, there was some effort to do this before: my understanding is that Dave Cunningham (the author of Jsonnet) is actually part of the Helm core team, but had to halt work when he went on Paternity leave.

So, when the plugin model is ready for us, I have great interest in picking up the work, at which point it should become clear whether it is realistically feasible as an alternative. It seems to me that the time to talk about what goals that would involve are the next time I talk to Matt, in mid-May.

**Comment by jzelinskie** [comment]
There's an ongoing discussion on the SIG-Apps mailing list about a combined effort towards something like this. If this subject interests you, I urge you to participate in the discussion: https://groups.google.com/forum/#!topic/kubernetes-sig-apps/cRpBZHZsnOo

It'd be great to have some participation from someone from the Helm team.

**Comment by hausdorff** [comment]
Yes, I'm sorry. I would have said something sooner but I only found out on Friday, and then I was out all this week for a family emergency. I was planning on bringing it up either on the list or at the round table discussion mentioned in that thread, that Rick Spencer is organizing.

**Comment by bacongobbler** [comment]
Just pinging now that it is mid-may and the plugin model you mention is in core Helm via `helm plugin`. A decent Helm plugin that renders a chart would be [`helm-template`](https://github.com/technosophos/helm-template), which I think is what @technosophos probably mentioned to you. Feel free to check it out!

**Comment by bacongobbler** [comment]
#2577 is related to this discussion and brought up a good point. We should make the decision to either allow competing template engines in tiller or enforce the yaml template engine.

Marking this as a discussion point for Helm 3.

**Comment by hausdorff** [comment]
@bacongobbler How should an outsider seeking to get involved in this discussion proceed? Just by monitoring that issue?

**Comment by bacongobbler** [comment]
Yup! That or they can attend the helm developer's summit in January as there will quite likely be a few groups interested in discussing Helm 3 topics during the summit. We're still figuring out the logistics of that event so stay tuned in #helm-users (on Slack)!

Regardless of the outcome of that discussion at the summit (if it even happens), monitoring this ticket or #2577 would be a good way to get involved.

cc @michelleN @thomastaylor312

**Comment by thomastaylor312** [comment]
@hausdorff We still need to figure out how we will handle discussing these topics. I'll be working on how we will go forward with it

**Comment by bitsofinfo** [comment]
Ever been any movement on this? jinja2 or another template engine support would be great so alternatives are available to golang templates...

**Comment by technosophos** [comment]
Nobody ever jumped in to do stuff. So in Helm 3, we went this way: https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md

That's a proposal, of course, but if all of the events stuff makes its way in, it'll be fairly easy to add render tooling.
