### ISSUE TITLE
helm delete does not delete secrets

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#960]
If a helm chart has a k8s secret object it deploys OK. 

However,  helm delete does not delete the secret. 

My secret looks like this:
```
# Secrets for OpenAM stack deployment. This will be mounted on all containers so they can get their
# passwords, etc.
# Note that secret vals are base 64 encoded
# base64 of 'password' is 'cGFzc3dvcmQ='
# Watch for trailing \n when you encode!
apiVersion: v1
kind: Secret
metadata:
    name: "openam-secrets"
    annotations:
      "helm.sh/hook": pre-install

type: Opaque
data:
  dirmanager.pw:    {{ b64enc "password" }}
  am.enc.key: TzZRV3dIUE80b3MrekV6M05xbi8yZGFBWVd5aUZFMzINCg==
  amadmin.pw:   {{ b64enc "password" }}
# Install DJ secrets if we are using it as an external config store
{{- if .Values.externalConfigStore }}
---
apiVersion: v1
kind: Secret
metadata:
    name: "dj-secrets"
    annotations:
      "helm.sh/hook": pre-install
type: Opaque
data:
  dirmanager.pw:    {{ b64enc "password" }}
{{- end}}
```

**Comment by prydonius** [comment]
Just had a look, and I think this might not be being deleted because it's a pre-install hook.

**Comment by wstrange** [comment]
Can confirm. If I change the secrets to non-pre-install, they do get deleted OK on helm delete.


I am not sure what the  correct behaviour should be here. Perhaps this is not a bug?

**Comment by technosophos** [comment]
Yeah, this is by design.

Any resource that implements a hook is considered "self-managed". Tiller does not manage these at all (other than watching to see that they hit their initial "ready" state). This works well for things like Jobs, Ingress, and things done in `post-delete` hooks, where there is a good chance that you don't want Tiller to manage the resources.

But looking at the case above, I see what @wstrange is trying to do, and it makes sense. It does seem a little weird to have to do a `post-delete` hook that starts a pod or job that kills the secret above... but right now, that's the way we'd have to do it.

Any thoughts on how we'd want to handle cases like the above?

**Comment by prydonius** [comment]
I'm wondering if secrets are actually a good use-case for hooks. I'm not sure if we're doing this here, but Helm Classic maintained an installation order to ensure secrets were created before other types, which seems like the most reliable way to deal with them.

**Comment by wstrange** [comment]
It seems k8s actually takes care of holding the pod in a pending state until its volumes become available.  Maybe I just got lucky - but the order of secret creation has not been a factor.

**Comment by technosophos** [comment]
That sounds familiar to me. That is why, IIRC, we removed some of the ordering logic in new Helm. If we do end up with an issue there, we should definitely track it as an issue.

I'm going to add something in the docs about how Helm doesn't manage resources created by hooks.
