### ISSUE TITLE
feature: allow namespace to be set in a chart

### ISSUE THREAD

**Issue by adamreese** [kubernetes/helm#980]
Allow namespace to be set in a chart for resources that need to be created in specific namespace

**Comment by Quentin-M** [comment]
+1

**Comment by technosophos** [comment]
@adamreese This is supported now, right?

**Comment by bcorijn** [comment]
What is the current status of this? Can I set the namespace in my chart through a value or will Tiller override this? 

I tried finding some more information in the docs, but there's not much reference to namespaces in there. Nor on setting them explicitly through the chart, or how the value of .Release.Namespace is set.

**Comment by technosophos** [comment]
The problem here comes from the way the Kubernetes library works. It requires you to give it a single namespace that it can manage. If you give it a resource with an alternate namespace, it will happily _create_ that resource, but then subsequent queries for that object will not show the object (because it's in a namespace that differs from the one you gave it).

So essentially:

- You can create resources in multiple namespaces with `helm install`
- You _cannot_ `helm upgrade` them, though (and they may not show up with `helm status`)

Thus, we consider these charts to be unsupported

We'd gladly take a PR that elegantly works around this limitation.

**Comment by InAnimaTe** [comment]
Yeah so I've been playing with this a bit. @technosophos is absolutely right. If your chart includes different objects which you want to exist in different namespaces, that isn't going to work the way you think it does.

Helm seems to have its own concept of namespace based solely on which namespace it implicitly launches on (the default) or which is explicitly passed in at runtime (this is reflected in status output and `Release.Namespace` built-in. It has no knowledge of manifest defined namespaces i.e. `metadata.namespace` so if you were to use that, helm would have no knowledge of it. 

In my eyes, and how I'm (initially) using helm, a chart shouldn't contain objects which transgress multiple namespaces. Additionally, I'm defining the namespace in my values file so i can use `--set` to keep a more consistent workflow. In this case, I can safely continue using helm upgrade and other functions without worrying about mismatches only having to remember helm's reporting of namespace is not valid.

**Comment by bcorijn** [comment]
@InAnimaTe that is how I am doing it now as well, but from @technosophos his answer I could not really deduct if this manual overriding of the Helm `Release.Namespace` is actually supported or it might break at any moment.

**Comment by technosophos** [comment]
Helm does not have it's own concept of namespace. We follow Kubernetes' conception very carefully. The problem is that Kubernetes clients connect _to a specific namespace_ and do their operations from within that namespace. If you tell Helm that you deployed a release to namespace `foo`, it will connect to that namespace to learn about the release.

However, it is possible to connect to one namespace, and then deploy a resource to another namespace by overriding the contextual namespace using the `metadata.namespace:` field in a manifest.

`kubectl` explicitly disallows you from connecting to one namespace and installing into another.

Say I have a manifest that declares itself to be in the `metadata.namespace: cookies`. If I try to install this with `kubectl` pointed to a different namespace, I get this:

```
⇒  kubectl create --namespace default -f ./example.svc
the namespace from the provided object "cookies" does not match the namespace "default". You must pass '--namespace=cookies' to perform this operation.
```

For whatever reason, we never _explicitly disallowed_ this. We just tell people not to do it. While `kubectl` can operate on just one object and override an unconfigured namespace, Helm doesn't have that luxury, since it is almost always dealing with more than one object (some of which are un-namespaced, like TPRs and Namespace kinds).

So what we suggest to people is to use the `--namespace` flag on the CLI, and use (but don't override) `.Release.Namespace`. The `.Release.Namespace` value should always contain the value that was passed as `--namespace`. It's possible to set the default value for `--namespace` by any of the way `kubectl` supports setting a default namespace (see `kubectl config -h`).

That said, you are free to use Helm other ways, provided you understand that there are some known edge cases where Helm will not be able to find certain resources because they were created in a namespace that doesn't match the one you tell Helm to use (with --namespace or through Kube config).

As far as future support goes, we are more likely to try to support multiple namespaces. We are less likely to get stricter about what we allow in charts (unless it really becomes a problem). We'd almost definitely accept a PR that allowed users to export something like `HELM_NAMESPACE` and have that work like using `--namespace`. (We already do this with `--tiller-namespace` and `TILLER_NAMESPACE`).

I know the topic is a little obscure. I hope this at least explained why Helm currently works the way it does.

**Comment by jascott1** [comment]
@adamreese I want to close this due to inactivity and that #2060 seems to have taken over this discussion. However this issue does have a "Upcoming Major" label so wanted to double-check with you first. Can we close this one?

**Comment by adamreese** [comment]
We can close this.

**Comment by morvencao** [comment]
@technosophos Does `helm/tiller` now support to specify `namespace` in chart?
I have done some simple test in my local env:

### env
```
root@llcao-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

root@llcao-master:~# helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"8ddf4db6a545dc609539ad8171400f6869c61d8d", GitTreeState:"clean"}
```

### Create `nginx-chart` and add resource in another namespace:
```
root@llcao-master:~# helm create nginx-chart
Creating nginx-chart
# Default values for nginx-chart.

root@llcao-master:~# cat > ./nginx-chart/templates/sleep.yaml <<EOF
>apiVersion: extensions/v1beta1
>kind: Deployment
>metadata:
>  name: sleep
>  {{- if .Values.sleep.anotherNamespace }}
>  namespace: {{ .Values.sleep.anotherNamespace }}
>  {{- end }}
>spec:
>  replicas: 1
>  template:
>    metadata:
>      labels:
>        app: sleep
>    spec:
>      containers:
>      - name: sleep
>        image: "{{ .Values.sleep.repository }}:{{ .Values.sleep.tag }}"
>        command: ["/bin/sleep", "3650d"]
>        imagePullPolicy: IfNotPresent
>EOF

root@llcao-master:~# cat >> ./nginx-chart/values.yaml <<EOF
>sleep:
>  anotherNamespace: istio-system
>  repository: pstauffer/curl
>  tag: v1.0.2
>EOF
```

### Install the chart:
```
root@llcao-master:~# helm install ./nginx-chart --name nginx --namespace default
```

### Check the release status:
```
root@llcao-master:~# helm status nginx
LAST DEPLOYED: Tue Feb 12 02:47:31 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME               TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
nginx-nginx-chart  ClusterIP  10.0.52.211  <none>       80/TCP   9m

==> v1beta2/Deployment
NAME               DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
nginx-nginx-chart  1        1        1           1          9m

==> v1beta1/Deployment
sleep  1  1  1  1  9m

==> v1/Pod(related)
NAME                               READY  STATUS   RESTARTS  AGE
nginx-nginx-chart-c6c9778cc-vq5r5  1/1    Running  0         9m
sleep-789c4b4667-5q4dr             1/1    Running  0         9m


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=nginx-chart,release=nginx" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

The status shows that the `sleep` resources can be listed, although it's in another namespace(`istio-system`), instead of chart release namespace(`default`)

### Check the sleep deployment tag:
```
root@llcao-master:~# kubectl -n istio-system get deploy sleep -owide
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS                 IMAGES
sleep                    1         1         1            1           112s   sleep                      pstauffer/curl:v1.0.2
```

### Upgrade the release with new sleep image:
```
root@llcao-master:~# helm upgrade nginx --set sleep.tag=v1.0.3 ./nginx-chart
Release "nginx" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Feb 12 02:43:57 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta2/Deployment
NAME               DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
nginx-nginx-chart  1        1        1           1          3m

==> v1beta1/Deployment
sleep  1  1  0  1  3m

==> v1/Pod(related)
NAME                               READY  STATUS       RESTARTS  AGE
nginx-nginx-chart-c6c9778cc-jmkdr  1/1    Running      0         3m
sleep-789c4b4667-z2sr6             1/1    Terminating  0         3m
sleep-85bbdf484d-jm97t             0/1    Pending      0         0s

==> v1/Service
NAME               TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
nginx-nginx-chart  ClusterIP  10.0.117.236  <none>       80/TCP   3m


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=nginx-chart,release=nginx" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

### Check if sleep image is upgraded
```
root@llcao-master:~# kubectl -n istio-system get deploy sleep -owide
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS                 IMAGES
sleep                    1         1         1            0           3m34s  sleep                     pstauffer/curl:v1.0.3
```

The sleep image has been upgraded from `v1.0.2` to `v1.0.3` successfully.

### Delete the release:
```
root@llcao-master:~# helm delete nginx --tls --purge
root@llcao-master:~# kubectl -n istio-system get deploy sleep
Error from server (NotFound): deployments.extensions "sleep" not found
```

We can see that the `sleep` resources has also been removed after the chart is deleted.

So can we say the `helm/tiller` now supports specify resources in other namespace other than the `.Release.Namespace`?
